### ISSUE TITLE
How to authenticate when creating a service instance  with the apiaccess plan

### ISSUE THREAD

**Issue by sayortanaka** [SAP/cloud-security-xsuaa-integration#1011]
Hi team,

I was able to authenticate in case of creating a service instance  with the application plan, 
https://github.com/SAP/cloud-security-xsuaa-integration/tree/main/samples/spring-security-xsuaa-usage

but It fails  in case of apiaccess plan.

Please tell me the code for reference.

- Spring Boot:2.7.1, xsuaa-spring-boot-starter:2.11.13
- Environment: Cloud Foundry
- 2760424 - API Access to xsuaa Configuration Data: https://launchpad.support.sap.com/#/notes/2760424

**Comment by liga-oz** [comment]
Hi @sayortanaka,

the `apiaccess` plan is not supported by default in the security client libraries. However, it is possible to get it working by providing a custom `XsuaaServiceConfiguration` bean, where you load manually the service configuration for apiaccess plan. Something like this:

```java
@Bean
public XsuaaServiceConfiguration xsuaaServiceConfiguration(){
    OAuth2ServiceConfiguration conf = CFEnvironment.getInstance().loadForServicePlan(Service.XSUAA, CFConstants.Plan.APIACCESS);
    return new XsuaaServiceConfiguration() {
        @Override
        public String getUaaUrl() {
            return conf.getProperty("url");
        }
        @Override
        public String getAppId() {
            return conf.getProperty(CFConstants.XSUAA.APP_ID);
        }
        @Override
        public String getUaaDomain() {
            return conf.getProperty(CFConstants.XSUAA.UAA_DOMAIN);
        }
        @Nullable
        @Override
        public String getVerificationKey() {
            return conf.getProperty(CFConstants.XSUAA.VERIFICATION_KEY);
        }
        @Override
        public String getClientId() {
            return conf.getClientId();
        }
        @Override
        public String getProperty(String name) {
            return Objects.requireNonNull(conf.getProperty(name));
        }
        @Override
        public String getClientSecret() {
            return conf.getClientSecret();
        }
        @Override
        public ClientIdentity getClientIdentity() {
            ClientIdentity identity = new ClientCertificate(conf.getProperty(CFConstants.CERTIFICATE), conf.getProperty(CFConstants.KEY), getClientId());
            if (!identity.isValid()) {
                identity = new ClientCredentials(getClientId(), getClientSecret());
            }
            return identity;
        }
    };
}
```

❗ Please upgrade to the latest security client library version which is 2.13.3 it includes important bug fixes!

Kind Regards,
Liga

**Comment by sayortanaka** [comment]
Hi @liga-oz,

Thank you for your quick response and the upgrade information.
This problem was resolved thanks to your support.

Regards,
Tanaka
