### ISSUE TITLE
How to mock token exchange endpoint /oauth/token

### ISSUE THREAD

**Issue by adamandre79** [SAP/cloud-security-xsuaa-integration#1033]
Hello colleagues,

in our application we use the following security library:

```
            <dependency>
                <groupId>com.sap.cloud.sjb.cf</groupId>
                <artifactId>sap-java-buildpack-bom</artifactId>
                <version>1.63.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```
and 
```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>com.sap.cloud.security</groupId>
            <artifactId>resourceserver-security-spring-boot-starter</artifactId>
        </dependency>
```

And we are using Spring boot 2.7.5.

We have several dependencies to other services, here most of them we mock if we start our application locally, but not all. 
We need to call a token exchange if we want to call the dependencies which we do not want to mock.

During token exchange the endpoint `/oauth/token` is tried to call but as there is no wiremock server configured for this, this will fail.
So, the question is, if there is a way to mock this endpoint with library `java-security-test`.

Regards
André

**Comment by liga-oz** [comment]
Hi @adamandre79,

java-security-test main goal is to generate a JWT which you can call your app's secured endpoints with, configure identity service and stub calls to identity service (JWK endpoint) https://github.com/SAP/cloud-security-xsuaa-integration/tree/main/java-security-test#unit-test-utilities.
 
In your case I believe you could setup mock server for `/oauth/token` and return the generated JWT and then the service that is expected to consume this token, needs to be configured with `XsuaaExtension` for example like here: https://github.com/SAP/cloud-security-xsuaa-integration/blob/main/samples/spring-security-hybrid-usage/src/test/java/sample/spring/security/junitjupiter/TestControllerXsuaaTest.java#L27

Kind Regards,
Liga

**Comment by adamandre79** [comment]
Hello @liga-oz ,

thanks for the answer. In the xsuaa library there is a class which we use to implement our own answer for the endpoint `oauth/token`: `XsuaaMockWebServer`. Is there something equal in the new java security library?

Regards
André

**Comment by liga-oz** [comment]
Hi @adamandre79,

Here's code snippet:
https://github.com/SAP/cloud-security-xsuaa-integration/blob/main/java-security-test/src/test/java/com/sap/cloud/security/test/extension/SecurityTestExtensionTest.java#L61-L63

Kind Regards,
Liga

**Comment by adamandre79** [comment]
Hello @liga-oz ,

thanks for the code snippet, but unfortunately this is not working, because I'm not talking about unit tests, but I want to start the app locally on my machine without having the possibility to have this test context.

But what I understand is, that there is no class like `XsuaaMockWebServer`, so I need to search for an other way.

Regards
André
