### ISSUE TITLE
How to prevent session hijacking

### ISSUE THREAD

**Issue by sayortanaka** [SAP/cloud-security-xsuaa-integration#1057]
Hi team,

Please tell me how to prevent session hijacking.

- client library: org.springframework.boot 2.7.1 , com.sap.cloud.security.xsuaa:xsuaa-spring-boot-starter:2.13.3
- Environment: Cloud Foundry

Steps:

1. Identity Authentication: [Configure Concurrent User Access to the Application](https://help.sap.com/docs/IDENTITY_AUTHENTICATION/6d6d63354d1242d185ab4830fc04feb1/80ead1a7d3cd4e298b0d32295a11889d.html)
Set Warning
> The user can sign in from only one device or browser at a time. If other sessions exist, the user receives a message and will have the option to terminate the other session and sign out.
2. Login using first  device, successful.
3. Login using second  device,  Click「Sign Out & Continue」, successful.
![image](https://user-images.githubusercontent.com/60851892/211715232-630a1997-52b7-4559-8a7a-0751accee5ce.png)

4. Expected behavior is to sign out automatically and become inaccessible on the first device.
   However,  I can access it on both the first device and the second device.

Best regards,
Tanaka

**Comment by liga-oz** [comment]
Hi @sayortanaka,

this library doesn't do session handling, you should be looking in SAP app router direction for it https://www.npmjs.com/package/@sap/approuter?activeTab=readme#session-handling 

or spring itself if you want to do it natively in Java https://docs.spring.io/spring-security/reference/servlet/authentication/session-management.html#ns-concurrent-sessions 

Just a remark - the link to help.sap.com explains configuration for Identity service aka IAS, but the `com.sap.cloud.security.xsuaa:xsuaa-spring-boot-starter` library supports [Xsuaa](https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/6373bb7a96114d619bfdfdc6f505d1b9.html) only 

If you want to use Identity service you should be using this module: https://github.com/SAP/cloud-security-xsuaa-integration/tree/main/spring-security#sap-btp-spring-security-client-library 
here's boot starter for the same https://github.com/SAP/cloud-security-xsuaa-integration/tree/main/spring-security-starter

**Comment by sayortanaka** [comment]
Hi @liga-oz 

Thank you for the reference pages.

By the way, is there any case where the access token becomes invalid before it expires?

Best regards,
Tanaka

**Comment by liga-oz** [comment]
Hi @sayortanaka,

>By the way, is there any case where this library is used to determine that the xsuaa access token is invalid before it expires?

if you mean standard token validation checks like Jwt signature validation, timestamp validation etc. then yes.

Kind Regards,
Liga

**Comment by sayortanaka** [comment]
Hi @liga-oz

Thank you for the reply.
I understood that there are no proprietary implementations associated with the service other than standard token validation checks.

Best regards,
Tanaka
