### ISSUE TITLE
Migration issue for Spring Security. Application start up failure

### ISSUE THREAD

**Issue by sharma-jahnvi** [SAP/cloud-security-xsuaa-integration#1089]
Hello Team,

I am using the below documentation for migration to the spring security and use converter interface through Autowiring instead of xsuaa packages as described in the sample provided in documentation. 
 I have checked the xsappname configuration and tried it in both ways: though VCAP_SERVICES env variable as well as tried adding in application .properties file.
But I am facing the below error while configuration.
Also tried using the custom methods (without using IdentitySourceProvider) which implement the converter interface as mentioned in the sample code provided here:

[documentation:]
https://github.com/SAP/cloud-security-xsuaa-integration/tree/main/spring-security#setup-spring-security-oauth-20-resource-server

sample link:
https://github.com/SAP/cloud-security-xsuaa-integration/blob/main/samples/spring-security-hybrid-usage/src/main/java/sample/spring/security/SecurityConfiguration.java

Error is :

Field authConverter in com.sap.acrs.config.WebSecurityConfig required a bean of type 'org.springframework.core.convert.converter.Converter' that could not be found.

The injection point has the following annotations:
- @org.springframework.beans.factory.annotation.Autowired(required=true)

Library used: org.springframework.boot
spring-boot-starter-security

com.sap.cloud.security
resourceserver-security-spring-boot-starter
2.13.5
org.apache.httpcomponents httpclient - Environment: Cloud Foundry

Any kind of help would be appreciated.
Attaching my WebSecurityConfiguration file for reference.
[WebSecurityConfiguration.zip](https://github.com/SAP/cloud-security-xsuaa-integration/files/10764254/WebSecurityConfiguration.zip)

**Comment by finkmanAtSap** [comment]
Hi @sharma-jahnvi ,

The issue is that the configuration that contains property xsappname could not be found in your environment.
For local testing, you can supply the configuration via application.yaml as described under this link:

https://github.com/SAP/cloud-security-xsuaa-integration/blob/main/spring-security/README.md#minimal-configuration-required

I hope that gets you going!
Best,
Manuel

**Comment by sharma-jahnvi** [comment]
Hi @finkmanAtSap
Hi Manuel 
I had tried this already and also added the same in application .properties file to check if it works. But the issue still persists.
Actually the converter is not having any implementation class defined for it due to which the Spring context is not able to autowire the bean for it. Do we need to create a separate implementation class for this or is there any other way out ?

KIndly let me know in case of some solutions which can be worked upon.
Thanks 
Jahnvi

**Comment by finkmanAtSap** [comment]
Hey Jahnvi,

Sorry to hear that it is not working for you.

The Converter bean that should be found by default for Autowiring is defined in the following Configuration:

https://github.com/SAP/cloud-security-xsuaa-integration/blob/main/spring-security/src/main/java/com/sap/cloud/security/spring/autoconfig/HybridAuthorizationAutoConfiguration.java#L43

As you can see from the Conditional annotations in that file, the Converter bean would not be created if Spring property "sap.security.services.xsuaa.xsappname" is missing, hence my original suggestion to add it to the application.yaml or application.properties when running locally.
Also, the Configuration would not run at all if "sap.spring.security.hybrid.auto" is set to false.

As next step, can you please debug and check if this code section is executing for you?
And if not, double-check that the required properties are available?
