### ISSUE TITLE
Xsuaa dependancy issue with spring boot 3.0

### ISSUE THREAD

**Issue by vatsla20** [SAP/cloud-security-xsuaa-integration#1090]
The pom file :

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.0.1</version>
		<relativePath /> 
	</parent>

		<java.version>1.8</java.version>
		<hana.jdbc.version>2.4.67</hana.jdbc.version>
		<commons-lang3.version>3.11</commons-lang3.version>
		
		<instancemanager-client.version>2.0.23</instancemanager-client.version>

		
		<spring-xsuaa>2.13.5</spring-xsuaa>
		<sap.cloud.security.version>2.13.5</sap.cloud.security.version>
		<apache.httpclient.version>4.5.14</apache.httpclient.version>
		<json-version>20180813</json-version>

	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<version>2.4.6</version>
		</dependency>
		<dependency> 
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-oauth2-jose</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-config</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-oauth2-resource-server</artifactId>
		</dependency>
		<dependency>
			<groupId>com.sap.cloud.security.xsuaa</groupId>
			<artifactId>spring-xsuaa</artifactId>
			<version>2.13.5</version>
		</dependency>
		<dependency> 
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-to-slf4j</artifactId>
		</dependency>

		<dependency>
			<groupId>com.sap.cloud.security.xsuaa</groupId>
			<artifactId>spring-xsuaa</artifactId>
			<version>${spring-xsuaa}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-batch</artifactId>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
		</dependency>
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20211205</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.batch</groupId>
			<artifactId>spring-batch-test</artifactId>
			<version>5.0.0</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-junit-jupiter</artifactId>
			<version>5.0.0</version>
			<scope>test</scope>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>

SecurityConfig. java class :

@Configuration
//@EnableAutoConfiguration
@EnableWebSecurity
@EnableGlobalMethodSecurity(prePostEnabled = true, securedEnabled = true, jsr250Enabled = true)
public class SecurityConfig {
    @Bean
    @ConfigurationProperties("vcap.services.analytics-uaa.credentials")
    public XsuaaCredentials xsuaaCredentials() {
        return new XsuaaCredentials();
    }

    public XsuaaServiceConfiguration xsuaaServiceConfiguration() {
        return new XsuaaServiceConfigurationCustom(xsuaaCredentials());
    }
//    @Autowired
//    XsuaaTokenFlows xsuaaTokenFlows;
    @Bean
    public XsuaaTokenFlows xsuaaTokenFlows() {
        return new XsuaaTokenFlows(
                new DefaultOAuth2TokenService(HttpClientFactory.create(xsuaaServiceConfiguration().getClientIdentity())),
                new XsuaaDefaultEndpoints(xsuaaServiceConfiguration()),
                xsuaaServiceConfiguration().getClientIdentity());
    }

    @Bean
    public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
        // @formatter:off
        http
                .sessionManagement()
                .sessionCreationPolicy(SessionCreationPolicy.STATELESS) // session is created by approuter
                .and()
                .authorizeHttpRequests()
                .anyRequest().authenticated()
                .and()
                .oauth2ResourceServer()
                .bearerTokenResolver(new IasXsuaaExchangeBroker(xsuaaTokenFlows()))
                .jwt()
                .jwtAuthenticationConverter(getJwtAuthenticationConverter());
        // @formatter:on

        return http.build();
    }

    /**
     * Customizes how GrantedAuthority are derived from a Jwt
     */
    Converter<Jwt, AbstractAuthenticationToken> getJwtAuthenticationConverter() {
        TokenAuthenticationConverter converter = new TokenAuthenticationConverter(xsuaaServiceConfiguration());
        converter.setLocalScopeAsAuthorities(true);
        return converter;
    }
    @Bean
    JwtDecoder jwtDecoder() {
        return new XsuaaJwtDecoderBuilder(xsuaaServiceConfiguration()).build();
    }
}
We were trying to add xsuaa authentication to our spring boot application(note : also implements spring batch 5.0.0). While authenticating the http requests the securtityConfiguration file is not able to autowire XsuaaTokenFlows and XsuaaServiceConfiguration. Error is No bean found.

As a work around we have configured the beans manually post that are getting the error:
 Parameter 0 of method setFilterChains in org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration required a bean of type 'org.springframework.security.oauth2.jwt.JwtDecoder' that could not be found.

This issue is resolved by adding
@Bean
    JwtDecoder jwtDecoder() {
        return new XsuaaJwtDecoderBuilder(xsuaaServiceConfiguration()).build();
    }
but while hitting the api endpoints I encounter the issue of
 _java.lang.AbstractMethodError: Receiver class com.sap.cloud.security.xsuaa.extractor.IasXsuaaExchangeBroker does not define or inherit an implementation of the resolved method 'abstract java.lang.String resolve(jakarta.servlet.http.HttpServletRequest)' of interface org.springframework.security.oauth2.server.resource.web.BearerTokenResolver.
	at org.springframework.security.oauth2.server.resource.web.authentication.BearerTokenAuthenticationFilter.doFilterInternal(BearerTokenAuthenticationFilter.java:119) ~[spring-security-oauth2-resource-server-6.0.1.jar:6.0.1]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.0.3.jar:6.0.3]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:374) ~[spring-security-web-6.0.1.jar:6.0.1]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:107) ~[spring-security-web-6.0.1.jar:6.0.1]_

**The main issue seems to be with conflicting dependencies, with the xsuaa dependencies, is the latest version of com.sap.cloud.security.xsuaa not compatible with spring boot 3.0?**

**Comment by finkmanAtSap** [comment]
Hi @vatsla20 ,

Spring Boot 3.0 is unfortunately not yet supported. You can find more information here: https://github.com/SAP/cloud-security-xsuaa-integration/issues/809

Best,
Manuel

**Comment by vatsla20** [comment]
Thank you for the information.
But are there any alternatives or suggestions at the current moment  for the same, as our project is based on spring boot 3.0 ?
