### ISSUE TITLE
The Repo describes feature around GET methods for Controllers. Can you please also guide with an example for POST requests using a simple thymleaf form, because when i used the repo to extend for a POST method and deploying the app in CF. I am getting an error on POST CALL saying that x-csrf-token is not found.

### ISSUE THREAD

**Issue by sunny13nitk** [SAP/cloud-security-xsuaa-integration#1097]
The Repo describes feature around GET methods for Controllers. Can you please also guide with an example for POST requests using a simple thymleaf form, because when i used this repo to extend for a POST method and deploying the app in CF. I am getting an error on POST CALL saying that x-csrf-token is not found. Is there a way to bind the POST/PUT methods with the token thus obtained as we are doing for GET methods.

Regards
Sunny
Mail: sunny13nitk@gmail.com

**Comment by finkmanAtSap** [comment]
Hi Sunny,

The tokens validated in our samples are access tokens, not CSRF tokens.
This project has nothing to do with CSRF protection mechanisms.
Instead, approuter is responsible for this which is used in our samples.

I don't know which client you use to make requests to the deployed app but requests other than GET need to include a CSRF token to protect against CSRF.
To obtain such a token, the client needs to make a specific kind of request first after establishing a session with the approuter.

For more information, please see https://help.sap.com/docs/btp/sap-business-technology-platform/application-router-configuration#csrf-protection

Best,
Manuel
