### ISSUE TITLE
Logback was introduced as a dependency of token-client in release 2.13.6

### ISSUE THREAD

**Issue by patrickhuy** [SAP/cloud-security-xsuaa-integration#1102]
**Issue Summary**
In release 2.13.6 the dependency to logback-classic https://github.com/SAP/cloud-security-xsuaa-integration/blob/2.13.6/token-client/pom.xml#L101-L104

was potentially accidentally added to `token-client`.

In 2.13.5 this was a a test dependency: https://github.com/SAP/cloud-security-xsuaa-integration/blob/2.13.5/token-client/pom.xml#L101-L106 - this is also true for 2.13.2: https://github.com/SAP/cloud-security-xsuaa-integration/blob/2.13.2/token-client/pom.xml#L101-L105

I consider this a bug as it is unexpected for a library to have a dependency to logback (and it's breaking our builds). Also it is not listed in the changelog. It's also making our tests fail with this update.

**Issue Report Checklist**

- [x] Real, current bug
- [x] Not a duplicate  
- [x] Not covered in "Common Pitfalls" section of corresponding module's README.md e.g. [java-security#common-pitfalls](https://github.com/SAP/cloud-security-xsuaa-integration/tree/main/java-security#common-pitfalls)
- [x] Reproducible
- [x] Good summary
- [ ] Well-documented 
    - [ ] log level increased to `DEBUG` debug logs provided
    - [ ] POM provided
    - [ ] dependency tree provided
    - [ ] code snippet provided (when applicable)

**Comment by liga-oz** [comment]
thank you reporting this, yes indeed it should be a test dependency. Will fix it ASAP.

**Comment by liga-oz** [comment]
Version 2.13.7 with the fix is available now.
