### ISSUE TITLE
Support for Spring projects without Boot

### ISSUE THREAD

**Issue by maxvader** [SAP/cloud-security-xsuaa-integration#112]
Hello, I have to mantain a project that is configured to produce a War to be run in a Tomcat environment and internally is a classic Spring application with Spring Security but not Boot.
So now I'm stuck in the situation where I use sap java build pack _but_ I use Spring Security and not Boot.
Neither of the 2 solutions you provide is good for me, I tried to use the artifacts for spring security, starting some beans manually, but it doesen't work.
Can you create a classic Spring solution or simply provide some configuration instructions?
I can't switch to Spring Boot ATM.

**Comment by nenaraab** [comment]
Dear @maxvader 

if you are not interested into the test/mock spring-xsuaa libs, then i have good news for you. 
You should be able to use it without Spring-Boot.

Pls, try first with version 1.4.0:
```xml
                <properties>
	        	<sap.cloud.security.version>1.4.0</sap.cloud.security.version>
        	</properties>
                 <dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-oauth2-jose</artifactId>
			<version>5.1.1.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-config</artifactId>
			<version>5.1.3.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-oauth2-resource-server</artifactId>
			<version>5.1.1.RELEASE</version>
		</dependency>
		<dependency>
			<groupId>com.sap.cloud.security.xsuaa</groupId>
			<artifactId>spring-xsuaa</artifactId>
			<version>${sap.cloud.security.version}</version>
		</dependency>
               <dependency> <!-- as of version 1.5.0-->
                      <groupId>org.apache.logging.log4j</groupId>
                      <artifactId>log4j-to-slf4j</artifactId>
                      <version>2.11.2</version>
               </dependency>
 ```

and then configure OAuth server in your Security Configuration class:
```java
@Configuration
@EnableWebSecurity
@PropertySource(factory = XsuaaServicePropertySourceFactory.class, value = {""})
public class SecurityConfiguration extends WebSecurityConfigurerAdapter {
    
    @Autowired
    XsuaaServiceConfigurationDefault xsuaaServiceConfiguration;

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        // @formatter:off
        http
            .sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS)
        .and()
            .authorizeRequests()
            .antMatchers("/hello-token/**").hasAuthority("Read") // checks whether it has scope "<xsappId>.Read"
            .antMatchers("/actuator/**").authenticated()
            .anyRequest().denyAll()
        .and()
            .oauth2ResourceServer()
            .jwt()
            .jwtAuthenticationConverter(getJwtAuthoritiesConverter());
        // @formatter:on
    }

    Converter<Jwt, AbstractAuthenticationToken> getJwtAuthoritiesConverter() {
        TokenAuthenticationConverter converter = new TokenAuthenticationConverter(xsuaaServiceConfiguration);
        converter.setLocalScopeAsAuthorities(true);
        return converter;
    }

    @Bean
    JwtDecoder jwtDecoder() {
        return new XsuaaJwtDecoderBuilder(xsuaaServiceConfiguration).build();
    }

    @Bean
    XsuaaServiceConfigurationDefault xsuaaConfig() {
        return new XsuaaServiceConfigurationDefault();
    }
}
```

Does this help?

best regards,
Nena

**Comment by maxvader** [comment]
Thank you @nenaraab , I was on a short vacation and I tried your solution today.
I works! But there is one problem with the sample controller.
I can do access control in the SecurityConfiguration class and works as expected,

But some methods of the TestController from your project, copied into my project, don't work as expected:

- @GetMapping(value = "/v1/method")
    @PreAuthorize("hasAuthority('Read')")
   is called even if the user hasn't Read authority, he has only a generic "all" authority.

- @GetMapping(value = "/v2/sayHello")
    public String sayHello(@AuthenticationPrincipal Jwt jwt) {
says jwt is null and throws exception "while trying to invoke the method java.lang.Object.toString() of a null object loaded from local variable 'jwt'"

- v1/sayHello works and prints this: (asteriscs used to cover my data)
{
"client id": "sb-supplyportal-ws-horsa!t11590",
"family name": "*****",
"given name": "****",
"subaccount id": "***************",
"logon name": ***@****",
"scopes": "[supplyportal-ws-horsa!t11590.all, openid]",
"email": "massimo.nanni@horsa.it",
"authorities": "[all]",
"grant type": "authorization_code"
}

**Comment by nenaraab** [comment]
@maxvader 
cool thanks for the feedback

in order to get @PreAuthorize working you need to enable Method security:
https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/samples/spring-security-xsuaa-usage/src/main/java/sample/spring/xsuaa/SecurityConfiguration.java#L34

never tried this in context of non-Spring boot application.

Alternatively, you can get the jwt token via SecurityContext.getToken().... see also here:

https://github.com/SAP/cloud-security-xsuaa-integration/blob/5eb083425476fd47007712bbf2be31d62ec41d49/spring-xsuaa/README.md#access-usertoken-information

**Comment by maxvader** [comment]
Thank you, method level security works, even in non boot scenario!

**Comment by nenaraab** [comment]
@maxvader 
please also try with version `1.6.0` (this should - not like version `1.5.0`) be again compatible with NON-Spring Boot apps.

Best regards,
Nena
