### ISSUE TITLE
Incompatible value returned from token.getUsername, token.getClientId in security-xsuaa 1.6.0

### ISSUE THREAD

**Issue by nehasonisap** [SAP/cloud-security-xsuaa-integration#125]
Hi,

We recently migrated to security-xsuaa 1.6.0 and we are facing some issue with respect to the values which are being returned from SpringSecurityContext.token.getUsername(), SpringSecurityContext.token.getClientId(). 

These APIs are returning values different than what we used to get using the UserInfo - SecurityContext.getUserInfo().getLogonName() and SecurityContext.getUserInfo().getClientId().

We are aware that UserInfo is deprecated and we assumed that we need to use the APIs from token to get the user name and client id, but we noticed that the values have a client/user prefix in the values returned.

**Old value of user name in technical token from method SecurityContext.getUserInfo().getClientId()** – sb-ProductApp-bl-paas-test!b4943|businesslogging-sb-test!b3598

**New value of user name in technical token from method SpringSecurityContext.token.getClientId()** – client/sb-ProductApp-bl-paas-test!b4943|businesslogging-sb-test!b3598
 
**Old value of user name in user token from method SecurityContext.getUserInfo().getLogonName()** - buslog.icbs@sap.com
**New value of user name in user token from method SpringSecurityContext.token.getUsername()** – user/xsuaa-monitoring-idp/buslog.icbs@sap.com

There is one more difference where the API getUsername is returning a value even in case of technical token, SecurityContext.getUserInfo().getLogonName() didnt return a value if it was a technical token.

We are using the user name for our DPP APIs which is totally dependant on the user name field which we were reading from the getLogonName API.

We would not want to do a workaround to fix this. Can you please let us know what is the recommendation to handle this incompatible change? 

We were in process of providing a patch and we noticed this change. It would be really helpful if you could let us know what needs to be done at earliest.
 
Thanks in advance!

Neha

**Comment by nenaraab** [comment]
Hi @nehasonisap 
thanks for raising this issue! I'm going to analyse this tomorrow.
Best regards,
Nena

**Comment by nehasonisap** [comment]
Hi Nena, 

I have edited the issue with the method names. Kindly get back to us in case you need any other detail.

Thanks,
Neha

**Comment by nenaraab** [comment]
@nehasonisap thanks - now its clear

**Comment by nenaraab** [comment]
Hi @nehasonisap 

I've checked your concern.
In version 1.6 (current master branch):

- `getLogonName` as well as `getClientId` returns the value from the claim from the JWT, nothing more and is compatible to the SAP Container lib and has not changed. `getUsername`method is a new method from Spring UserDetails which is implemented slightly different to `getLogonName`.

Please check the JWT token content itself, e.g. using bridge tool.
I will close this issue.

Best regards,
Nena

**Comment by nehasonisap** [comment]
Hi Nena,

Sorry, but I did not understand how values **user/xsuaa-monitoring-idp/buslog.icbs@sap.com** and **buslog.icbs@sap.com** from APIs are not different. 

Did you mean the token generation part has changed from our side and it has the value **user/xsuaa-monitoring-idp/buslog.icbs@sap.com**?

Kindly clarify. I will setup a call to discuss this.

Thanks,
Neha

**Comment by nehasonisap** [comment]
Thanks for the help Nena :). We are using the getLogonName now and it returns the expected value. While migrating from java-container-security library to security-xsuaa, we missed to use this API.
