### ISSUE TITLE
Wrong info log

### ISSUE THREAD

**Issue by ralphkiefer** [SAP/cloud-security-xsuaa-integration#130]
The XsuaaServicesParser log a wrong info log @line 64:
			if (attributeString.isPresent()) {
				logger.info("XSUAA VCAP_SERVICES has no attribute with name '{}'.", name);
			}
... which means that if the attribute is present the log states the opposite

![XSUAAServicesParser_WrongInfoLog](https://user-images.githubusercontent.com/54885806/64237235-3e12a300-cefc-11e9-8517-f5f2f5ad49b2.JPG)

**Comment by nenaraab** [comment]
Dear Ralph, thanks for reporting! It is already fixed in `1.7.0`version.
