### ISSUE TITLE
Case sensitivity in "Bearer"

### ISSUE THREAD

**Issue by sivamaravis** [SAP/cloud-security-xsuaa-integration#138]
Hello colleagues,
With the migration to this library, we realized that the header when it comes with the JWT has become case sensitive for "Bearer".

This is being fixed in the spring-security in https://github.com/spring-projects/spring-security/commit/63f2b6094f59cc9ded6a83ac3def4a1726890a8b

This is tagged with 5.2.0.RC1 

Best Regards,
sivaram

**Comment by mwdb** [comment]
The TokenExtractor class is configurable. This is the class that extracts a token from the HTTP request.

As a workaround you can probably copy https://github.com/spring-projects/spring-security/blob/master/oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/web/DefaultBearerTokenResolver.java and configure it as tokenResolver, similar like in https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/samples/spring-security-basic-auth/src/main/java/sample/spring/xsuaa/SecurityConfiguration.java#L58

**Comment by nenaraab** [comment]
@sivamaravis 

thanks for reporting!
I'm going to fix that in the next version.

Best regards,
Nena

**Comment by nenaraab** [comment]
Hi @sivamaravis ,

have you already tested Spring-xsuaa in combination with the new spring security RC version and recognized any issue?

I've analyzed this issue and I do not see any problematic statement in one of our libs. 

In case you have an issue, do not hesitate to reopen the issue with further details :-)

Best regards,
Nena
