### ISSUE TITLE
multiple xsuaa bindings throws exception

### ISSUE THREAD

**Issue by nikamath** [SAP/cloud-security-xsuaa-integration#141]
We are facing similar issue as mentioned in https://github.com/SAP/cloud-security-xsuaa-integration/issues/84.
However, we do not want to expose all the apis to broker plan and would like to differentiate between application and broker. Please suggest what can be done.

**Comment by nenaraab** [comment]
Dear @nikamath,
are you a SAP employee? If yes, I could forward you a blog post which is only available SAP-internally.

**Comment by nikamath** [comment]
Yes, I am. You can mail me at nikita.kamath@sap.com

**Comment by nenaraab** [comment]
Cool, you should have received a mail - so i will close the issue here :-)

**Comment by nenaraab** [comment]
SAP-internal link:
https://jtrack.wdf.sap.corp/browse/NGPBUG-96581?focusedCommentId=1387138&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1387138
