### ISSUE TITLE
The maven-source-plugin artifact version is missing in parent pom

### ISSUE THREAD

**Issue by cristianpetrache** [SAP/cloud-security-xsuaa-integration#142]
The _org.apache.maven.plugins:maven-source-plugin_ plugin is invoked in many modules, but no version is specified. This can be easily fixed by adding the plugin (with some version) in the plugin management section of the parent pom (similarly with _org.apache.maven.plugins:maven-javadoc-plugin_)

**Comment by nenaraab** [comment]
Hi @cristianpetrache 
thanks a lot for the info. We are going to fix that soon.
