### ISSUE TITLE
How to access logged in user's I-Number ?

### ISSUE THREAD

**Issue by boudhayan-dev** [SAP/cloud-security-xsuaa-integration#146]
Hi,

The Token available in the controller of a spring-boot application, after a user logs in via the XSUAA service contains only **email** , and  **name** properties (apart from others). I am using the default SAP ID service on CF. I wanted to know if it is possible to get the user's I-Number/D-Number details from the token as well ? I parsed the token but there doesnt seem to be any field containing this info.

I have configured spring boot for Neo environment where this information is available. Sample snippet - 
```
@GetMapping("/getDetails")
	public ResponseEntity<?> getDetail( Principal principal) {
		String principalNo = principal.getName().substring(1);
                .......
     }
```

**principalNo**  contains the I-Number of the user.  I was wondering is the same possible in CF environment with the XSUAA token ?

**Comment by nenaraab** [comment]
Hi @boudhayan-dev 
we can only offer you the information about the D/I/S User in case it is available as part of the JWT token (Access Token). I think the Token.getLogonName() returns the email adress as well.
Best regards,
Nena

**Comment by boudhayan-dev** [comment]
Hi @nenaraab ,

Yes, Token.getLogonName() returns the email address. I believe, since we login to our CF account via email address and not I/D/C number, thus the above function return email address.

However, my requirement is that I retrieve the I/D/C number of the logged in user in the controllers of the Spring application. As I showed earlier, this is possible from the Principal object in Neo landscape. Neo Landscape is also using the same SAP ID Service. In that case, why is the Emplyoee number (I/D/C) not available in the token in CF ?

I checked my info in - https://accounts.sap.com and it contains the I-Number under User ID field. Doesn't SAP ID service use this info and thus the resulting token returned by XSUAA should contain this as well ? 

I have parsed the Token returned by XSUAA to Spring boot but couldn't find the Employee Number anywhere. How can I configure this ? Any solution ?

**Comment by nenaraab** [comment]
@boudhayan-dev 
AFIK you can configure the SAML attributes in your custom IdP in such a way that it includes the D/I/S User. But as i've understood not all SAML attributes are mapped to the JWT token.

@mwdb what do you think?

**Comment by boudhayan-dev** [comment]
Are there any samples to do this mapping ? Also, how would I go about doing these changes to the SAP ID service. It comes configured as default.

**Comment by nenaraab** [comment]
I would suggest to open a BCP (component BC-CP-CF-SEC-IAM) / or Jira Ticket for the same as this is not the right place to discuss the same.

**Comment by bsrdjan** [comment]
I have the same requirement and interested if this is solved and how?
