### ISSUE TITLE
Redirecting to login page while testing /v1/sayHello service using oAuth token

### ISSUE THREAD

**Issue by manjunathgudisi** [SAP/cloud-security-xsuaa-integration#166]
Hello

As shown in the attached screenshot, while testing the service (/v1/sayHello/) on Postman using oAuth token, Im redireting to login page. Im expecting the JSON response from service. What I'm missing here. Do I need to use xsuaa service of **apiaccess** plan for this?

Getting oAuth2.0 token

<img width="616" alt="Screen Shot 2019-10-21 at 12 10 38 PM" src="https://user-images.githubusercontent.com/6059076/67182169-32236780-f3fc-11e9-94d9-10734bcbab90.png">

Testing the service

<img width="1308" alt="Screen Shot 2019-10-21 at 12 07 30 PM" src="https://user-images.githubusercontent.com/6059076/67182183-3b143900-f3fc-11e9-9854-cbdae53b5226.png">

**Comment by nenaraab** [comment]
Hi @manjunathgudisi

This is as expected. When you call the app router this will initiate the oauth-flow and redirect to the login screen (html) in order to logon the user on the sap cloud identity provider.

That’s why it’s recommended to apply the requests in the browser.

Best regards

**Comment by manjunathgudisi** [comment]
Hi @nenataab

What should I do in order to get the response from Postman. What URL should I use if it’s not app-router URL.

Thanks, Manju

**Comment by nenaraab** [comment]
Hi @manjunathgudisi 
please have a look at this documentation:
https://github.com/SAP/cloud-bulletinboard-ads/blob/Documentation/Security/Exercise_24_MakeYourApplicationSecure.md#call-deployed-service
Best regards,
Nena

**Comment by alphageek7443** [comment]
Hello @nenaraab  
what if we want to consume this service (/v1/sayHello/) in an app having custom native Login UI which help us to generate some kind of token(Oauth token or maybe x-csrf-token) to access it.

Thanks Lalit

**Comment by nenaraab** [comment]
Hi Lilit,

What exactly is your issue?
You want to consume your hello endpoint from another micro service without calling the Approuter?
Is the calling service bound to the same xsuaa instance?


Best regards,
Nena
