### ISSUE TITLE
Upgrade to spring boot version 2.2.x

### ISSUE THREAD

**Issue by hassler-d** [SAP/cloud-security-xsuaa-integration#168]
Version 2.2. of spring boot has been [released](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.2-Release-Notes)

The upgrade implies:
- spring 5.2
- Junit 5
- Java 13 support (8 and 11 are still supported as well)
- Kubernetes detection

As discussed with @nenaraab this should be part of a major version upgrade.

**Comment by mibo** [comment]
Created PR #179 to work on (solve) this.

**Comment by nenaraab** [comment]
SpringBoot 2.2 provides a vulnerability fix and that's why this fix is relevant.

**Comment by hassler-d** [comment]
Version has been upgraded in master. Thank you!
