### ISSUE TITLE
[XSA] CAP Java NG App invalid token

### ISSUE THREAD

**Issue by andre68723** [SAP/cloud-security-xsuaa-integration#187]
Hi,

our Product is available on CF and XSA and we're migrating  to CAP and JavaNG Stack. Deployed on XSA, all request are getting 401 due to missing „uaadomain“ and  JWT Token without  „jku“ und „kid“ 

 error="invalid_token", error_description="JWT verification failed: Cannot verify with online token key, jku, kid, uaadomain is null"

From application side we don't welcome adding the [boilerplate code workaround](XsaCompatibleXsuaaConfiguration.java) to each service. Kindly provide a fix in your lib

Thanks, Andre

**Comment by markuslorenzgmx** [comment]
@andre68723 Hi, I have the same problem. Could you please tell me more about the workaround? Can you provide some example code? Thank you.

**Comment by beckermarc** [comment]
Hi, the workaround is adding the following configuration definition to your application:
```java
package com.sap.cds.examples.playground;

import static com.sap.cloud.security.xsuaa.token.TokenClaims.CLAIM_JKU;
import static com.sap.cloud.security.xsuaa.token.TokenClaims.CLAIM_KID;

import java.net.URI;
import java.net.URISyntaxException;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.oauth2.jwt.JwtDecoder;
import org.springframework.web.client.RestOperations;

import com.nimbusds.jwt.JWT;
import com.sap.cloud.security.xsuaa.XsuaaServiceConfiguration;
import com.sap.cloud.security.xsuaa.token.authentication.TokenInfoExtractor;
import com.sap.cloud.security.xsuaa.token.authentication.XsuaaJwtDecoder;
import com.sap.cloud.security.xsuaa.token.authentication.XsuaaJwtDecoderBuilder;

@Configuration
public class XsaCompatibleXsuaaConfiguration {

	@Bean
	public JwtDecoder xsuaaJwtDecoder(XsuaaServiceConfiguration xsuaaServiceConfiguration, RestOperations restOperations) {
		XsuaaJwtDecoder decoder = (XsuaaJwtDecoder) new XsuaaJwtDecoderBuilder(xsuaaServiceConfiguration).withRestOperations(restOperations).build();
		decoder.setTokenInfoExtractor(new XsaCompatibleTokenInfoExtractor(xsuaaServiceConfiguration));
		return decoder;
	}

	private static class XsaCompatibleTokenInfoExtractor implements TokenInfoExtractor {

		private final XsuaaServiceConfiguration config;

		public XsaCompatibleTokenInfoExtractor(XsuaaServiceConfiguration config) {
			this.config = config;
		}

		@Override
		public String getJku(JWT jwt) {
			String jku = (String) jwt.getHeader().toJSONObject().getOrDefault(CLAIM_JKU, null);
			// XSA fallback
			if(jku == null) {
				jku = config.getUaaUrl() + "/token_keys";
			}
			return jku;
		}

		@Override
		public String getKid(JWT jwt) {
			String kid = (String) jwt.getHeader().toJSONObject().getOrDefault(CLAIM_KID, null);
			// XSA fallback
			if(kid == null) {
				kid = "legacy-token-key";
			}
			return kid;
		}

		@Override
		public String getUaaDomain(JWT jwt) {
			String uaaDomain = config.getUaaDomain();
			// XSA fallback
			if(uaaDomain == null) {
				try {
					uaaDomain = new URI(config.getUaaUrl()).getHost();
				} catch (URISyntaxException e) {
					// bad luck
				}
			}
			return uaaDomain;
		}

	}

}
```

**Comment by nenaraab** [comment]
@beckermarc thanks for sharing!

My little proposals:
- instead of “bad luck” i would log the issue
- instead of  
jku = config.getUaaUrl() + "/token_keys";  
  I would use:  
jku =   
XsuaaDefaultEndpoints(config.getUaaUrl()).getJwksUri();

Best regards,
Nena

**Comment by nenaraab** [comment]
I will close this ticket: the [spring-xsuaa](https://github.com/SAP/cloud-security-xsuaa-integration/tree/master/spring-xsuaa) library will not "officially" support XSUAA on premise. If you still like to leverage [spring-xsuaa](https://github.com/SAP/cloud-security-xsuaa-integration/tree/master/spring-xsuaa) client library in context of XSA on premise, you need to follow the description given here.

Alternatively as of version `2.5.0` we have now released a new plain [Java-security client library](https://github.com/SAP/cloud-security-xsuaa-integration/tree/master/java-security) which fully supports XSA on premise applications. This will replace the SAP internal java-container-security client library and will be incorporated in the SAP Java Buildpack in one of the next versions. In case applications wants to make use of Spring-Security, there is a slim Spring adapter available (as documented [here](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/java-security/Migration_SpringSecurityProjects.md)).

In case you dislike this decision, please reopen the issue AND setup a meeting for further clarifications.
