### ISSUE TITLE
XSUAA service instance expected to be same for UI and backend

### ISSUE THREAD

**Issue by navinkrishnan** [SAP/cloud-security-xsuaa-integration#191]
Hi,

I have a question, Does UI and backend need to be necessarily bound to the same xsuaa service instance ?

In my case, I have a backend with spring security implementation which checks for the scope "Create"

`@ServletSecurity(@HttpConstraint(rolesAllowed = { "Create" }))`

Now, i'm exposing this as a `destination` in my CF.

If i create a new xsuaa instance with different xsappname and bind to the UI application and add the same roles, I get the 401 error when the approuter hits the backend.

I tried to bind the same UI/approuter application  with same XSUAA instance as backend, then i'm able to access

**Comment by nenaraab** [comment]
@navinkrishnan 
exact. All microservices (including application router) that makes up a "business application", should be bound to the same Xsuaa instance. E.g. the business application "web shop" consists of several UIs, approuter, order service, product catalog, ...).

Does this answer your question?

Best regards,
Nena

**Comment by navinkrishnan** [comment]
Hi @nenaraab 

Thank you. Just one more question,

Consider a situation, where the particular backend is offered as Odata Service (Let's say deployed in different account) and people can add it as destination and consume in the UI.
In such scenario, how they can bind to the same service instance ?

How to deal this ? 

Regards,
Navin
