### ISSUE TITLE
Yet another multiple xsuaa bindings question

### ISSUE THREAD

**Issue by pacaceres** [SAP/cloud-security-xsuaa-integration#194]
Hello,

I am encountering a similar issue in my team's project (SAP Cloud SDK) with multiple xsuaa bindings.  While searching for ideas I found your resolved issues and read there is an internal wiki page.  I'm also a SAP employee, so could you forward the page to my email pablo.caceres@sap.com?  Thanks!

**Comment by nenaraab** [comment]
@pacaceres 
SAP-internal link:
https://jtrack.wdf.sap.corp/browse/NGPBUG-96581?focusedCommentId=1387138&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1387138
