### ISSUE TITLE
XSUAA service instance expected to be same for UI and backend [2]

### ISSUE THREAD

**Issue by navinkrishnan** [SAP/cloud-security-xsuaa-integration#195]
Hi @nenaraab 

Continuing, because the issue got closed

https://github.com/SAP/cloud-security-xsuaa-integration/issues/191

Consider a situation, where the particular backend is offered as Odata Service (Let's say deployed in different account) and people can add it as destination and consume in the UI.
In such scenario, how they can bind to the same service instance ?

How to deal with this scenario ?

Regards
Navin

**Comment by nenaraab** [comment]
Hi @navinkrishnan,

of course, in case you like to connect to a remote service this needs to be realized with so-called destination service. Find further information about that here:
https://blogs.sap.com/2018/10/08/using-the-destination-service-in-the-cloud-foundry-environment/

Furthermore, the **Cloud SDK** does support Client Credentials Authentication for connecting to a destination. Its implementation heavily relies on the platform Destination Service. The online documentation lists Client Certificate Authentication as one of its supported features. For a complete overview visit the [SAP Cloud SDK Overview](https://blogs.sap.com/2017/05/10/first-steps-with-sap-s4hana-cloud-sdk/).

Best regards,
Nena
