### ISSUE TITLE
Mapping SAML attributes

### ISSUE THREAD

**Issue by texttechne** [SAP/cloud-security-xsuaa-integration#197]
Hi,

we use a custom Identity Provider and have successfully integrated it into Cloud Foundry following your Spring example. Everything is working so far, except for mapping custom SAML attributes.

Additional used resources:
* General: https://developers.sap.com/tutorials/s4sdk-secure-cloudfoundry.html
* Attributes: https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/4827f0bbe27d459fad8342896d4e569b.html

Actually we have configured `xs-security.json` and stuff and the IDP as well. Analysing the SAML assertions we can see our custom SAML attributes. But we don't get them from the token. The only things that work are these magic variables:
* first_name
* last_name
I call them "magic" because we don't even need to specify them in the security descriptor: They work out-of-the-box. Unfortunately nothing else.

Any help here would be greatly appreciated!

**Comment by nenaraab** [comment]
Hi @texttechne,

seems to be a similar issue to this one #146 
In case the SAML attribute does not appear in the token, you will not be able to access it.

I would suggest to open a BCP (component BC-CP-CF-SEC-IAM) / or Jira Ticket for the same as this is not the right place to discuss the same.
