### ISSUE TITLE
[token-client] clientid not available in UserTokenFlow API

### ISSUE THREAD

**Issue by sbusch-dev** [SAP/cloud-security-xsuaa-integration#207]
Hi,

We are trying to implement a user token flow. As per your documentation, the code should look like:

```
XsuaaToken jwtToken = SpringSecurityContext.getToken();

OAuth2TokenResponse userToken = tokenFlows.userTokenFlow()
                .token(jwtToken)
                .clientId(<client_id>) // this is optional
                .subdomain(jwtToken.getSubdomain()) // this is optional      
                .attributes(additionalAttributes) // this is optional
                .execute();
```
The clientid however is not available in the fluent API. I have tried versions 2.3.0 and 2.4.1-SNAPSHOT. None of them has a clientid.

BR Stefan

**Comment by nenaraab** [comment]
Dear @sbusch-dev 
thanks for raising this issue. I have adapted the Readme.

In this case, if you like to issue a token for a "foreign" client you need to create your own [`XsuaaTokenFlow`](token-client/src/main/java/com/sap/cloud/security/xsuaa/tokenflows/XsuaaTokenFlows.java) (Bean).

Example:
```java
public XsuaaTokenFlows createCustomFlow(RestOperations restOperations,
     XsuaaServiceConfiguration serviceConfiguration) {

   OAuth2ServiceEndpointsProvider endpointsProvider = new XsuaaDefaultEndpoints(serviceConfiguration.getUaaUrl());
   ClientCredentials clientCredentials = new ClientCredentials(<your client id>, <your client secret>);
   OAuth2TokenService oAuth2TokenService = new XsuaaOAuth2TokenService(restOperations);
   return new XsuaaTokenFlows(oAuth2TokenService, endpointsProvider, clientCredentials);
}
```

> When defining another `XsuaaTokenFlow` bean, this may override the one, which is autoconfigured with [XsuaaTokenFlowAutoConfiguration](spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/autoconfiguration/XsuaaTokenFlowAutoConfiguration.java#L55) when using `xsuaa-spring-boot-starter`.

**Comment by nenaraab** [comment]
Please let me know, in case you have an idea on how to improve the API for that use case!
