### ISSUE TITLE
Supportability via SAP_EXT_TRL

### ISSUE THREAD

**Issue by andre68723** [SAP/cloud-security-xsuaa-integration#223]
It used to be possible to see the jwt token in the application log by providing env parameters 
```
cf/xs set-env <app> SAP_EXT_TRC stdout
cf/xs set-env <app> SAP_EXT_TRL 3
cf/xs restage <app>
```
This made life a lot easier when jwt tokens were needed to be obtained for support issues. 
Seems to come originally from SAPSSOEXT library

**Comment by nenaraab** [comment]
As implemented here:
https://github.com/SAP-samples/cloud-sapjwt#error-situations

**Comment by nenaraab** [comment]
@hassler-d 
Can you please take over?

**Comment by hassler-d** [comment]
> @hassler-d
> Can you please take over?

Yes sure! 



> It used to be possible to see the jwt token in the application log by providing env parameters
> 
> ```
> cf/xs set-env <app> SAP_EXT_TRC stdout
> cf/xs set-env <app> SAP_EXT_TRL 3
> cf/xs restage <app>
> ```
> 
Can you explain to me or show me some information about what SAP_EXT_TRL means?

**Comment by hassler-d** [comment]
Hello @andre68723,

we have extended the logging. If you set the logging level to debug and the validation of JWT tokens fails, you 
will see a log message like this:

```log
[main] WARN com.sap.cloud.security.token.validation.ValidationResults - Issuer is not trusted because 'iss' 'http://auth.com' does not match host 'myauth.com' of the identity provider.
[main] DEBUG com.sap.cloud.security.token.validation.CombiningValidator - Validator that caused the failed validation: com.sap.cloud.security.token.validation.validators.JwtIssuerValidator
[main] DEBUG com.sap.cloud.security.token.validation.CombiningValidator - Object of type com.sap.cloud.security.token.XsuaaToken that caused the failed validation: 
Jwt header
	{"jku":"http://auth.com/token_keys","kid":"key-id-0","alg":"RS256"}
Jwt payload
	{"aud":["clientId"],"ext_attr":{"enhancer":"XSUAA","zdn":"theSubdomain"},"grant_type":"user_token","user_name":"testUser","origin":"userIdp","iss":"http://auth.com","exp":"6974031600","cid":"clientId"}
```
This would display the content of JWT header and payload. This feature will be part of the 2.7.5 release of this library.

It will be available in the SAP Java Buildpack with the next release (by the end of next week).
See the [troubleshooting guide](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/java-security/Migration_SAPJavaBuildpackProjects.md#troubleshooting) and this [sample](https://github.com/SAP/cloud-security-xsuaa-integration/tree/master/samples/sap-java-buildpack-api-usage) on set log level to debug.

Would this be this sufficient for your use case?

Best Regards
Daniel

**Comment by andre68723** [comment]
Hello Daniel,

fine, that would mean the decoded jwt token would be displayed directly?
That would be even better. 

PS: this would only work in failed case? (which is a notable difference)

Thanks!

**Comment by hassler-d** [comment]
Hi @andre68723,

yes it would be displayed just like in the logs in decoded form. 
Right now it would only be logged in failed cases that is correct.
Do you have a use case for the token being logged on non failed cases as well?

**Comment by andre68723** [comment]
Hi Daniel,

well, we used in the past for some FLP issues mostly to do a positive/negative comparison between working and non-working tokens, but this was afair in the node/approuter stack which is not relevant here.

Thank you for bringing the solution into production, that's a nice and useful enhancement!

**Comment by hassler-d** [comment]
Alright, you are welcome!

So it works out for you when the tokens are only printed on failed validation attempts?
You can always extract the token value on non-failed attempts from the application :)

**Comment by andre68723** [comment]
Thanks, closing the issue as implemented
