### ISSUE TITLE
Unused Field

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [SAP/cloud-security-xsuaa-integration#229]
https://github.com/SAP/cloud-security-xsuaa-integration/blob/19f97f6008d60bc071fa8b749f5c95b8f2850752/spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/authentication/ReactiveXsuaaJwtDecoder.java#L36-L38

These fields are never used

**Comment by nenaraab** [comment]
Hi @hassler-d 
i think we can remove the unused private fields.
BR

**Comment by nenaraab** [comment]
@QiAnXinCodeSafe thanks!
