### ISSUE TITLE
Simple token validation failed

### ISSUE THREAD

**Issue by robertofalk** [SAP/cloud-security-xsuaa-integration#246]
Hi,

I'm trying to setup a simple validation without named users, usually used in reusable-services scenarios on cloud foundry.

my xs-security.json looks like this:
```json
{  
  "xsappname":"my-basic-app",
  "authorities": ["$XSAPPNAME.default"],
  "scopes": [  
     {  
        "name":"$XSAPPNAME.default",
        "description":"Default grant access to all endpoints exposed by my-app"
     }
  ]
}
```

Then, in my Servlet code I want to read the zone _id from the token, but I'm getting null as a result of `Token token = SecurityContext.getToken();`.

```java
@ServletSecurity(@HttpConstraint(rolesAllowed = { "default" }))
public class CurrencyConverterServlet extends HttpServlet {
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        Token token = SecurityContext.getToken();
    }
}
```

am I missing something here?

Best regards,
Roberto Falk

**Comment by robertofalk** [comment]
btw, I'm following this example: https://github.com/SAP/cloud-security-xsuaa-integration/blob/2.5.1/samples/java-security-usage/src/main/java/com/sap/cloud/security/samples/HelloJavaServlet.java

**Comment by nenaraab** [comment]
Hi @robertofalk 

honestly, i do not understand...
The SecurityContext is only instantiated in case the token is valid and you should be able to access it (within the same thread). In case the token is not valid it will never enter the doGet method.

Please set a breakpoint in `AbstractTokenAuthenticator` class and `validateRequest` method and provide me the decoded token.

-> For that, fetch the ` authorizationHeader` from the debugger. Remove the "Bearer " from the beginning and can decode the token on this website: https://jwt.io/

kind regards,
Nena

**Comment by robertofalk** [comment]
Hi @nenaraab,

My token is valid, because the scope `default` is correctly validated. 
Any specific reason that I need to get the token from `validateRequest`? because I can simply provide you the token that I'm generating manually. But I guess when you see the reply, the token will be already expired. 

Best regards,
Roberto Falk

**Comment by nenaraab** [comment]
Hi @robertofalk 

I've checked your github and it's now clear... as i've assumed you've followed the sample only partially. 

You need to decide for 
a) [Token Validation for Java web applications using SAP Java Buildpack](https://github.com/SAP/cloud-security-xsuaa-integration#token-validation-for-java-web-applications-using-sap-java-buildpack) or
b) [Token Validation for Java web applications](https://github.com/SAP/cloud-security-xsuaa-integration#token-validation-for-java-applications) but then you need to copy the`JettyTokenAuthenticator` class as well: https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/samples/java-security-usage/src/main/java/com/sap/cloud/security/samples/tmp/JettyTokenAuthenticator.java

Best regards,
Nena

**Comment by robertofalk** [comment]
thanks!
