### ISSUE TITLE
Check for Not Authenticated

### ISSUE THREAD

**Issue by Alexaas** [SAP/cloud-security-xsuaa-integration#254]
Hi, 
if somebody trys to login to our app without token it fails here:
https://github.com/SAP/cloud-security-xsuaa-integration/blob/0573c1890afd53e6235122449039bd4307b277dc/spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/SpringSecurityContext.java#L34

In certain cases we need to handle this. E.g. we would like to write this situation to audit log. So a concrete exception or an "isAuthenticated" method would be helpful. Please check. 

Thanks and Regards,
Alex

**Comment by nenaraab** [comment]
Hi @Alexaas 
good idea. Any suggestion about the exception name?
Best regards,
Nena

**Comment by Alexaas** [comment]
Why not just throwing AccessDeniedException as you do some lines before?

**Comment by Essenpreis** [comment]
@alstolten . Finalized the version. Wdyt? Want to give me a review?

**Comment by nenaraab** [comment]
Done with version 2.6.0
