### ISSUE TITLE
Could not find clear instructions for replacing the SAPOfflineTokenService bean in spring-xsuaa 

### ISSUE THREAD

**Issue by kiranbadala** [SAP/cloud-security-xsuaa-integration#266]
Hi Colleagues,

Currently, we are using SAPOfflineTokenService bean in our security configuration file. Since it's not supported any more in new spring-xsuaa, please provide clear instructions on the impact and workable solution for the same in the new spring-xsuaa.

**Comment by nenaraab** [comment]
Hi,

i guess, you're implementing a SpringBoot application - i guess - and you want to migrate from SAP java container security library.

This should document all required steps:
https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/spring-xsuaa/Migration_JavaContainerSecurityProjects.md

Best regards,
Nena

**Comment by nenaraab** [comment]
please let me know, or reopen this issue, in case this does not solve / answer your question.
