### ISSUE TITLE
Class Cast Exception on sap_java_buildpack

### ISSUE THREAD

**Issue by tnpradeep** [SAP/cloud-security-xsuaa-integration#276]
Hi,

When below line of code is executed on sap_java_buildpack tomee server, there is a classcast exception error.
` XSUserInfo userInfo = (XSUserInfo) request.getUserPrincipal();`

Error trace:

"written_at":"2020-05-07T11:03:20.633Z","written_ts":3597120321685148,"tenant_id":"-","component_id":"5bd11f39-4929-4b2b-beb6-a2a249bc85ab","DCComponent":"","component_name":"xsuaa-sample","organization_name":"xxxxtrial","component_type":"application","space_name":"dev","component_instance":"0","organization_id":"f2543c08-5a50-4b51-889f-8fb9bc60d6fa","correlation_id":"-","CSNComponent":"","Application":"xxxxx","space_id":"634a0cf3-c2f1-48bf-b4dd-75e0f95ebefd","container_id":"10.0.137.217","type":"log","logger":"org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/].[UserInfo]","thread":"http-bio-0.0.0.0-8080-exec-3","level":"ERROR","categories":[],"msg":"Servlet.service() for servlet [UserInfo] in context with path [] threw exception","stacktrace":["java.lang.ClassCastException: **com.sap.xs.security.container.XSSecurityAuthenticator$XSUserInfoWrapper (loaded by java.net.URLClassLoader@0x0000000100010bf8) cannot be cast to com.sap.xsa.security.container.XSUserInfo** (loaded by org.apache.tomee.catalina.LazyStopWebappClassLoader@0x0000000100230770) (found matching interface com.sap.xsa.security.container.XSUserInfo loaded by java.net.URLClassLoader@0x0000000100010bf8, but needed loader org.apache.tomee.catalina.LazyStopWebappClassLoader@0x0000000100230770)","tat com.sap.xsuaa.sample.userinfo.servlet.UserInfo.doGet(UserInfo.java:35)","tat javax.servlet.http.HttpServlet.service(HttpServlet.java:621)","tat javax.servlet.http.HttpServlet.service(HttpServlet.java:728)","tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)","tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)","tat org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)","tat org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)","tat org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)","tat org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)","tat org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)","tat org.apache.tomee.catalina.OpenEJBValve.invoke(OpenEJBValve.java:44)","tat org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:604)","tat com.sap.xs.security.container.XSSecurityAuthenticator.invoke(XSSecurityAuthenticator.java:131)","tat org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:165)","tat com.sap.xs.java.valves.ErrorReportValve.invoke(ErrorReportValve.java:66)","tat ch.qos.logback.access.tomcat.LogbackValve.invoke(LogbackValve.java:256)","tat org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)","tat com.sap.xs.security.TenantIdValve.invoke(TenantIdValve.java:33)","tat com.sap.xs.security.UserInfoValve.invoke(UserInfoValve.java:19)","tat com.sap.xs.statistics.tomcat.valve.RequestTracingValve.invoke(RequestTracingValve.java:43)","tat com.sap.xs.logging.catalina.RuntimeInfoValve.invoke(RuntimeInfoValve.java:40)","tat org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:755)","tat org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:452)","tat org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1195)","tat org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:654)","tat org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:317)","tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)","tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)","tat org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)","tat java.lang.Thread.run(Thread.java:836)"] }
2020-05-07T11:03:20.648+0000 [RTR/7] OUT xsuaa-sample.cfapps.eu10.hana.ondemand.com - [2020-05-07T11:03:19.228373157Z] "GET /user HTTP/1.1" 500 0 98 "https://xxxxxxx.authentication.eu10.hana.ondemand.com/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0" "-" "10.0.137.217:61019" x_forwarded_for:"-" x_forwarded_proto:"https" vcap_request_id:"f3cbdbfd-11df-4d29-764b-f6766faa3136" response_time:1.420188 gorouter_time:0.000852 app_id:"5bd11f39-4929-4b2b-beb6-a2a249bc85ab" app_index:"0" x_correlationid:"d33b218f-2d6e-4174-455f-a078eb6a5801" tenantid:"-" x_scp_request_id:"844d9729-9650-4013-b201-94504162ab19-5EB3EAF7-2F8ECB9" x_cf_app_instance:"-" x_b3_traceid:"1e39a8a985ef1bd6" x_b3_spanid:"1e39a8a985ef1bd6" x_b3_parentspanid:"-" b3:"1e39a8a985ef1bd6-1e39a8a985ef1bd6"

**Comment by nenaraab** [comment]
Hi @tnpradeep,

thanks a lot for reporting! This github is not the right place to raise an issue with SAP Java Buildpack. 
I keep it open to clarify the next steps here.

Which SAP Java Buildpack version do you use? If you do not specify a dedicated buildpack in your deployment descriptor (e.g. manifest or mta file) you use the latest. The latest buildpack version you can determine with `cf buildpacks`.

Thanks,
Nena

**Comment by hassler-d** [comment]
Hi @tnpradeep,

it would also be interesting to see the dependencies of your app. Can you show us your `pom.xml`? An api dependency not in scope `provided` could cause such an issue.

**Comment by tnpradeep** [comment]
Hi,

Thank you for the reply.
I have pushed my code [here](https://github.com/tnpradeep/xsuaa-sample)

@nenaraab : my manifest of web application is [here](https://github.com/tnpradeep/xsuaa-sample/blob/master/com.sap.xsuaa.sample.userinfo/manifest.yml)
I have provided buildpack as below without any version ,
**buildpack: sap_java_buildpack**

@hassler-d : Here is my [pom.xml](https://github.com/tnpradeep/xsuaa-sample/blob/master/com.sap.xsuaa.sample.userinfo/pom.xml)

**Comment by hassler-d** [comment]
Hi @tnpradeep,

thanks for the links!
I see that you have `java-security` as a dependency in your pom.xml. Why do you have that dependency? You do not seem to be using it. Try to remove the java-security module from your pom.xml.
You will also need to remove the unused imports in your `UserInfo.java`:

```diff
-import com.sap.cloud.security.token.SecurityContext;
-import com.sap.cloud.security.token.Token;
-import com.sap.cloud.security.token.TokenClaims
```

After that your app should work.

Best Regards,
Daniel
