### ISSUE TITLE
spring-xsuaa 2.6.2 with Spring 2.1.13.RELEASE

### ISSUE THREAD

**Issue by githubsree** [SAP/cloud-security-xsuaa-integration#279]
Hi colleagues,

We are currently using spring-xsuaa -> 1.6.0 version.

We want to migrate to latest version as the above one do not support "bearer".
Will spring-xsuaa -> 2.6.2 supported with  spring - 2.1.13.RELEASE?

I believe, the "bearer" support will also be enabled with this.

Thank You
Regards
Sreeram

**Comment by nenaraab** [comment]
Hi @githubsree 
what do you mean with Spring, Spring-Boot 2.1.13 version?
- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter
- https://mvnrepository.com/artifact/org.springframework.security/spring-security-core
- https://mvnrepository.com/artifact/org.springframework/spring

I can not guarantee Spring downward-compatibilties.

- I would suggest you to register for notifications, that you get an email, when new releases are available, and update more frequently.
- For now start with version spring-xsuaa 1.7.0 and check in your code, whether you make use of deprecated methods from spring-xsuaa. The deprecated methods are documented as part of javadoc and explains what to use instead.
- If you have managed all deprecations, upgrade to the latest and check whether it works.
You can find the changelog of all releases here:
https://github.com/SAP/cloud-security-xsuaa-integration/releases

The token-client lib supports bearer grant type as of version 2.5.0.

Best regards,
Nena
