### ISSUE TITLE
Build failure : Failed to execute goal com.sap.cloud.security.cas.dcl:dcl-compiler-plugin:1.0.0-SNAPSHOT:compile (default) on project spring-security-cas: Compilation failed with :ERROR

### ISSUE THREAD

**Issue by trimbandaru007** [SAP/cloud-security-xsuaa-integration#301]
Hi Team,

I am trying to build the samples/spring-security-cas/ project and getting below error

[INFO] --- dcl-compiler-plugin:1.0.0-SNAPSHOT:compile (default) @ spring-security-cas ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.303 s
[INFO] Finished at: 2020-06-07T08:44:51+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.sap.cloud.security.cas.dcl:dcl-compiler-plugin:1.0.0-SNAPSHOT:compile (default) on project spring-security-cas: Compilation failed with :ERROR -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.sap.cloud.security.cas.dcl:dcl-compiler-plugin:1.0.0-SNAPSHOT:compile (default) on project spring-security-cas: Compilation failed with :ERROR
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)

-------------
Here is my java version:
![image](https://user-images.githubusercontent.com/65766494/83959601-67ea6300-a89c-11ea-82f4-26177356074b.png)

Maven version:
![image](https://user-images.githubusercontent.com/65766494/83959614-97996b00-a89c-11ea-8264-5e888327bdf9.png)

Could you please what is going wrong here?

Thanks
-Trim

**Comment by nenaraab** [comment]
Hi @trimbandaru007 
maybe its because of your maven settings.
The dcl plugin is only available SAP internal on SAP Nexus.

Furthermore in your settings.xml you may need to specify to accept SNAPSHOT versions.

E.g.
```xml
<profile>
         <id>snapshot.build</id>
         <pluginRepositories>
            <pluginRepository>
               <id>nexus-central</id>
               <url>http://nexus:8081/nexus/content/groups/build.snapshots/</url>
            </pluginRepository>
         </pluginRepositories>
         <repositories>
            <repository>
               <id>nexus-central</id>
               <url>http://nexus:8081/nexus/content/groups/build.snapshots/</url>
            </repository>
         </repositories>
         <properties>
            <tycho.disableP2Mirrors>true</tycho.disableP2Mirrors>
            <tycho.localArtifacts>ignore</tycho.localArtifacts>
         </properties>
      </profile>
```

please let me know, in case you need further support here...

**Comment by nenaraab** [comment]
Hi @trimbandaru007 

i will close this ticket. Pls let me know, if you still face issues. Then I will re-open it again.

Thx,
Nena
