### ISSUE TITLE
set additional attributes for requestTokenForClient

### ISSUE THREAD

**Issue by hadarkobi** [SAP/cloud-security-xsuaa-integration#305]
We are using XSUserInfoAdapter.requestTokenForClient for creating client token with clientId and clientSecret and we also need the ability to add additional attributes.
Will you support this ability?

Thanks

**Comment by nenaraab** [comment]
Hi @hadarkobi 

can you please describe your use case in more detail?

Thanks!

**Comment by nenaraab** [comment]
hi @hadarkobi 

The `requestTokenForClient()` is kind of deprecated. And was removed from the "new" API as of version `2.0.0` in favor of [XsuaaTokenFlows](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/token-client/src/main/java/com/sap/cloud/security/xsuaa/tokenflows/XsuaaTokenFlows.java) which is provided with [token-client](/token-client) library. 

Best regards,
Nena
