### ISSUE TITLE
zid vs zone_uuid

### ISSUE THREAD

**Issue by matheusrhoden** [SAP/cloud-security-xsuaa-integration#310]
I would like ask for some clarifications related to the recent changes regarding Zones, as my team has been directly accessing the _zid_ claim value of our XSUAA tokens for tenant discrimination. 

Do we need to start using the new `Token.getZoneId()` method, since it will look for a _zone_uuid_ claim and only use _zid_ as a fallback? Or can we trust that _zone_uuid_ will be the same as _zid_ and keep our current implementation? Thanks!

**Comment by nenaraab** [comment]
Hi @matheusrhoden

no, `zone_uuid` is only relevant in context of ias tokens.
In case of xsuaa identity provider `zid` is the right claim to access the token guid.

Best regards,
Nena

**Comment by matheusrhoden** [comment]
Ok, thanks @nenaraab
