### ISSUE TITLE
SecurityContext.getAccessToken() is null when using @Async

### ISSUE THREAD

**Issue by jmargieh** [SAP/cloud-security-xsuaa-integration#311]
Hello,

We are using ```@Async``` spring annotations for asynchronous execution support in Spring.
Method annotated with ```@Async``` will be executed in different thread.

the current implementation of SecurityContext holds the access token on the ThreadLocal.
hence, derived/child threads from the parent thread does not inherit the values set on parent thread.

I would suggest to use: ```InheritableThreadLocal``` instead, so application can take advantage of @Async annotation, CompletableFuture, ...etc.
Please see: https://docs.oracle.com/javase/7/docs/api/java/lang/InheritableThreadLocal.html

Thanks,
Jawad

**Comment by nenaraab** [comment]
Hi @jmargieh 
thanks for the idea. We will evaluate and come back to you. 
In general, are you interested in contributing?
Best regards,
Nena

**Comment by hassler-d** [comment]
Hi Jawad,

thanks for your suggestion!
I have been researching your proposal and found that using `InheritableThreadLocal` might be problematic in conjunction with web servers.
This library often is used inside web servers that use thread pooling. This means that threads for different web requests are being reused. Let's assume we have implemented the `SecurityContext` with `InheritableThreadLocal`.
I could create a child thread inside my request handler and get passed down the `SecurityContext` from the parent. So far so good. But what if the child thread lives on and the parent gets reused for a different request. Do I now have access to the `SecurityContext` from this request? Or is it only passed down once when the child is being created? Do you know this?

Best Regards,
Daniel

**Comment by nenaraab** [comment]
Closing the ticket due to inactivity > 2 weeks. 
In case the issue is still relevant please reopen the ticket.
