### ISSUE TITLE
The sample app is not getting deployed in SAP trial account

### ISSUE THREAD

**Issue by JoyAhan** [SAP/cloud-security-xsuaa-integration#321]
Hi,

I am trying to deploy the sample app in sap-java-buildpack-api-usage . It is failing with the below error

2020-07-01T16:49:59.00+0530 [APP/PROC/WEB/0] OUT [CONTAINER] org.apache.catalina.startup.ContextConfig          SEVERE  Cannot configure an authenticator for method [XSUAA]

Please do let me know if I am missing something

**Comment by mwdb** [comment]
Which buildpack do you use?
You can check with cf app <name>

Should return something like
buildpacks:        sap_java_buildpack

**Comment by hassler-d** [comment]
I can deploy the sample just fine.

**Comment by nenaraab** [comment]
Hi @JoyAhan can we close this ticket?

**Comment by nenaraab** [comment]
Closing the ticket due to inactivity > 2 weeks.If the issue is still relevant please reopen the ticket.
