### ISSUE TITLE
Hide Role Collections From Subscriber Subaccount

### ISSUE THREAD

**Issue by borceacristiann** [SAP/cloud-security-xsuaa-integration#322]
Dear Colleagues, 
 
I am part of the SAP ETD-Cloud team which is working on a multi-tenant application that is deployed  in Cloud Foundry.
 
For authentication, authorization, application routing and role generation we use XSUAA. The roles are created from the mta.yaml which resides in the SAP Application Router. The application is part of the Cloud Foundry subscription and it is multi-tenant based.
 
Is there any possibility to hide custom roles for the subscribed accounts? We would like to have certain roles visible only to our central tenant while others should be available for all the subscribers, including us.
 
Regards,
Borcea Cristian.

**Comment by nenaraab** [comment]
Hi @pianocktail, can you answer this question?

**Comment by pianocktail** [comment]
Hi,
the question is already answered in the SAP internal [JAM](https://jam4.sapjam.com/questions/CeuzmBDvGSvFoOVwvsKMMo) forum but to have it visible also externally I repeat it here:
A common solution is:
1) Create a second service instance. This service instance contains the operator roles and is not subscribed. As it is not subscribed, it is only available in your operator subaccount.
2) Grant scopes to the instance containing  your operator roles.  
Regards
Matthias Bühl

**Comment by borceacristiann** [comment]
Thank you so much :)
