### ISSUE TITLE
Feature request: java-security-test's JwtGenerator to support non-String, non-JSON claims, and blocking "aud"

### ISSUE THREAD

**Issue by patrickmhaller** [SAP/cloud-security-xsuaa-integration#341]
Hi team,

## non-String, non-JSON claims
to simulate arbitrary JWTs during unit testing and integration testing, JwtGenerator is already offering `.withClaimValue()` for Strings and Json-Nodes, or specific methods like `.withExpiration()`.
But there's currently no way to set other non-string, non-JSON claims such as "iat" or "nbf".
We're currently seeing hard-coded defaults and uncontrollable implicit behavior.

## "aud" audience claim
We'd also like to get explicit control over the "aud" claim, which is currently intentionally blocked. The hardcoded values (below) are OK as default, but why blocking access to these internals during unit testing the hard way?
```
JwtGenerator:
	private void createAudienceClaim() {
		if (service == Service.IAS) {
			jsonPayload.put(AUDIENCE, jsonPayload.getString(TokenClaims.XSUAA.CLIENT_ID));
		} else {
			jsonPayload.put(AUDIENCE, Arrays.asList(jsonPayload.getString(TokenClaims.XSUAA.CLIENT_ID)));
		}
	}
```

Both requested cases would help to precisely regenerate a JWT to test specification without any implicit behavior and to react quicker in unit tests to (upcoming) changes in UAA infrastructures.

Thanks,
Patrick

**Comment by nenaraab** [comment]
Hi @patrickmhaller thanks for the feature request => ACCEPTED.

**Comment by nenaraab** [comment]
Hi @patrickmhaller,

I have to revise my statement above...
We have to understand your use-cases first. 

For example the audience is a technical claim, it is only relevant in context of JWT Token Validation, which itself is tested within our client library and MUST NOT be tested again as part of the applications.

Same is true for `nbf`, this is only checked as part of JWT Token Validation. Btw. UAA/XSUAA do not provide `nbf` claim at all.

If we support Instants we may have to support String Arrays... so please provide further details about how you like to leverage `JwtGenerator`.

We can also clarify that next week in a meeting, Daniel is going to setup.

Best regards,
Nena

**Comment by nenaraab** [comment]
see also here: 
https://github.wdf.sap.corp/CPSecurity/Knowledge-Base/tree/master/99_Internal/03_ApplicationSecurity/IntegrationTests

**Comment by hassler-d** [comment]
Hi Patrick,

we have relaxed the `JwtGenerator` so that the audience claim can now be overridden, if needed. We. Expiration can be set via the respective method. We still do not support overriding of "iat" or "nbf" claim values. If you really need this, please get in contact with us.

This will be part of the upcoming 2.7.7. release.

Best Regards
Daniel
