### ISSUE TITLE
cf-logcollector.ps1: Apparently DEBUG xssec* needs to be set for approuter and not (only?) for App

### ISSUE THREAD

**Issue by DerGuteWolf** [SAP/cloud-security-xsuaa-integration#344]
cf-logcollector.ps1: Apparently DEBUG xssec* needs to be set for approuter and not (only?) for App

Also https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/f22d5100b3a243af88e3edf5311754fc.html and cf set-env output recommends to restage and not restart.

**Comment by nenaraab** [comment]
Hi @DerGuteWolf,

sorry, but I do not understand your question / request?

Best regards,
Nena
