### ISSUE TITLE
Performance: ELK logs full of "Jwt token with audience ... is not issued for these clientIds: ..." if multiple 

### ISSUE THREAD

**Issue by patrickmhaller** [SAP/cloud-security-xsuaa-integration#346]
Hi Team,

we do have multiple (two) XSUAA instances to verify inbound JWTs with, hence two XsuaaAudienceValidators with different configuration:

```
    @Bean
    public JwtDecoder getJwtDecoder()
    {
        UaaCredentials xxxApiUaaCredentials = xxxApiUaaCredentials();

        XsuaaAudienceValidator audienceValidator = new XsuaaAudienceValidator(xxxUaaConfig());
        audienceValidator.configureAnotherXsuaaInstance(xxxApiUaaCredentials.getXsAppName(),
                                                        xxxApiUaaCredentials.getClientId());
        return new XsuaaJwtDecoderBuilder(xxxUaaConfig()).withTokenValidators(audienceValidator).build();
    }
```

Hence, we get
1. JwtAudienceValidator with clientIds = [sb-xxx-api-sandbox123!b108, xxx-api-sandbox123!b108]
2. JwtAudienceValidator with clientIds = [sb-xxx-sandbox123!t108, xxx-sandbox123!t108]

The mechanism via `AuthTokenDecoder.decodeAndValidate()` &rarr; `CombiningValidator `&rarr; `JwtAudienceValidator` looks functionally correct, but if the _wrong_ validator is hit first, it always records a warning to ELK via `ValidationResults.createInvalid()` in any case.

In the context of multiple UAAs, could the either this particular logging case be relaxed or the algorithm changed to avoid the log flood?

Thanks,
Patrick

**Comment by nenaraab** [comment]
Hi @patrickmhaller,

have you followed this guide:
https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/spring-xsuaa/Migration_JavaContainerSecurityProjects.md#multiple-xsuaa-bindings

Then i'm not sure, whether there is an easy fix, because you have always two set of validators.

Can you please share with us, which xsuaa plans you make use of, and whether you are already productive or not.

Thanks!

**Comment by nenaraab** [comment]
Question whether this is related to this cloud sdk issue:
https://github.wdf.sap.corp/MA/sdk/issues/3706

**Comment by TanviiG** [comment]
Hi Nena,

We (cloud SDK team) would like to get some insights related to the issue. Following are the questions: 

- What are all the situations where the XSUAA JWT validation would fail?
- Is our assumption correct, that it would fail every time in case of multiple xsuaa service bindings ? 

Regards,
Tanvi

**Comment by nenaraab** [comment]
Hi @TanviiG 

- What are all the situations where the XSUAA JWT validation would fail?
--> pls. check this [spec [SAP internal]](https://github.wdf.sap.corp/CPSecurity/Knowledge-Base/blob/master/03_ApplicationSecurity/TokenValidation.md)
- Is our assumption correct, that it would fail every time in case of multiple xsuaa service bindings ?  
  --> No, spring-xsuaa is the only lib that raises this error message and this can be bypassed by configuring another service as described here: https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/spring-xsuaa/Migration_JavaContainerSecurityProjects.md#multiple-xsuaa-bindings

**Comment by nenaraab** [comment]
remove the "bug" flag. as multiple XsuaaAudienceValidators should never exist. We had a similar issue, when one application was bound to two xsuaa instances of the same type (e.g. application). This is not supported.

**Comment by nenaraab** [comment]
The ticket is in status "Author Action" without any activity for 14 days or longer. Thus, closing the ticket.
Please reopen if the issue is still relevant.
