### ISSUE TITLE
[Consultation] Migration from java container security lib to spring security

### ISSUE THREAD

**Issue by MariaClemence** [SAP/cloud-security-xsuaa-integration#351]
Hello, 

I am working on the migration from java container security client library to Spring Security.

In my existing application using the java container security, I am reading the below information from jwt 
1.	Role collections using system attribute “xs.rolecollections"
String[] roleCollections = userInfo.getSystemAttribute(“xs.rolecollections”);

2.	Read jku from jwt header 
String jku = userInfo.getJKU();

Sample JWT
{
    "alg": "Rxxxxxxx",
    "jku": "https://cxxxxxxxxxxxxxxxx.com/token_keys",
    "kid": "key-id-x",
    "typ": "JWT"
}
.{
    "jti": "exxxxxxxxxxxxxxxx",
    "ext_attr": {
        "enhancer": "XSUAA",
        "subaccountid": "4xxxxxxxxxxxxxxxxxxxxx",
        "zdn": "cxxxxxxxxxxxxx"
    },
    "xs.system.attributes": {
        "xs.rolecollections": ["ManagerRole"]
    },
    ..............
}

Please let me know how to read this information using the new Spring Security APIs, 
Token token = SpringSecurityContext.getToken();

Would I need to parse the jwt to extract this information or are there any APIs available to read this information from the Token?

Thanks,
Vanessa

**Comment by hassler-d** [comment]
Hi Vanessa,

using the `Token` class you can access the data like this:
```java
List<String> rolecollections = token.getClaimAsJsonObject("xs.system.attributes").getAsList("xs.rolecollections", String.class);
```

Best Regards
Daniel

**Comment by MariaClemence** [comment]
> Hi Vanessa,
> 
> using the `Token` class you can access the data like this:
> 
> ```java
> List<String> rolecollections = token.getClaimAsJsonObject("xs.system.attributes").getAsList("xs.rolecollections", String.class);
> ```
> 
> Best Regards
> Daniel

Thanks Daniel. I will try it out.
