### ISSUE TITLE
[Consultation] Getting Tenant for ClientCredentialFlow

### ISSUE THREAD

**Issue by sim-lus** [SAP/cloud-security-xsuaa-integration#352]
Hi colleagues,

we are currently using _ClientCredentialFlow_  and in the case of multitenant applications we are setting the respective tenant from the JWT access token in the following way:
`tokenFlows.clientCredentialsTokenFlow().subdomain(((XsuaaToken)at).getSubdomain());`

We are using tenant information also in other parts of our app, where we get it via
`SecurityContext.getAccessToken().getZoneId();`

Where would we get this tenant information from, if we have a job-style application where there is no JWT token available in the request? Would it be valid to use the property `identityzoneid` from the env variables of the respective XSUAA instance? What is the difference to `tenantid`?

BR Simon

**Comment by hassler-d** [comment]
Hello Simon,

if you have parts in your application that cannot access the `SecurityContext`, you have to provide the information yourself. If it is just a child thread that needs to access this information you could create your own `InheritableThreadLocale` to propagate the required information. But in general this really depends on your application.

Regarding your other question I think they can be answered by XSUAA colleagues. Do you have an D/C/I-User? If yes I can point you to internal resources for that!

Best Regards
Daniel

**Comment by sim-lus** [comment]
Hi Daniel,

thanks for the response, I will contact you via mail.
