### ISSUE TITLE
Compatible spring-xsuaa version and spring-boot version

### ISSUE THREAD

**Issue by ItaiFonio** [SAP/cloud-security-xsuaa-integration#353]
Hi

Our project spring.boot.version is upgrading from 2.2.4.RELEASE to 2.3.2.RELEASE.

Current spring-xsuaa is 1.5.0 which is rather old.

Should I upgrade to latest (version 2.7.5)?

10X, Itai

**Comment by nenaraab** [comment]
Hi @ItaiFonio 

Yes, its always recommended to upgrade to the latest one :-)
We also keep our spring-dependencies up to date.

You can watch the releases, then you get a mail with the latest release notes 
(see also here: https://github.com/SAP/cloud-security-xsuaa-integration/releases)

Best regards,
Nena
