### ISSUE TITLE
Error in Description of new Security Jars.

### ISSUE THREAD

**Issue by harishannamalai** [SAP/cloud-security-xsuaa-integration#356]
New Security Jars referenced in the Document seems to invalid.
File: Migration_SAPJavaBuildpackProjects.md

Description Provided:
**The above mentioned dependencies should be removed / replaced with this one:**

```
<dependency>
    <groupId>com.sap.cloud.security.xsuaa</groupId>
    <artifactId>api</artifactId>
    <version>2.7.3</version>
    <scope>provided</scope> <!-- provided with buildpack -->
</dependency>
```

But in essence the Replacement Jars are:

```
<dependency>
    <groupId>com.sap.cloud.security</groupId>
    <artifactId>java-api</artifactId>
    <version>2.7.3</version>
    <scope>provided</scope> <!-- provided with buildpack -->
</dependency>
```

Please check and Advice.

**Comment by nenaraab** [comment]
Hi @harishannamalai 
yeah, that's confusing, but its correct.

SAP Java Buildpack >= 1.26 provides two open-source "api"s.
1. **com.sap.cloud.security.xsuaa:api** (for compatibility reasons) as described in [Migration Part 1](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/java-security/Migration_SAPJavaBuildpackProjects.md)
2. **com.sap.cloud.security:java-api** as described in [Migration Part 2](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/java-security/Migration_SAPJavaBuildpackProjects.md)

Enjoy your weekend!
Nena
