### ISSUE TITLE
Custom Token generation in case of basic authentication using spring security 5.x version

### ISSUE THREAD

**Issue by rupangshu** [SAP/cloud-security-xsuaa-integration#363]
Hi All, 

I m trying to migrate spring security to latest 5 but while migrating the changes , i m not getting any way to perform custom token generate which we are doing it earlier.
Scenario  _ our usecase is - customer can pass either basic authentication or oauth2 token  , And in our resource server config we  are generating the token based on the basic credentials passed in case of basic oauth .
In case of oauth2 , we are directly validating via xsuaa resource server using jwt token.

Earlier we are using the method for explictly generating oauth token in case of basic auth , 
```
   @Override
    public void configure(ResourceServerSecurityConfigurer resources){
}
```

Below are the existing code which we are planning to migrate to spring security 5.
`@Configuration
@EnableWebSecurity
@EnableResourceServer
public class ResourceServerConfig extends ResourceServerConfigurerAdapter {

   

    @Override
    public void configure(HttpSecurity http) throws Exception {

        
        http.sessionManagement()
                /** session is created by App-router*/
                .sessionCreationPolicy(SessionCreationPolicy.NEVER).and()
                /** demand specific scopes depending on intended request*/
                .authorizeRequests()
                /** enable OAuth2 checks*/
                .mvcMatchers(HttpMethod.POST,path).access(scopes)
                .mvcMatchers(HttpMethod.GET, path).permitAll()
                .mvcMatchers("/**").authenticated();
    }

    @Bean
    protected SAPOfflineTokenServicesCloud offlineTokenServices() {
        return new SAPOfflineTokenServicesCloud();
    }

    @Override
    public void configure(ResourceServerSecurityConfigurer resources){
        resources.tokenExtractor(new TokenExtractor() {
            @Override
            public Authentication extract(HttpServletRequest request) {
               
                try {
                    String JWT = null;
                    String token = null;
                   
                    String toBeDecoded = request.getHeader(Constants.AUTHORIZATION);
                    String[] arr = toBeDecoded.split(" ");
                    if ((Constants.BASIC_AUTH).equals(arr[0])) {
                         token = arr[1];
                        byte[] decoded = Base64.getDecoder().decode(token);
                        Charset charset = Charset.forName("UTF-8");
                        String decodedString = new String(decoded, charset);
                        String clientSecret = decodedString.split(":")[1];
                        String cliendId = decodedString.split(":")[0];

                        
                        JWT = generateJWTtoken(cliendId ,clientSecret );

                        request.setAttribute("accessToken", JWT);
                        PreAuthenticatedAuthenticationToken preAuthenticatedAuthenticationToken = new PreAuthenticatedAuthenticationToken(
                                JWT, clientSecret);
                        preAuthenticatedAuthenticationToken.setAuthenticated(true);
                        return preAuthenticatedAuthenticationToken;
                    } else if (arr[0].equals(Constants.BEARER_AUTH)) {
                        JWT = arr[1];
                        request.setAttribute("accessToken", JWT);
                        PreAuthenticatedAuthenticationToken preAuthenticatedAuthenticationToken = new PreAuthenticatedAuthenticationToken(
                                JWT, null);
                        preAuthenticatedAuthenticationToken.setAuthenticated(true);
                        return preAuthenticatedAuthenticationToken;
                    } else {
                        PreAuthenticatedAuthenticationToken preAuthenticatedAuthenticationToken = new PreAuthenticatedAuthenticationToken(
                                null, null);
                        preAuthenticatedAuthenticationToken.setAuthenticated(false);
                        return preAuthenticatedAuthenticationToken;
                    }
                } catch (IllegalArgumentException | OAuth2AccessDeniedException  e) {
                    PreAuthenticatedAuthenticationToken preAuthenticatedAuthenticationToken = new PreAuthenticatedAuthenticationToken(
                            null, null);
                    preAuthenticatedAuthenticationToken.setAuthenticated(false);
                    return preAuthenticatedAuthenticationToken;
                }
            }
        });
    }
}`

```

**Comment by rupangshu** [comment]
we are using below dependencies for spring security 5.x - 

<dependency> 
    <groupId>org.springframework.security</groupId>
    <artifactId>spring-security-oauth2-jose</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.security</groupId>
    <artifactId>spring-security-config</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.security</groupId>
    <artifactId>spring-security-oauth2-resource-server</artifactId>
</dependency>
<dependency>
    <groupId>com.sap.cloud.security.xsuaa</groupId>
    <artifactId>spring-xsuaa</artifactId>
    <version>2.7.7-SNAPSHOT</version>
</dependency>
<dependency> 
    <groupId>org.apache.logging.log4j</groupId>
    <artifactId>log4j-to-slf4j</artifactId>
    <version>2.11.2</version>
</dependency>

**Comment by nenaraab** [comment]
Hi @rupangshu 

Thanks for your request.
Spring-xsuaa supports already basic authentication.
Pls have a look at this sample:
https://github.com/SAP/cloud-security-xsuaa-integration/tree/master/samples/spring-security-basic-auth

Best regards,
Nena

**Comment by nenaraab** [comment]
Because of inactivity for more than 14 days... I will close this issue.
