### ISSUE TITLE
Performance Issue while using client api to fetch the token

### ISSUE THREAD

**Issue by mohan-agarwal** [SAP/cloud-security-xsuaa-integration#364]
Dear Colleagues,
   We are from OData Provisioning(ODP) on CF. Ours is a java application which is deployed on CF which connects to SAP ABAP Backend system and fetches the data. we need to get the access token for the subscribed account so that we can fetch the destinations configured in the subscribed account. We use Destination and Connectivity components.    
We are following [document](https://github.com/SAP/cloud-security-xsuaa-integration#token-exchange-for-java-applications)  to use  the client-apis to fetch the xsuaa token.

Dependencies added: 
<dependency>
			<groupId>com.sap.cloud.security.xsuaa</groupId>
			<artifactId>token-client</artifactId>
			<version>2.7.6</version>
		</dependency>
		
		<dependency>
		    <groupId>com.sap.cloud.security</groupId>
		    <artifactId>java-security</artifactId>
		    <version>2.7.6</version>
		</dependency> 

Code Snippet to fetch the token:

XsuaaTokenFlows tokenFlows = new XsuaaTokenFlows(
                    new DefaultOAuth2TokenService(), 
                    new XsuaaDefaultEndpoints(xsuaaURL1), 
                    new ClientCredentials(clientId1, clientSecret1));
	XsuaaToken jwtToken = (XsuaaToken) SpringSecurityContext.getToken();
	OAuth2TokenResponse clientCredentialsToken = tokenFlows.clientCredentialsTokenFlow()
                    .subdomain(jwtToken.getSubdomain()) 
                    .execute();

We need to fetch two tokens for the runtime calls: one for destination and other for connectivity.
The time taken to fetch each token varies from 75 ms to 150 ms and total time to fetch both tokens varies from 150 to 350 ms.
As the default cache is enabled so somehow I feel that the time taken to fetch the token is more. Is there any suggestion that you can provide to minimize this time.

url fired is : https://ebaascust03-odptest.cfapps.sap.hana.ondemand.com/odata/IWBEP/RMTSAMPLEFLIGHT;v=1/FlightCollection?sap-statistics=true&$top=1 .

Org: GWaaSNeoOnCF
Space: test
Application Name: odptest-service

Thanks & Regards,
Mohan

**Comment by hassler-d** [comment]
Hi Mohan,

do you fetch the **same token(s)** repeatedly? The cache only helps if you cache the the same token more than once!

I have create a little performance test and the results are as follows:
Without cache my sample app fetched `10 tokens in 1649ms (164ms/request)`
With cache it fetched `10 tokens in 373ms (37ms/request)`

If the token is **not cached** the vast majority of the time is spent waiting for the HTTP request to the XSUAA endpoint to finish. 

Do you observe bad performance when the **same token(s)** are fetched repeatedly? Or only if you fetch the two tokens for the first time?

Best Regards
Daniel

**Comment by mohan-agarwal** [comment]
Hi Daniel,

For every OData call, the token is fetched twice (one for Destination and one for connectivity).

I am repeatedly calling the same url and the fetching these two tokens.

I am observing this bad performance when the same token(s) are fetched repeatedly.

Best Regards,
Mohan

**Comment by hassler-d** [comment]
Hi Mohan,

if the cache is hit, performance should be good. How many odata call do you expect per second/minute? Can you show me the part of the code where you handle the odaca call and fetch the tokens? Maybe the cache is thrown away after each request?
If you have very different caching requirements you can also create two `XsuaaTokenFlows`, one for destination and one for connectivity and configure the `DefaultOAuth2TokenService` caches differently.

Best Regards
Daniel

**Comment by hassler-d** [comment]
Hi Mohan,

in our meeting today we have identified the root cause of the issue. I suggested that you reuse the XsuaaTokenFlow instance so that the cache is actually used. After this your performance problems should be solved. If this does not solve the issue you can of course create a new issue.

Best Regards
Daniel
