### ISSUE TITLE
Is it possible to restrict authorization scopes to provider tenant only?

### ISSUE THREAD

**Issue by frankfangcn** [SAP/cloud-security-xsuaa-integration#366]
Hi colleagues,

It's a consulting issue. 

We developed some admin functions in SaaS service, and these admin functions are to be used by ourselves (should only be used in provider tenant and can't be accessed by customers). In case we don't want to split these functions to a separate service, is it possible to use xsuaa to authorize these functions to be used on provider tenant only? I tried and it seems scopes in xsuaa are always propagated to consumer tenant by saas registry service, thereby can't be hidden from customers.  

Please let me know if any solution for above scenario. Thanks a lot!

Zhongjie

**Comment by nenaraab** [comment]
HI @frankfangcn 
thanks for your request!

- Which client lib do you make use of?
- Your request seems to be similar to [this one](https://github.com/SAP/cloud-security-xsuaa-integration/issues/359). Is that right?

Thanks and best regards,
Nena

**Comment by nenaraab** [comment]
@torsten-sap @kayuweschmidt 
If you like, you can follow up on that feature request...

**Comment by nenaraab** [comment]
Hi @frankfangcn 

so its like that, you have these two options:
1) In the admin endpoints check the call is for your paas xsuaa tenant
2) Hide the roles by defining the scopes in the subscribed xsuaa instance and the corresponding role template in another (not subscribed) xsuaa service instance.

Best regards,
Nena
