### ISSUE TITLE
Server error while obtaining access token from XSUAA (502 BAD_GATEWAY)

### ISSUE THREAD

**Issue by yduong** [SAP/cloud-security-xsuaa-integration#371]
Hi, 

Below is the code I used to get the client credential. Most of the time, the code works, but in one case, it gives me the error. "c.s.c.s.x.c.XsuaaOAuth2TokenService      : Server error while obtaining access token from XSUAA (502 BAD_GATEWAY): 502 Bad Gateway: Registered endpoint failed to handle the request."

Do you have any idea for this ? Attached is the log. [Uploading log.txt…]()

Thank you for your help,
Best regards

XsuaaTokenFlows tokenFlows = new XsuaaTokenFlows(
		tokenService,
                new XsuaaDefaultEndpoints(xsUaaUri),
                new ClientCredentials(clientId, clientSecret));
OAuth2TokenResponse clientCredentialsToken = tokenFlows.clientCredentialsTokenFlow().execute();

**Comment by nenaraab** [comment]
Hi @yduong 

as the client libs logs the issues, that are received from the xsuaa service, i would suggest you to create either a BCP ticket or a JIRA NGPBUG on component "xsuaa".

Thanks and best regards,
Nena
