### ISSUE TITLE
[token-client] Misleading message in TokenFlowException

### ISSUE THREAD

**Issue by hassler-d** [SAP/cloud-security-xsuaa-integration#384]
In case of an error, the `PasswordTokenFlow` in the `token-client` throws a `TokenFlowException` with a misleading message: 

> "Error requesting user token with grant_type 'client_credentials'...

This is wrong because the grant_type in the password token flow is `password` and not `client_credentials`.

**Comment by nenaraab** [comment]
Solved with version 2.7.8
