### ISSUE TITLE
Security Library to support both native java application and spring boot application

### ISSUE THREAD

**Issue by WeiHan0801** [SAP/cloud-security-xsuaa-integration#395]
Hello colleagues,

We are facing a problem now that we have implemented a library(.jar) which is consumed by both native java application and spring boot application. Inside this library, we want to fetch the token. If we use the SpringSecurityContext.getToken() (from java-security.jar), the token is achieved properly inside the native java application. However, in the spring-boot application, we got the following errors. If we use the SpringSecurityContext.getToken() (from spring-xsuaa), the native java application cannot get the token. Do you have any idea how can we get the token in both scenarios? Is there a general way to get token in this case? Thanks a lot for the help and support.

**Error logs for** **SpringSecurityContext.getToken() (from java-security.jar)**: 
java.lang.ClassCastException: org.springframework.security.web.authentication.WebAuthenticationDetails cannot be cast to org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationDetails

Best regards,
Wei

**Comment by nenaraab** [comment]
hi @WeiHan0801,

no, this is not supported.
The APIs between spring-xsuaa and java-security are different...

**in java-security**
https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/java-security/src/main/java/com/sap/cloud/security/adapter/spring/SpringSecurityContext.java#L42
returns a token of this interface:
java-api/src/main/java/com/sap/cloud/security/token/Token.java 

**whereas in spring-xsuaa**
https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/SpringSecurityContext.java#L29 returns a token of this interface:
spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/Token.java

Best regards,
Nena
