### ISSUE TITLE
Sl4j Binding issue with new security Library 

### ISSUE THREAD

**Issue by KaminiSingh** [SAP/cloud-security-xsuaa-integration#398]
Hi ,
I am trying to upgrade my project with the new security libraries following the migration guide 
https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/java-security/Migration_SpringSecurityProjects.md

The application gets started but UI does not come up and the logs had the error 

   2020-10-21T11:16:21.24+0530 [APP/PROC/WEB/0] ERR SLF4J: Class path contains multiple SLF4J bindings.
   2020-10-21T11:16:21.24+0530 [APP/PROC/WEB/0] ERR SLF4J: Found binding in [jar:file:/home/vcap/app/WEB-INF/lib/log4j-slf4j-impl-2.8.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
   2020-10-21T11:16:21.24+0530 [APP/PROC/WEB/0] ERR SLF4J: Found binding in [jar:file:/home/vcap/app/WEB-INF/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
   2020-10-21T11:16:21.24+0530 [APP/PROC/WEB/0] ERR SLF4J: Found binding in [jar:file:/home/vcap/app/META-INF/.sap_java_buildpack/tomcat/lib/logback-classic.jar!/org/slf4j/impl/StaticLoggerBinder.class]
   2020-10-21T11:16:21.24+0530 [APP/PROC/WEB/0] ERR SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
   2020-10-21T11:16:21.24+0530 [APP/PROC/WEB/0] ERR SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]

I resolved these error by excluding the dependencies ..

		<exclusion>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
		</exclusion>

		    <dependency>
				<groupId>org.apache.logging.log4j</groupId>
				<artifactId>log4j-slf4j-impl</artifactId>
				<version>${log4j.version}</version> 	
				<scope>provided</scope>	
			</dependency>

But now I am getting below error and not able to resolve this 

level":"ERROR","categories":[],"msg":"Error configuring application listener of class [com.sap.gateway.core.service.servlet.ServletListener]","stacktrace":["java.lang.LinkageError: loader constraint violation: when resolving method \"org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;\" the class loader \"<unnamed>\" (instance of org.apache.catalina.loader.ParallelWebappClassLoader@3de8a96c, child of java.net.URLClassLoader@61a52fbd) of the current class, org/slf4j/LoggerFactory, and the class loader \"System\" (instance of sun.misc.Launcher$AppClassLoader@4b85612c, child of sun.misc.Launcher$ExtClassLoader@25f38edc, urls: 'file:/home/vcap/app/META-INF/.sap_java_buildpack/postgresql_jdbc/postgresql-42.2.13.jar', 'file:/home/vcap/app/META-INF/.sap_java_buildpack/tomcat/lib/logback-classic.jar', 'file:/home/vcap/app/META-INF/.sap_java_buildpack/tomcat/lib/servlet-api.jar', 'file:/home/vcap/app/META-INF/.sap_java_buildpack/tomcat/lib/logback-core.jar', 'file:/home/vcap/app/META-INF/.sap_java_buildpack/tomcat/lib/jul-to-slf4j.jar', 'file:/home/vcap/app/META-INF/.sap_java_buildpack/tomcat/lib/slf4j-api.jar', 'file:/home/vcap/app/META-INF/.sap_java_buildpack/tomcat/lib/xs-logging.jar', 'file:/home/vcap/app/META-INF/.sap_java_buildpack/tomcat/lib/xsrt-droplet-addon.jar', 'file:/home/vcap/app/META-INF/.sap_java_buildpack/tomcat/lib/com.fasterxml.jackson-core.jar', 'file:/home/vcap/app/META-INF/.sap_java_buildpack/tomcat/lib/com.fasterxml.jackson-databind.jar', 'file:/home/vcap/app/META-INF/.sap_java_buildpack/tomcat/lib/com.fasterxml.jackson-annotations.jar', 'file:/home/vcap/app/META-INF/.sap_java_buildpack/tomcat/bin/xs-jdsr-statistics-api.jar', 'file:/home/vcap/app/META-INF/.sap_java_buildpack/tomcat/bin/xs-jdsr-passport.jar', 'file:/home/vcap/app/META-INF/.sap_java_buildpack/tomcat/bin/xs-jdsr-protocol-handlers.jar', 'file:/home/vcap/app/META-INF/.sap_java_buildpack/tomcat/lib/cf-java-logging-support-core.jar', 'file:/home/vcap/app/META-INF/.sap_java_buildpack/tomcat/lib/cf-java-logging-support-logback.jar', 'file:/home/vcap/app/META-INF/.sap_java_buildpack/tomcat/lib/commons-lang3.jar', 'file:/home/vcap/app/META-INF/.sap_java_buildpack/tomcat/lib/jackson-jr-objects.jar', 'file:/home/vcap/app/META-INF/.sap_java_buildpack/tomcat/bin/bootstrap.jar', 'file:/home/vcap/app/META-INF/.sap_java_buildpack/tomcat/bin/tomcat-juli.jar') for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature","\tat org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:423)","\tat org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)","\tat org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)","\tat com.sap.gateway.core.service.servlet.ServletListener.<clinit>(ServletListener.java:76)","\tat sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)","\tat sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)","\tat sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)","\tat java.lang.reflect.Constructor.newInstance(Constructor.java:423)","\tat org.apache.catalina.core.DefaultInstanceManager.newInstance(DefaultInstanceManager.java:151)","\tat org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4613)","\tat org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5155)","\tat org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)","\tat org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1412)","\tat org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1402)","\tat java.util.concurrent.FutureTask.run(FutureTask.java:266)","\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)","\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)","\tat java.lang.Thread.run(Thread.java:836)"] }
   2020-10-20T14:56:44.57+0530 [APP/PROC/WEB/0] OUT { "written_at":"2020-10-20T09:26:44.577Z","written_ts":1750123719087601,"tenant_id":"-","component_type":"application","component_id":"318c1ed5-d2ce-4fac-8a69-7520ca8f26cb","space_name":"test","component_name":"odptest-service","component_instance":"0","organization_id":"f1aeec1e-4fd4-440f-bd9e-629b352449d7","correlation_id":"-","organization_name":"GWaaSNeoOnCF","space_id":"7524d93e-f1e4-4c9b-a6be-785be4c72bd7","container_id":"10.0.138.87","type":"log","logger":"org.apache.catalina.core.ContainerBase.[Catalina].[localhost].[/]","thread":"localhost-startStop-1","level":"ERROR","categories":[],"msg":"Skipped installing application listeners due to previous error(s)" }

Please let me know what am I doing wrong or How can i resolve this issue ?

**Comment by liga-oz** [comment]
Hi @KaminiSingh,

Are you using SAP Java Buildpack for your project?

Could you please provide dependency tree of your project?

Kind regards,
Liga Ozolina

**Comment by KaminiSingh** [comment]
Hi @liga-oz 

Yes , we are using SAP Java Buildpack for the project .. Below is the Dependency tree..


[INFO] ----------------------< com.sap.odp:odp-service >-----------------------
[INFO] Building OData Provisioning (CF) Service 0.1.0-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.10:tree (default-cli) @ odp-service ---
[INFO] com.sap.odp:odp-service:war:0.1.0-SNAPSHOT
[INFO] +- com.sap.cloud.security:java-security:jar:2.7.4:provided
[INFO] |  +- com.sap.cloud.security:java-api:jar:2.7.4:provided
[INFO] |  |  \- com.google.code.findbugs:jsr305:jar:3.0.2:provided
[INFO] |  +- commons-io:commons-io:jar:2.6:compile
[INFO] |  \- com.sap.cloud.security.xsuaa:token-client:jar:2.7.4:provided
[INFO] |     +- com.sap.cloud.security.xsuaa:api:jar:2.7.4:provided
[INFO] |     \- com.github.ben-manes.caffeine:caffeine:jar:2.8.5:runtime
[INFO] |        +- org.checkerframework:checker-qual:jar:3.4.1:runtime
[INFO] |        \- com.google.errorprone:error_prone_annotations:jar:2.4.0:runtime
[INFO] +- com.sap.gw.rt:service.api:jar:1.33.63:compile
[INFO] |  +- com.google.code.gson:gson:jar:2.8.5:compile
[INFO] |  +- org.apache.poi:poi:jar:4.1.1:compile
[INFO] |  |  +- org.apache.commons:commons-collections4:jar:4.3:compile
[INFO] |  |  \- org.apache.commons:commons-math3:jar:3.6.1:compile
[INFO] |  +- org.apache.poi:poi-ooxml:jar:3.17:compile
[INFO] |  |  \- com.github.virtuald:curvesapi:jar:1.04:compile
[INFO] |  +- org.apache.poi:poi-ooxml-schemas:jar:3.17:compile
[INFO] |  |  \- org.apache.xmlbeans:xmlbeans:jar:2.6.0:compile
[INFO] |  |     \- stax:stax-api:jar:1.0.1:compile
[INFO] |  \- org.liquibase:liquibase-core:jar:3.8.0:compile
[INFO] |     +- org.yaml:snakeyaml:jar:1.26:compile
[INFO] |     \- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |        \- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] +- com.sap.gw.rt:service.persistence:jar:1.33.63:compile
[INFO] +- com.sap.gw.rt:core.api:jar:1.33.63:compile
[INFO] |  +- com.sap.it.commons:com.sap.it.commons:jar:1.14.0:compile
[INFO] |  +- com.sap.it.commons:com.sap.it.commons.logging.slf4j:jar:1.14.0:compile
[INFO] |  \- javax.jms:javax.jms-api:jar:2.0.1:compile
[INFO] +- com.sap.gw.rt:core.runtime:jar:1.33.63:runtime
[INFO] |  +- org.apache.commons:com.springsource.org.apache.commons.codec:jar:1.6.0:compile
[INFO] |  \- com.sap.core.jdsr:com.sap.js.passport.api:jar:1.2.0:runtime
[INFO] +- com.sap.gw.rt:core.bep:jar:1.33.63:compile
[INFO] |  \- com.netflix.hystrix:hystrix-core:jar:1.5.18:compile
[INFO] |     +- com.netflix.archaius:archaius-core:jar:0.4.1:compile
[INFO] |     |  \- commons-configuration:commons-configuration:jar:1.8:compile
[INFO] |     |     \- commons-lang:commons-lang:jar:2.6:compile
[INFO] |     +- io.reactivex:rxjava:jar:1.3.8:compile
[INFO] |     \- org.hdrhistogram:HdrHistogram:jar:2.1.9:compile
[INFO] +- org.apache.olingo:olingo-odata2-core:jar:2.0.11-sap-12:compile
[INFO] +- org.apache.olingo:olingo-odata2-api:jar:2.0.11-sap-12:compile
[INFO] +- org.springframework:spring-context:jar:5.2.8.RELEASE:compile
[INFO] |  +- org.springframework:spring-aop:jar:5.2.8.RELEASE:compile
[INFO] |  +- org.springframework:spring-beans:jar:5.2.8.RELEASE:compile
[INFO] |  +- org.springframework:spring-core:jar:5.2.8.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.2.8.RELEASE:compile
[INFO] |  \- org.springframework:spring-expression:jar:5.2.8.RELEASE:compile
[INFO] +- org.springframework.security:spring-security-config:jar:5.3.4.RELEASE:compile
[INFO] +- org.springframework.security:spring-security-web:jar:5.3.4.RELEASE:compile
[INFO] |  \- org.springframework:spring-web:jar:5.2.8.RELEASE:compile
[INFO] +- org.springframework.security:spring-security-core:jar:5.3.4.RELEASE:compile
[INFO] +- org.springframework.security.oauth:spring-security-oauth2:jar:2.4.1.RELEASE:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:5.2.8.RELEASE:compile
[INFO] +- commons-codec:commons-codec:jar:1.10:compile
[INFO] +- org.eclipse.persistence:eclipselink:jar:2.5.0:compile
[INFO] |  \- org.eclipse.persistence:commonj.sdo:jar:2.1.1:compile
[INFO] +- org.eclipse.persistence:javax.persistence:jar:2.0.4.v201112161009:compile
[INFO] +- javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO] +- org.postgresql:postgresql:jar:42.2.13:compile
[INFO] |  +- com.github.waffle:waffle-jna:jar:1.9.1:runtime
[INFO] |  |  +- net.java.dev.jna:jna:jar:4.5.1:runtime
[INFO] |  |  +- net.java.dev.jna:jna-platform:jar:4.5.1:runtime
[INFO] |  |  \- org.slf4j:jcl-over-slf4j:jar:1.7.30:runtime
[INFO] |  +- org.osgi:org.osgi.core:jar:4.3.1:runtime
[INFO] |  \- org.osgi:org.osgi.enterprise:jar:4.2.0:runtime
[INFO] +- org.apache.cxf:cxf-rt-rs-extension-providers:jar:3.3.6:compile
[INFO] |  +- org.apache.cxf:cxf-core:jar:3.3.6:compile
[INFO] |  |  +- org.glassfish.jaxb:jaxb-runtime:jar:2.3.3:compile
[INFO] |  |  |  +- org.glassfish.jaxb:txw2:jar:2.3.3:compile
[INFO] |  |  |  \- com.sun.istack:istack-commons-runtime:jar:3.0.11:compile
[INFO] |  |  +- com.fasterxml.woodstox:woodstox-core:jar:5.0.3:compile
[INFO] |  |  +- org.apache.ws.xmlschema:xmlschema-core:jar:2.2.5:compile
[INFO] |  |  \- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
[INFO] |  |     \- jakarta.activation:jakarta.activation-api:jar:1.2.2:compile
[INFO] |  +- org.apache.cxf:cxf-rt-frontend-jaxrs:jar:3.3.6:compile
[INFO] |  |  +- jakarta.ws.rs:jakarta.ws.rs-api:jar:2.1.6:compile
[INFO] |  |  +- org.apache.cxf:cxf-rt-transports-http:jar:3.3.6:compile
[INFO] |  |  \- org.apache.cxf:cxf-rt-security:jar:3.3.6:compile
[INFO] |  +- javax.annotation:javax.annotation-api:jar:1.3:compile
[INFO] |  +- javax.xml.ws:jaxws-api:jar:2.3.1:compile
[INFO] |  |  \- javax.xml.soap:javax.xml.soap-api:jar:1.4.0:compile
[INFO] |  +- com.sun.activation:javax.activation:jar:1.2.0:compile
[INFO] |  +- org.apache.geronimo.specs:geronimo-ws-metadata_2.0_spec:jar:1.1.3:compile
[INFO] |  +- com.sun.xml.messaging.saaj:saaj-impl:jar:1.5.2:compile
[INFO] |  |  +- jakarta.xml.soap:jakarta.xml.soap-api:jar:1.4.2:compile
[INFO] |  |  +- org.jvnet.staxex:stax-ex:jar:1.8.3:compile
[INFO] |  |  \- com.sun.activation:jakarta.activation:jar:1.2.2:runtime
[INFO] |  +- org.jacorb:jacorb-omgapi:jar:3.9:compile
[INFO] |  +- org.apache.geronimo.specs:geronimo-jta_1.1_spec:jar:1.1.1:compile
[INFO] |  \- org.jboss.spec.javax.rmi:jboss-rmi-api_1.0_spec:jar:1.0.6.Final:compile
[INFO] +- org.codehaus.woodstox:woodstox-core-asl:jar:4.2.0:compile
[INFO] +- org.codehaus.woodstox:stax2-api:jar:3.1.4:compile
[INFO] +- org.codehaus.jettison:jettison:jar:1.4.0:compile
[INFO] +- com.sap.hcp.cf.logging:cf-java-logging-support-log4j2:jar:2.1.4:compile
[INFO] |  \- com.sap.hcp.cf.logging:cf-java-logging-support-core:jar:2.1.4:compile
[INFO] |     +- com.fasterxml.jackson.jr:jackson-jr-objects:jar:2.9.10:compile
[INFO] |     \- org.apache.commons:commons-lang3:jar:3.9:compile
[INFO] +- com.sap.hcp.cf.logging:cf-java-logging-support-servlet:jar:2.1.4:compile
[INFO] |  \- com.auth0:java-jwt:jar:3.3.0:compile
[INFO] +- org.apache.logging.log4j:log4j-slf4j-impl:jar:2.8.2:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] |  \- org.apache.logging.log4j:log4j-api:jar:2.13.3:compile
[INFO] +- org.apache.logging.log4j:log4j-core:jar:2.8.2:compile
[INFO] +- com.sap.xs.auditlog:audit-java-client-api:jar:2.0.16:provided
[INFO] +- com.sap.xs.auditlog:audit-java-client-impl:jar:2.0.16:compile
[INFO] |  +- com.sap.xs.auditlog:auditlog-common:jar:2.0.41:compile
[INFO] |  +- com.sap.xs.java:xs-user-holder:jar:1.8.3:compile
[INFO] |  |  \- com.sap.xs2.security:java-container-security-api:jar:0.33.18:compile
[INFO] |  |     \- com.sap.cloud.security.xssec:api:jar:1.0.2:compile
[INFO] |  \- org.apache.httpcomponents:httpclient:jar:4.5.7:compile
[INFO] |     +- org.apache.httpcomponents:httpcore:jar:4.4.11:compile
[INFO] |     \- commons-logging:commons-logging:jar:1.2:compile
[INFO] +- com.sap.xs.java:xs-env:jar:1.8.5:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.10.6:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.10:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.9.10:compile
[INFO] +- junit:junit:jar:4.11:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:2.2:test
[INFO] |     \- org.hamcrest:hamcrest:jar:2.2:test
[INFO] +- org.mockito:mockito-all:jar:1.10.19:test
[INFO] +- org.powermock:powermock-module-junit4:jar:1.6.4:test
[INFO] |  \- org.powermock:powermock-module-junit4-common:jar:1.6.4:test
[INFO] |     +- org.powermock:powermock-core:jar:1.6.4:test
[INFO] |     |  \- org.javassist:javassist:jar:3.25.0-GA:test
[INFO] |     \- org.powermock:powermock-reflect:jar:1.6.4:test
[INFO] +- org.powermock:powermock-api-mockito:jar:1.6.4:test
[INFO] |  +- org.mockito:mockito-core:jar:3.3.3:test
[INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.10.14:test
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.10.14:test
[INFO] |  |  \- org.objenesis:objenesis:jar:2.6:test
[INFO] |  \- org.powermock:powermock-api-support:jar:1.6.4:test
[INFO] +- com.github.stefanbirkner:system-rules:jar:1.17.1:test
[INFO] +- org.eclipse.jetty:jetty-server:jar:9.2.7.v20150116:test
[INFO] |  +- org.eclipse.jetty:jetty-http:jar:9.4.31.v20200723:test
[INFO] |  |  \- org.eclipse.jetty:jetty-util:jar:9.4.31.v20200723:test
[INFO] |  \- org.eclipse.jetty:jetty-io:jar:9.4.31.v20200723:test
[INFO] +- org.eclipse.jetty:jetty-servlet:jar:9.2.13.v20150730:test
[INFO] |  \- org.eclipse.jetty:jetty-security:jar:9.4.31.v20200723:test
[INFO] \- org.json:json:jar:20190722:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

**Comment by liga-oz** [comment]
Hi @KaminiSingh,

as you are using SAP Java Buildpack can you confirm that you have done all steps provided in the following guide: https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/java-security/Migration_SAPJavaBuildpackProjects.md 

Thanks,
Liga Ozolina

**Comment by KaminiSingh** [comment]
Hi @liga-oz 
All the steps in the guide is followed except that i have added one additional dependency of 

               <dependency>
  			<groupId>com.sap.cloud.security</groupId>
  			<artifactId>java-security</artifactId> 
  			<scope>provided</scope>	 		
 		</dependency>

I hope that should not cause any issue ...

**Comment by KaminiSingh** [comment]
Hi @liga-oz 

Also I would like to clarify that do I not need to remove below dependencies if I am using SAP java Build Pack

                      <dependency>
				<groupId>com.sap.cloud.security.xsuaa</groupId>
				<artifactId>token-client</artifactId>
				<version>${xsuaa.token.client}</version>
			</dependency>

			<dependency>
				<groupId>com.sap.cloud.security.xsuaa</groupId>
				<artifactId>java-container-security</artifactId>
				<version>${java.security.version}</version>
				<exclusions>
				    <exclusion>
				      <groupId>com.unboundid.components</groupId>
				      <artifactId>json</artifactId>
				    </exclusion>
				  </exclusions>
			</dependency>

		<dependency>
			<groupId>com.sap.cloud.security.xsuaa</groupId>
			<artifactId>token-client</artifactId>
		</dependency>

		<dependency>
			<groupId>com.sap.cloud.security.xsuaa</groupId>
			<artifactId>java-container-security</artifactId>
			<exclusions>
				<exclusion>
					<groupId>com.fasterxml.jackson.core</groupId>
					<artifactId>jackson-databind</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.springframework.security</groupId>
					<artifactId>spring-security-core</artifactId>
				</exclusion>
				<exclusion>
                    <groupId>com.unboundid.components</groupId>
                    <artifactId>json</artifactId>
                 </exclusion>
			</exclusions>
		</dependency>

If not then I do not have any  below dependencies 

groupId (deprecated) | artifactId (deprecated)
-- | --
com.sap.xs2.security | java-container-security-api
com.sap.cloud.security.xssec | api
com.sap.cloud.security.xsuaa | java-container-security-api


Then what are the changes needs to be done in my pom.xml to use new security library for my project .. I am attaching my pom.xml for your reference ..

**Comment by KaminiSingh** [comment]
[pom.txt](https://github.com/SAP/cloud-security-xsuaa-integration/files/5415138/pom.txt)

**Comment by KaminiSingh** [comment]
Hi @liga-oz Also I am attaching the changed pom.xml according to the migration guide for your reference ...
[pom.txt](https://github.com/SAP/cloud-security-xsuaa-integration/files/5415278/pom.txt)

**Comment by liga-oz** [comment]
Hi @KaminiSingh ,

From the dependency tree you provided, there is SLF4J implementation provided at compile time, which would clash with the SLF4J implementation provided by the SAP Java Buildpack.
<img width="460" alt="Screenshot 2020-10-26 at 13 36 43" src="https://user-images.githubusercontent.com/72249435/97173578-15e5a380-1791-11eb-8d7c-a5c179ea7ffb.png">
 https://github.com/SAP/cloud-security-xsuaa-integration/blob/a72660c910a7aa5a7eea9e5ca86d2110b5d47533/java-security/README.md#logging 

Regarding your question which dependencies you can remove when you are using SAP Java buildpack:

- java-container-security -> depends what modules you are using
- token-client lib -> is part of SAP Java buildpack

You can also take advantage of BOM to manage SAP Java buildpack dependencies.
More info: https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/6c6936e8e4ea40c9a9a69f6783b1e978.html
Note: group-id in the above document is missing "cf" at the end in group id, it should be `<groupId>com.sap.cloud.sjb.cf</groupId>`
