### ISSUE TITLE
xsuaa migration api Principal.getName response change

### ISSUE THREAD

**Issue by kamakumar** [SAP/cloud-security-xsuaa-integration#399]
Hi,

We're trying to upgrade our project using the xsuaa migration guide.
https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/spring-xsuaa/Migration_JavaContainerSecurityProjects.md

After upgrading, we found that the Principal.getName api now returns "user/ldap/kamal.kumar04@sap.com" in Cloud Foundry.
The prefix "user/ldap" or "client/" is added and since we are using this api for user authorization, it creates a problem.

Is there a way to prevent this from happening ?

Regards,
Kamal

**Comment by nenaraab** [comment]
Hi @kamakumar ,

You may like to get the name like it it is done here (from USER_NAME claim):

https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/java-security/src/main/java/com/sap/cloud/security/adapter/xs/XSUserInfoAdapter.java#L89

Does this help?
I will update the documentation accordingly...

Best regards,
Nena

**Comment by nenaraab** [comment]
Your use-case isn't documented anywhere and might not be supported in the near future as it uses classes from the deprecated Spring OAuth2 lib.

```java
    @GetMapping("/v2/sayHello")
    public String sayHello(@AuthenticationPrincipal Principal principal) {

        principal.getName(); // returns token.getUserName() @see AuthenticationToken
    }
```

References:
- https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Migration-Guide
- https://stackoverflow.com/questions/59273338/what-is-the-replacement-for-the-deprecated-authorizationserver-in-spring-securit
- https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/OAuth2AuthenticationConverter.java
- https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/AuthenticationToken.java
