### ISSUE TITLE
Add generic module for non-spring projects

### ISSUE THREAD

**Issue by sawoz** [SAP/cloud-security-xsuaa-integration#40]
Hi!

Would it be possible to add an additional, more generic module for non-Spring projects which is then referenced by the xsuaa-spring module?

I could imagine that this could contain a slight abstraction of common concepts such as JWT to avoid coupling to Spring in these places.

What do you think?

Thanks!
Sander

**Comment by mwdb** [comment]
Hi Sander,

I see these use cases:
1) Java application using container based authentication. These are addressed with the SAP Java build pack and use the api in the api directory.
2) Node.js application: They get the validation libraries from npm.sap.com
3) Spring applications. Covered with this project.

Most of the validation logic is already included in spring-security 5. I'd don't want to add another validation library.

**Comment by tuxedo0801** [comment]
Tomcat with SpringBoot is not good solution when trying to create microservices. Javalin or Sparkjava with an underlying jetty seem to be "perfect" (at least for what we try).

Problem is: It seems that there is now way to use this, as there is no matching xsuaa library (or at least one that can be easily adapted). :-(

**Comment by mwdb** [comment]
Hi,
You can take a look at the libraries provided by "XS Java 1" on SAP Service Market Place. This contains a class with the constructor below. It validates a token against the xsuaa service binding. It has some spring dependencies, but does not require spring or Tomcat.
 
public UserInfoTomcat(String tokenValue) throws UserInfoException

Regards,

Martijn

**Comment by strehle** [comment]
hi,
we will provide this small java only library, the library in XS JAVA 1 is depedent on spring4 and because of EOL of spring4 will will provide a library without spring deps.

regards,

**Comment by nenaraab** [comment]
Hi @sawoz,

would this ["token-client"](#124) library for token exchange be sth, you would like to leverage?
It's planned for the next release (1.7), so feel free to provide your feedback.

**Comment by nenaraab** [comment]
Initial version of token-client lib is released. It is designed in such a way, that we can support further Rest clients such as Apache HTTP client in the future if requested. In this case no dependency to a Spring library is required.
