### ISSUE TITLE
Scope issue

### ISSUE THREAD

**Issue by sundarvc** [SAP/cloud-security-xsuaa-integration#402]
HI all,

I am running the xsuaa-usage example and see the following error in the logs:

'User not authorized, source of route: /^\\/to-spring-app\\/(.*)/, IP: ******, required scopes: ssc-xsuaa!t15778.ssc.display,ssc-xsuaa!t15778.ssc.admin, user scopes: openid,uaa.user',

Does this mean the scope is not getting propagated to the spring app ? I did add the appropriate user to the role collection, but I get 403 error with the above message.

Thanks,
Sundar

**Comment by nenaraab** [comment]
hi @sundarvc 

yes.

pls check the decoded token... (set a break point in TokenBrokerResolver)

If it does not contain the respective scope, the rolecollection that provides the scope has to be assigned to the user that does the request.  Furthermore you may have to clean the browser cache and provoke another login.

Best regards,
Nena
