### ISSUE TITLE
[spring-xsuaa] Cleanup dependencies to deprecated Spring Security OAuth

### ISSUE THREAD

**Issue by nenaraab** [SAP/cloud-security-xsuaa-integration#403]
With the implementation in these two classes 
- https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/OAuth2AuthenticationConverter.java
- https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/AuthenticationToken.java
we have dependecies to Spring Security OAuth2 which is already deprecated. We have to check whether we can setup a principal differently, maybe as described here in the [baeldung tutorial](https://www.baeldung.com/spring-security-oauth-principal-authorities-extractor)

References:
- https://www.baeldung.com/spring-security-oauth-principal-authorities-extractor
- https://github.com/SAP/cloud-security-xsuaa-integration/issues/399
- https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Migration-Guide

**Comment by nenaraab** [comment]
Hi @pianocktail,

can you please create a JIRA Ticket for that, this has to be solved soon.

Best regards,
Nena

**Comment by pianocktail** [comment]
[SECAUTH-1125](https://jtrack.wdf.sap.corp/browse/SECAUTH-1125) created
