### ISSUE TITLE
JWT verification failed: Cannot verify with online token key, uaadomain is null

### ISSUE THREAD

**Issue by VandanaHA** [SAP/cloud-security-xsuaa-integration#406]
Hi,

I'm using org.springframework.security.oauth2.jwt.JwtDecoder in my spring application to decode JWT token. 

XsuaaServiceConfiguration xsc = (xsuaaServiceConfiguration == null) ? new XsuaaServiceConfigurationDefault() : xsuaaServiceConfiguration;
jwtDecoder = new XsuaaJwtDecoderBuilder(xsc).build();
XsuaaToken xsuaaToken = (XsuaaToken) jwtDecoder.decode(tokenValue);

I get the following error while decoding the JWT:
"org.springframework.security.oauth2.jwt.JwtException: JWT verification failed: Cannot verify with online token key, **uaadomain is null**"

I have attached my pom.xml file.
[pom.txt](https://github.com/SAP/cloud-security-xsuaa-integration/files/5456451/pom.txt)

Can you please let me know how to resolve this?

Regards,
Vandana

**Comment by nenaraab** [comment]
Hi @VandanaHA (cc @liga-oz)

please tell us more about the setup, which plan do you make us e of?

Best regards,
Nena

**Comment by VandanaHA** [comment]
Hi Nena,

I use Application plan for my xsuaa instance.

Regards,
Vandana

**Comment by liga-oz** [comment]
Hi @VandanaHA,

could you please provide safely your VCAP_SERVICES output?

Is there a specific reason why you're checking xsuaaServiceConfiguration is not null?

Perhaps, you could take advantage of Spring Autoconfiguration capabilities that would also auto configure the Jwt decoder for you, as described here:  https://github.com/SAP/cloud-security-xsuaa-integration/blob/a72660c910a7aa5a7eea9e5ca86d2110b5d47533/spring-xsuaa/README.md#auto-configuration

Best Regards,
Liga Ozolina

**Comment by liga-oz** [comment]
Hi @VandanaHA ,

as discussed, providing you some samples of xsuaaSecurityConfiguration usage:

- Using Autowiring capabilities to configure Xsuaa service:
https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/samples/spring-security-xsuaa-usage/src/main/java/sample/spring/xsuaa/SecurityConfiguration.java#L38 
- As you mentioned you're migrating your project, referencing here migration guide and how to access VCAP_SERVICES:
https://github.com/SAP/cloud-security-xsuaa-integration/blob/fcd59c6f710f867f5b617d0b128da2750f7c1b87/spring-xsuaa/Migration_JavaContainerSecurityProjects.md#access-vcap_services-values
- Code snippet of custom Xsuaa Service configuration implementation `XsuaaServiceConfigurationCustom`

```
import com.sap.cloud.security.xsuaa.XsuaaCredentials;
import com.sap.cloud.security.xsuaa.XsuaaServiceConfigurationCustom;

@Bean
@ConfigurationProperties("vcap.services.<<name of your xsuaa instance of plan application>>.credentials")
public XsuaaCredentials xsuaaCredentials() {
    return new XsuaaCredentials(); // primary Xsuaa service binding, e.g. application
}

@Bean
public XsuaaServiceConfiguration customXsuaaConfig() {
    return new XsuaaServiceConfigurationCustom(xsuaaCredentials());
}
```

Kind Regards,
Liga

**Comment by liga-oz** [comment]
Hi @VandanaHA,
I will close this issue, please reopen, if the issue is still relevant.

Thanks,
Liga Ozolina
