### ISSUE TITLE
Log entries about subdomain being not replaces

### ISSUE THREAD

**Issue by brunohaller** [SAP/cloud-security-xsuaa-integration#407]
Hi,

we are getting a lots of logs stating that:

The subdomain of the URI 'https://***' is not replaced by subdomain 'null'

from here
https://github.com/SAP/cloud-security-xsuaa-integration/blob/0790e24af3540673ce39495ef3e93c821a4773af/token-client/src/main/java/com/sap/cloud/security/xsuaa/util/UriUtil.java#L44

This information is not helpful, because I never want to replace the subdomain for that case.. Can that log be avoided, if no subdomain was set at all?

Best Regards,
Bruno

**Comment by nenaraab** [comment]
Hi @brunohaller I've set the log level to debug :-) thanks for reporting.
