### ISSUE TITLE
Dependency conflict with SAP CloudSDK for java

### ISSUE THREAD

**Issue by dannykruitbosch** [SAP/cloud-security-xsuaa-integration#413]
We're trying to use SAP SpringBoot Starter XSUAA 2.7.8 together with the SAP CloudSDK for Java 3.32.0.

The CloudSDK depends on part of the xsuaa (java-api, java-security, tokenclient, java-security-test) version 2.7.8, but does not use spring-xsuaa. The CloudSDK also depends on Spring Security 5.4.1.
When we add xsuaa-spring-boot-starter, our security integration tests break, and it seems to be due to the fact that xsuaa-spring-boot-starter depends on Spring Security 5.3.4.RELEASE.

We get errors saying: `java.lang.NoSuchMethodError: 'java.util.Map com.nimbusds.jose.Header.toJSONObject()`

We've not been able to resolve this issue. Can this be the cause of different dependencies? If so, any ideas on how to resolve these?

Thanks,

Danny

**Comment by liga-oz** [comment]
Hi @dannykruitbosch,

the dependency that is used in cloud-security-xsuaa-integration library is Spring Boot Dependencies » 2.3.4.RELEASE that contains transient dependency of Spring Security OAuth2 JOSE » 5.3.4.RELEASE. 
Even the latest version of Spring Boot Dependencies library 2.3.5.RELEASE  is using only Spring Security OAuth2 JOSE » 5.3.5.RELEASE. 

In your case, perhaps, if the higher version of Spring Security OAuth2 JOSE library is not required by your project, you could try to provide this dependency explicitly in your pom like this: 

`<dependency>`
`<groupId>org.springframework.security</groupId>`
          `<artifactId>spring-security-oauth2-jose</artifactId>`
        `<version>5.3.4.RELEASE</version>`
`</dependency>`

Kind Regards,
Liga Ozolina

**Comment by MatKuhr** [comment]
Just putting this here for other people to see: https://stackoverflow.com/questions/64764311/dependency-conflicts-between-sap-cloud-sdk-and-sap-cloud-security-xsuaa-integrat

**Comment by liga-oz** [comment]
Closing the issue. If you require further assistance please reopen again.
