### ISSUE TITLE
Are SCP CF Websocket endpoints secured? How can we enable security for Websocket endpoints?

### ISSUE THREAD

**Issue by githubsree** [SAP/cloud-security-xsuaa-integration#425]
Hi Colleagues,

We want to expose websocket enpoint to clients for big file uploads. Do XSUAA support security on websocket endpoints in SCP CF?

If yes,

1. is it recommended to expose websocket for secure communication?

2. How can we secure websocket endpoint securely? Do you have any examples, links, suggestions?

Thank You

Regards

Sreeram

**Comment by nenaraab** [comment]
Hi @githubsree,

- your communication should be secured via SSL.
- before you open the connection you should perform a check on whether the user is authenticated and authorized to upload the file. This can be done with bearer tokens (Authorization header)...
  - for that you can use [java-security](https://github.com/SAP/cloud-security-xsuaa-integration/tree/master/java-security) client lib for example. 
- and last but not least you should invest in resiliency, i.e. rate limitation, elasticity (auto-scaling) and check of payload size...

Let's see whether someone replies to your question on SAP Jam community and provides other ideas...

Best regards,
Nena
