### ISSUE TITLE
[spring-xsuaa] Declare missing dependency to Nimbus

### ISSUE THREAD

**Issue by newtork** [SAP/cloud-security-xsuaa-integration#426]
Related issue:
https://github.com/SAP/cloud-security-xsuaa-integration/issues/414

Please add the dependency to Nimbus (`compile`) into your `spring-xsuaa` POM.
This will make future debugging easier. Also enables tool-assisted dependency checks, e.g. `maven-enforcer-plugin`.

**Comment by liga-oz** [comment]
Hi @newtork,

the issue #414 has been meanwhile fixed and you can use the latest Spring libraries without having incompatibility issues with the Nimbus major version <=9 I would hesitate adding explicit Nimbus dependency in our POM as we are transitioning away of using this dependency in future and we would then need to maintain this version even though it comes as transient dependency with Spring projects and Nimbus version is maintained by Spring developers.

Kind Regards,
Liga
