### ISSUE TITLE
Incorrect scope for javax.servlet-api dependency in java-api

### ISSUE THREAD

**Issue by vtintillier** [SAP/cloud-security-xsuaa-integration#427]
`javax.servlet-api` dependency should always use `provided` scope, as those classes are provided by the Servlet container like Tomcat.

In `java-api` we have a `compile` scope dependency: https://github.com/SAP/cloud-security-xsuaa-integration/blob/d7faf413da7628eb91c6c60ba392f9b33c0eb90d/java-api/pom.xml#L29

**Comment by nenaraab** [comment]
Hi @vtintillier 

oh yes, that's probably a good idea. We set it for `spring-xsuaa` as provided and SAP Java Buidlpack provides it as well.

Best regards,
Nena

**Comment by nenaraab** [comment]
Hey @liga-oz 

please check all dependencies to `javax.servlet-api`, whether it can be set to provided or test.

Thanks,
Nena

**Comment by nenaraab** [comment]
Yeah, but I though, it can be removed from the samples as well?

**Comment by nenaraab** [comment]
Thanks a lot for reporting AND contributing the fix! Enjoy your weekend!

**Comment by vtintillier** [comment]
Thanks @nenaraab . Do you want me to look at samples too?

**Comment by liga-oz** [comment]
Hi @nenaraab,

checked and verified with IT for scope change of servlet-api to provided. PR #444

BR,
Liga
