### ISSUE TITLE
Suggestion: Use dependency-plugin to ensure dependency convergence

### ISSUE THREAD

**Issue by sawoz** [SAP/cloud-security-xsuaa-integration#43]
Hi!

we have made good experience with using the Maven dependency plugin to ensure converging dependency versions and avoid conflicts in our projects.

What is your take on this? I think consumers would greatly benefit from this.
I could offer to create a PR to showcase this a bit.

Kind regards
Sander

**Comment by nenaraab** [comment]
hi, we've cleaned up our pom.xml's and converged all depdendencies in the dependency management section of our parent pom
