### ISSUE TITLE
Missing POM dependency for java-api in spring-xsuaa/pom.xml

### ISSUE THREAD

**Issue by stevschm** [SAP/cloud-security-xsuaa-integration#430]
Hi colleagues,
in spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/XsuaaToken.java you import com.sap.cloud.security.token.InvalidTokenException;

Therefore, there should be a dependency in your spring-xsuaa/pom.xml for the java-api artifactID.

**Comment by nenaraab** [comment]
Hi @stevschm 

thanks for reporting that.

Best regards,
Nena

**Comment by liga-oz** [comment]
Hi @stevschm,
the exception class `com.sap.cloud.security.token.InvalidTokenException` has been replaced by `org.springframework.security.oauth2.server.resource.InvalidBearerTokenException`, if you do not use token exchange functionality, you shouldn't need java-api dependency at all. The changes will be available in the next release of 2.8.1 version.

Best Regards,
Liga
