### ISSUE TITLE
Evaluate Formatters

### ISSUE THREAD

**Issue by nenaraab** [SAP/cloud-security-xsuaa-integration#44]
Evaluate on how to avoid merge issues and how to avoid unreadable code changes because of different code styles and different ordering of imports.

### Option 1
#42 PR uses [Maven `code.revelc.net-formatter` plugin](https://code.revelc.net/formatter-maven-plugin/usage.html) and [Maven `code.revelc.net-impSort` plugin](https://code.revelc.net/impsort-maven-plugin/index.html)

### Option 2
use eclipseFormatter as given [here](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/etc/eclipse_settings.xml) and introduce checkstyle as described [here](#36)

**Comment by sawoz** [comment]
Some additional input: you can also use the Maven formatter in option 1 with the eclipse formatter XML:

```xml
<configuration>
    <configFile>...</configFile>
    <encoding>${project.build.sourceEncoding}</encoding>
    <directories>
        <directory>${project.basedir}/src/main/java</directory>
        <directory>${project.basedir}/src/test/java</directory>
    </directories>
    ...
</configuration>
```

**Comment by nenaraab** [comment]
> Some additional input: you can also use the Maven formatter in option 1 along with the eclipse formatter XML of option 2:
> 
> ```
> <configuration>
>     <configFile>${path.to.my.formatter.xml.file}</configFile>
>     <encoding>${project.build.sourceEncoding}</encoding>
>     <directories>
>         <directory>${project.basedir}/src/main/java</directory>
>         <directory>${project.basedir}/src/test/java</directory>
>     </directories>
>     ...
> </configuration>
> ```

@sawoz cool, great - tried it out in my PR #52 - works as defined... Thanks a lot!
