### ISSUE TITLE
Add getSubAccountId() to AccessToken interface

### ISSUE THREAD

**Issue by mtolksdorf** [SAP/cloud-security-xsuaa-integration#452]
For scenarios requiring the subaccountId to work properly (e.g. OnPremise Connectivty), there is an API getSubAccountId()  in the implementation class XsuaaToken. However, it is not part of the API of the interface AccessToken and if an application likes to stick to the interface so that it does not need to rely on and cast to the implementation, this is currently not possible. 
Proposal add the API and if there is no subaccountId available in the token simply return null or empty String

**Comment by nenaraab** [comment]
Hi @mtolksdorf thanks for the feature reqquest,

we will prove once more and will provide you a fix as soon as possible.

Best regards,
Nena

**Comment by nenaraab** [comment]
available with version 2.8.3
