### ISSUE TITLE
Regarding token exchange for AppToService calls

### ISSUE THREAD

**Issue by skadali** [SAP/cloud-security-xsuaa-integration#459]
Hello, 
I have a requirement to calls AppToService calls.

After I get the jwt token for the XSUAA (SaaS tenant App), I need to token exchange with reuse-service SDM credentials (another client id and secret).

When I talked to the SDM integration colleagues, they have asked me to token exchange the SaaS tenant jwt token with sdm's client id and secret: like below:

Subscription account -> communicate app uaa (jwt token ) - > take the token and exchange with SDM jaa (client id and client secret) -> generate a new jwt which has your client information which is understandable by SDM.

I tried to follow the token-client documentation as follows:
```java
try {
            XsuaaTokenFlows tokenFlows = new XsuaaTokenFlows(new DefaultOAuth2TokenService(),
              new XsuaaDefaultEndpoints(EnvironmentUtil.getSdmUaaUrl()), 
              new ClientCredentials(EnvironmentUtil.getSdmUaaClientId(), EnvironmentUtil.getSdmUaaClientSecret()));
            
              Token token = SecurityContext.getToken();   // token with SaaS tenant application
              // XsuaaToken token = (XsuaaToken) token;           
              if (token != null) {
                OAuth2TokenResponse userToken = tokenFlows.userTokenFlow()
                                                .token(token.getTokenValue())    // token value for the tenant app
                                                //.subdomain(token.getSubdomain())    
                                                .execute();
                access_token = userToken.getAccessToken();
              } else {
                OAuth2TokenResponse tokenResponse = tokenFlows.clientCredentialsTokenFlow().execute();
                access_token = tokenResponse.getAccessToken();
              }
        } catch(Exception e) {
            log.error("Exception found when getting access token.", e);
        } 
```

But I got the unauthorized error while trying to get OAuth2TokenResponse object. 
{\"error\":\"unauthorized\",\"error_description\":\"Unable to map issuer, [http://subdomain.localhost:8080/uaa/oauth/token] , to a single registered provider\"}

The below code is deprecated https://jam4.sapjam.com/blogs/show/2dxT4cVGxTXZRJT0D1DQQM: 
```java
XSTokenRequest tokenRequest = new XSTokenRequestImpl(<uaa base url>)
  .setType(XSTokenRequest.TYPE_USER_TOKEN) // or XSTokenRequest.TYPE_CLIENT_CREDENTIALS_TOKEN
  .setClientId(<client id>)
  .setClientSecret(<client secret>);
String token = SecurityContext.getUserInfo().requestToken(tokenRequest);
```
How to switch this App's xsuaa token to use the sdm's client id/secret programmatically so that I could use that jwt token to do sdm's api calls?
I tried to look into the examples, but as mentioned in above example, I got an unauthorized error. And Sdm colleagues say that they have Api's in Node.js where App's jwt is switched to use another services e.g. SDM's Client id/secret.
```java
var serviceCredentials = { "clientid" = "<client id>", "clientsecret" = "<client secret>", "url" = "<uaa base url>" }
req.authInfo.requestToken(serviceCredentials, constants.TYPE_USER_TOKEN, null, callback);
// or constants.TYPE_CLIENT_CREDENTIALS_TOKEN
```
Could you please help?

Regards,
Sri

**Comment by nenaraab** [comment]
Hi @skadali 

thank you for your request, can you please specify the subdomain in the token exchange as well?

Thanks and best regards,
Nena

- NGPBUG-122370

**Comment by skadali** [comment]
Hi @nenaraab,
Yes I tried with subdomain as well. I got the same error.
Error requesting token with grant_type 'urn:ietf:params:oauth:grant-type:jwt-bearer': Error retrieving JWT token. Server URI https://sapcai-dev-pal.authentication.eu10.hana.ondemand.com/oauth/token. Status code 401. Response body {"error":"unauthorized","error_description":"Unable to map issuer, https://copilot-tenant.authentication.eu10.hana.ondemand.com/oauth/token , to a single registered provider"

The sdm credientials are from the Provider account with url https://sapcai-dev-pal.authentication.eu10.hana.ondemand.com and client id and secret from the VCAP_SERVICES for the Provider service.
And the SaaS tenant token subdomain is  copilot-tenant so url would be https://copilot-tenant.authentication.eu10.hana.ondemand.com. 

From this example:
https://jam4.sapjam.com/blogs/show/2dxT4cVGxTXZRJT0D1DQQM
Subscription account -> communicate app uaa (jwt token ) - > take the token and exchange with SDM jaa (client id and client secret) -> generate a new jwt which has your client information which is understandable by SDM
Is the SDM Uaaurl, Client id and secret same as in the Provider instance binding instance from the VCAP_SERVICES. i.e. is it same for even the tenant application ?
Calling the Application from a SAAS Tenant
If you want to call the application depicted in the figure (that uses the reuse-service) from a SAAS tenant, you require the following subscriptions within this SAAS tenant:
·         Subscription to the application
·         Subscription to the clone of the reuse-service (that exists in the same org as the application)
       what does it mean. We have the binding created in our provider service. and the Tenant application is subscribed to the Provider service. (Cloud foundry is not enabled for our subscription tenant.)

Regards,
Sri

**Comment by nenaraab** [comment]
Hi @skadali 

the error is raised by the xsuaa (server side). And unfortunately, I'm not that familiar with your use case, so my suggestion would be to either file a NGPBUG ticket (xsuaa component) or to ask you question in our JAM forum.

Best regards,
Nena
