### ISSUE TITLE
Can't mock XsuaaToken with Mockito anymore // Outdated test documentation

### ISSUE THREAD

**Issue by LukasHeimann** [SAP/cloud-security-xsuaa-integration#466]
Hi everyone,

In our tests, we previously used Mockito to mock an `XsuaaToken`:

```java
XsuaaToken token = mock(XsuaaToken.class);
when(token.getScopes()).thenReturn(Arrays.asList("scope1", "scope2"));
```

Apart from `getScopes()`, we also mock `getSubject()`, `getSubaccountId()` and `getIssuedAt()` in other tests.

We recently tried to update to a more recent version of the library (2.8.0, which is bundled in a popular internal BOM) and experienced failures in our tests:

```
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class com.sap.cloud.security.xsuaa.token.XsuaaToken.
Mockito can only mock non-private & non-final classes.
```

I started to look into the test documentation to find other ways to get a mocked token for our use case and found the `JwtGenerator`, which seemed straight forward: https://github.com/SAP/cloud-security-xsuaa-integration/tree/master/java-security-test#jwt-generator

```java
XsuaaToken token = (XsuaaToken) JwtGenerator.getInstance(Service.XSUAA).withScopes("scope1", "scope2").createToken();
```

However, there were two issues:
- unlike described in the guide, the `getInstance` method needs an additional parameter for the clientId (which is fine, I can just give an arbitrary string)
- The documentation says: "By default its signed with a random RSA key pair". This seems to not be the case, as I now get `java.lang.IllegalStateException: Private key was not set!`. I'm unsure of what to use as minimal setup here.

How would you recommend us to handle this situation?

Thank you very much for your support!
Kind regards
Lukas

**Comment by nenaraab** [comment]
Hi @LukasHeimann 

- thanks a lot for the precise and valuable feedback!!! I've updated the documentation accordingly.
- The RSA key pair is set by default with java-security-test version `2.8.1`

Best regards,
Nena

**Comment by LukasHeimann** [comment]
Hi @nenaraab,

Thank you for your response and improving the documentation! Manually setting the version to 2.8.4 seems to even have solved the mockito issue, judging from our tests. As the central BOM seems to not regularly pick up updates from you, we'll handle the version manually now.

Kind regards
Lukas

**Comment by nenaraab** [comment]
Perfect - good to hear that 👍
