### ISSUE TITLE
Grant authorities in PaaS service communication

### ISSUE THREAD

**Issue by Tripti56** [SAP/cloud-security-xsuaa-integration#474]
Dear Team, 

We have a PaaS service offering (say A) bound to another reuse service (say B). B expects A to validate a `scope` and `grant-authority` to B to call A's endpoint. When we had bindings to both the app and broker plan of XSUAA, it was possible.  As now we have a completely PaaS offering, this has posed an issue. As I understand, granting authorities is not available in the broker plan of XSUAA. 
Please note, the above-mentioned scope authority is specific to B. 

I also came across this [post](https://jam4.sapjam.com/blogs/show/oEdyQO183plBoQdrvcPw2w?_lightbox=true ) which says `SAP_JWT_TRUST_ACL` is obsolete.

What should we do when the business application B wants to call an application A (with each application having its own CF XSUAA service instance)  ? (Since the XSUAA broker plan doesn't support grant authorities).

Best regards, 
Tripti

**Comment by nenaraab** [comment]
Hi @Tripti56 

maybe this explains better on what to do in order to get rid of `SAP_JWT_TRUST_ACL` 
https://github.com/SAP-samples/teched2020-DEV263/tree/main/exercises/ex5_sap_jwt_trust_acl ?

Kind regards,
Nena

**Comment by Tripti56** [comment]
hi @nenaraab, I came across following question on SAP Jam - [question](https://jam4.sapjam.com/questions/BRW7BcxIUmD1eJUg3ulJwI)

Could you please help me understand if ```grant-as-authority-to-apps``` is possible in ```broker``` plan of ```XSUAA```. 

Regards, 
Tripti

**Comment by Tripti56** [comment]
As I understand from the reply given, this option works only for onboarding and job scheduling. 
Please clarify if this is possible for other S2S communication.

**Comment by torsten-sap** [comment]
@Tripti56 Granting scopes from a "broker" plan instance to another XSUAA instance is only possible if both instances are part of the same subaccount. If not, then the call from A to B (and vice versa) needs to happen via a separate service instances of B (or A).

**Comment by nenaraab** [comment]
Hi @Tripti56 does this answer your question?

**Comment by Tripti56** [comment]
@nenaraab yes, it clarifies my question to some extent. Could you also suggest a workaround to make it work. As mentioned earlier, this requirement is relevant for our release.  I am working on a UML diagram to explain the scenario.  Will post once it is ready. 
I am looking for some recommendations for this to work.

**Comment by torsten-sap** [comment]
@Tripti56 If the calls go over subaccount borders the consumption needs to happen with service broker implementation, see the following documentation:
https://jam4.sapjam.com/blogs/show/2dxT4cVGxTXZRJT0D1DQQM

Apart from that I am not sure why a reuse-service B should expect from its callers that they validate certain scopes.

**Comment by Tripti56** [comment]
Well, it doesnt. I guess we need a call here.
