### ISSUE TITLE
Using reflection in code in order not to bring sprin security in the buildpack

### ISSUE THREAD

**Issue by vnb-dev** [SAP/cloud-security-xsuaa-integration#483]
Hi Colleagues,

We needed to remove the dependencies to spring security as this was a stopper for releasing our library to the buildpack.
The following PR was contributed to our team: https://github.wdf.sap.corp/audit-log-service/audit-java-client/pull/17 which unfortunately uses reflection. 

We would like to move this logic into the java security libraries and to clean up our code as using reflection is considered a bad practice in our team.

**Comment by nenaraab** [comment]
solved with https://github.com/SAP/cloud-security-xsuaa-integration/releases/tag/2.8.8 (already used in sap java buildpack)
