### ISSUE TITLE
JWT from another service being accepted

### ISSUE THREAD

**Issue by AchalKansal** [SAP/cloud-security-xsuaa-integration#497]
Hi Team,

We have two global accounts inn EU10

- Development
- Production

Development landscape is a different global account from Production landscape, where we have deployed our services and a tenant is subscribed to it and with those credentials, we are able to fetch the data from the Production landscape(which is a different Global account).

### Production Landscape :
- Broker plan:
   - "clientid": "sb-mdmbp-broker-production!b9541"
   - "xsappname": "mdmbp-broker-production!b9541"
- Application plan:
  - "clientid": "sb-mdmbp-app-production!t9541"
  - "xsappname": "mdmbp-app-production!t9541"

### Development Landscape: 
 - "clientid": "sb-bpservices-mdbpintgrtestconsumer11!b18441|mdmbp-broker-ms-provider-integration!b12186"
 - "xsappname": "bpservices-mdbpintgrtestconsumer11!b18441|mdmbp-broker-ms-provider-integration!b12186"
 - Token : Shared via mail already

**Comment by liga-oz** [comment]
Hi @AchalKansal,

this is duplicate https://jtrack.wdf.sap.corp/browse/NGPBUG-144882 
You are using deprecated library, solution as described in the NGP bug ticket is to migrate to [open source library ](https://github.com/SAP/cloud-security-xsuaa-integration), therefore closing this issue.

Kind Regards,
Liga
