### ISSUE TITLE
Retrieve token xs.user.attributes (custom) and scopes

### ISSUE THREAD

**Issue by silvia-giordano** [SAP/cloud-security-xsuaa-integration#500]
Hello colleagues,
we want to use Xsuaa authentication to access our UI / controller.
We created our custom template for the token that contains an attribute we need in our code, something like:

![image](https://user-images.githubusercontent.com/74785804/114054073-d074e880-988f-11eb-9ba9-878eaeea471a.png)

We use for the security configuration spring security / spring security oauth2 ([here ](https://github.wdf.sap.corp/CALMBuild/x-kafka-controller-srv/blob/master/srv/src/main/java/com/sap/calm/x/kafkacontroller/config/security/GeneralSecurityConfigurationAdapter.java)and [here ](https://github.wdf.sap.corp/CALMBuild/x-kafka-controller-srv/blob/master/srv/src/main/java/com/sap/calm/x/kafkacontroller/config/security/FormLoginSecurityConfiguration.java)the config classes)

At some point of the code in the security config, we want to manipulate the authorities to create custom roles based on the attribute from the token. How we can retrieve the information from the authorization token? Is it possible with this configuration?

Thanks in advance
BR

Silvia

**Comment by liga-oz** [comment]
Hi @silvia-giordano,

If I understood you correctly, your question is how to access xs.user.attribute value from decoded token. 
What cloud-security-xsuaa-integration modules you're using? 

`XsuaaToken` class offers out of the box method [getXSUserAttribute](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/spring-xsuaa/src/main/java/com/sap/cloud/security/xsuaa/token/XsuaaToken.java#L219) to do that. 

Here you can read up about some use cases of [spring-xsuaa](https://github.com/SAP/cloud-security-xsuaa-integration/tree/master/spring-xsuaa#usage) module.

Kind Regards,
Liga

**Comment by silvia-giordano** [comment]
Hello Liga, 
thank you for your quick answer.
We have dependency in our pom (inside the general parent pom):
com.sap.cloud.security.xsuaa:token-client:jar:2.8.3:compile
com.sap.cloud.security.xsuaa:api:jar:1.2.0:compile
com.sap.cloud.security.xsuaa:java-container-security-api:jar:2.16.4:provided
com.sap.cloud.security.xsuaa:api:jar:1.2.0:compile

But, in fact, we don't use the method provided from XSUAA directly. 
Are you able to see [this configuration class](https://github.wdf.sap.corp/CALMBuild/x-kafka-controller-srv/blob/master/srv/src/main/java/com/sap/calm/x/kafkacontroller/config/security/FormLoginSecurityConfiguration.java)?

In our configuration we have never the token available. So we thought: is it possible to retrieve the information in the token via a REST call at some point?

Thank you again

Kind Regards

Silvia

**Comment by liga-oz** [comment]
Hi @silvia-giordano ,

Firstly, I would highly recommend to upgrade the com.sap.cloud.security.xsuaa versions, latest one is 2.8.8 and migrate `java-container-security-api` as it is deprecated, you can find migration guides here: [java-security](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/java-security/Migration_SpringSecurityProjects.md). [spring-xsuaa](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/spring-xsuaa/Migration_JavaContainerSecurityProjects.md), I'm presuming you're not using SAPJavaBuildpack.

I can access your configuration class, but the question here is, if you're saying you do not have tokens in your application, how do you validate then incoming requests, how they are authenticated? Could you describe your application's authentication and authorization flow setup?

If you have encoded bearer token value, you can [create object ](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/java-security/README.md#create-a-token-object) of `Token` class, that would decode the token and you could then have access to various methods, see [here](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/spring-security/Migration_SpringXsuaaProjects.md#token-methods).

Best Regards,
Liga

**Comment by silvia-giordano** [comment]
Hello @liga-oz,
I think we found it how to do: we created a custom User Service in our configuration class, in this way we are able to do oauth2UserRequest.getAccessToken and retrieve finally everything from the token.
As you suggested, we will update com.sap.cloud.security.xsuaa versions as soon as possible.
Thank you anyway
BR

Silvia

**Comment by liga-oz** [comment]
Thanks @silvia-giordano for the update, closing this now. If you have any further questions please open a new issue.
