### ISSUE TITLE
Retrieve XsuaaAutoConfiguration from volumeMount

### ISSUE THREAD

**Issue by jalibu** [SAP/cloud-security-xsuaa-integration#513]
In Kyma environments there is no VCAP_SERVICES environment variable.
It would be great to have an option to parse the config from a volume mount (/etc/secrets/sapcp/xsuaa/my-binding)

**Comment by nenaraab** [comment]
Hi @jalibu thanks for your request!

as its not supported yet, i can only refer to this issue:
https://github.com/SAP/cloud-security-xsuaa-integration/issues/404

Kind regards,
Nena

**Comment by nenaraab** [comment]
The ticket is without any activity for 14 days or longer. 
Thus, closing the ticket.  @jalibu please reopen if the issue is still relevant.

**Comment by jalibu** [comment]
@nenaraab for sure it is still relevant

**Comment by zhjuncai** [comment]
is it support yet @nenaraab ?

**Comment by liga-oz** [comment]
@zhjuncai k8s is supprted starting from [2.11.0](https://github.com/SAP/cloud-security-xsuaa-integration/releases/tag/2.11.0) version
