### ISSUE TITLE
Multitenancy testing

### ISSUE THREAD

**Issue by Holdo** [SAP/cloud-security-xsuaa-integration#53]
### Problem
As a developer, I would like to be able to test multitenancy with JWTs from different identity zones (zid claim in the JWT which is semantically subaccount ID). This is useful for example in a test which is subscribing multiple tenants.

This scenario is currently not possible to test because:
- XSUAA mockserver performs offline validation only for one identity zone ("uaa")
- JwtGenerator does not support token generation with variable identityZones (hardcoded to "uaa")

In the past SAPOfflineTokenServices class supported this use-case because it did not check if the provided identity zone was trusted in case of the XSUAA application plan (when client_id contained !t).

**Comment by mwdb** [comment]
I'll look into this. One problem is certainly that the spring libraries require obtaining the token keys per HTTP, which in case of the uaa is <subdomain>.authentication.<landscape>.

On local systems, the URLs are not mapped (unless tweaking /etc/hosts). Some of the integration tests mitigate this by using localhost/<subdomain>/token_keys.

**Comment by Holdo** [comment]
Waiting for the next release...

**Comment by mwdb** [comment]
Done. Should be visible on maven central in about 2 hours

**Comment by mwdb** [comment]
Available on maven central as version 1.3.0
