### ISSUE TITLE
IAS Token Validation: Confirmation for JwtIssuerValidator

### ISSUE THREAD

**Issue by newtork** [SAP/cloud-security-xsuaa-integration#544]
For IAS token validation i have a `CombiningValidator` instance with the following validators:
 - JwtTimestampValidator ✔️ 
 - JwtIssuerValidator ❌ 
 - JwtSignatureValidator ❔ 
 - JwtAudienceValidator ❔ 

...coming from
```java
CFEnvironment environment;
OAuth2ServiceConfiguration configuration = environment.loadForServicePlan(Service.IAS, CFConstants.Plan.APPLICATION):
CombiningValidator validator = configuration.getJwtValidator();
```

My token looks like this:
```json
{
  "aud": [
    "...",
    "..."
  ],
  "sub": "...",
  "user_uuid": "...",
  "azp": "...",
  "iss": "ma.accounts400.ondemand.com",
  "zone_uuid": "...",
  "exp": 1624295651,
  "given_name": "Alexander",
  "iat": 1624292051,
  "family_name": "Foobar",
  "jti": "...",
  "email": "alexander.foobar@sap.com"
}
```

Upon validation the class `JwtIssuerValidator` responds with _invalid_ result:
```
Issuer is not trusted because 'iss' claim 'ma.accounts400.ondemand.com' does not provide a valid URI (missing http scheme). Please contact your Identity Provider Administrator.
```

I wonder is this expected? Is there a document which confirms this scheme requirement?

Maybe I'm using the API wrong(?) - are the classes above are only used for XSUAA token validation? Is there something similar for IAS?

---

**Update:** I looked into your `IasTokenAuthenticator` class and mimicked the validation logic:
```java
OAuth2ServiceConfiguration configuration;
Token token = new IasTokenAuthenticator().extractFromHeader("Bearer [ias-token]");
JwtValidatorBuilder.getInstance(configuration).build().validate(token);
```
Unfortunately it will throw the same exception.

Kind regards
Alex

**Comment by nenaraab** [comment]
Hi @newtork,

as a colleague you can access this [SAP-internal specification](https://github.wdf.sap.corp/CPSecurity/Knowledge-Base/blob/master/03_ApplicationSecurity/TokenValidation.md#2-issuer-validation).

The [fc7519#section-4.1.1](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.1) says its optional String or UR and [open id connect 1.0. spec](https://openid.net/specs/openid-connect-core-1_0.html#IssuerIdentifier) specifies it as URI, which includes imho the scheme.

Kind regards,
Nena

**Comment by newtork** [comment]
Hi @nenaraab,

Thanks for the quick and clear response, Unfortunately it seems we need to adjust our IdP settings. Do you _-by chance-_ have a guide on where to change it? To me it looks like a new IdP needs to be configured, because I can't edit the existing "issuer" value.

![image](https://user-images.githubusercontent.com/22489773/122963212-5c25ed80-d386-11eb-840c-902ce07fdf92.png)

Kind regards
Alex

**Comment by nenaraab** [comment]
Hi @newtork 
in my IAS admin the Authentication Context is set to "None" but the Issuer Name below the Suffix configuration contains "https". So I assume there is a more general setting.

If you go to `Applications & Resources` -> `Tenant Settings` -> `SAML 2.0 Configuration`
You can select in the `Identity Provider Settings` section the name in the drop down, one with and another one without https scheme.

Kind regards,
Nena

**Comment by nenaraab** [comment]
@strehle can you confirm that?

**Comment by strehle** [comment]
Hi @nenaraab , what excatly should I confirm?
The fact, that IAS can have OIDC issuer with and without https:// , then yes confirmed.
That is for legacy reason still possible to only set iasname.domain.com instead of https://iasname.domain.com

Both are a valid URI object according to RFCs., e.g. 2396.

So I see the issue comes from 
https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtIssuerValidator.java#L99-L102
and maybe you remove this and rely only only java URI object because this new URI - call performs many RFC compliant checks and both inputs

> iasname.domain.com
> https://iasname.domain.com
will be accepted.

**Comment by nenaraab** [comment]
Hi @newtork 

is it an option for you to change the identity provider settings? The default has changed since a while for new IAS tenants but never got this kind of question.

Kind regards,
Nena

**Comment by newtork** [comment]
Hi @nenaraab and @strehle,

Can we reopen the issue? I would like to challenge the decision to have [a protocol requirement](https://github.com/SAP/cloud-security-xsuaa-integration/blob/4bb471a957c0b951fa716f5d6eb48c5130d11393/java-security/src/main/java/com/sap/cloud/security/token/validation/validators/JwtIssuerValidator.java#L99-L103) for the issuer field in incoming JWTs from IAS.

In our end-to-end tests we are trying to exchange tokens with XSUAA in order to communicate with our Destination Service. Unfortunately XSUAA is responding with:
```json
{
  "error": "unauthorized",
  "error_description": "Unable to map issuer, https://ma.accounts400.ondemand.com , to a single registered provider"
}
```
When changing the issuer provided by IdP back to the original setting, then token exchange succeeded again.
```diff
- https://ma.accounts400.ondemand.com
+ ma.accounts400.ondemand.com
```

Since in your code, the `JwtIssuerValidator` ignores the protocol and only compares domain names, I wonder what the benefit of having it. In the meantime until we have a conclusion we're trying to workaround this limitation with our own [`CustomJwtIssuerValidator`](https://github.wdf.sap.corp/MA/sdk/blob/security-library/workaround-for-protocol-prefix-requirement/cloudplatform/security-scp-cf/src/main/java/com/sap/cloud/sdk/cloudplatform/security/CustomJwtIssuerValidator.java) class.

**Comment by newtork** [comment]
Argument against my feature request from OIDC standard:

https://openid.net/specs/openid-connect-core-1_0.html
> Issuer Identifier
> Verifiable Identifier for an Issuer. An Issuer Identifier is a case sensitive URL using the https scheme that contains scheme, host, and optionally, port number and path components and no query or fragment components.
