### ISSUE TITLE
Fix HttpHeaders.toString()

### ISSUE THREAD

**Issue by nenaraab** [SAP/cloud-security-xsuaa-integration#549]
Token was requested for endpoint uri=https://amsserver.authentication.cert.sap.hana.ondemand.com/oauth/token with **headers=HttpHeaders{headers=[com.sap.cloud.security.xsuaa.http.HttpHeader@e6516d15, com.sap.cloud.security.xsuaa.http.HttpHeader@8107e611, com.sap.cloud.security.xsuaa.http.HttpHeader@1a6a91e0]}** and parameters={grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer}

**Comment by liga-oz** [comment]
Merged #555
