### ISSUE TITLE
Support of Java Version > 8.X

### ISSUE THREAD

**Issue by nenaraab** [SAP/cloud-security-xsuaa-integration#552]
Additional Notes:
- we can't use latest Caffeine version as 3.x supports only Java 11 or higher, see also [PR #587](https://github.com/SAP/cloud-security-xsuaa-integration/pull/587)

**Comment by liga-oz** [comment]
Same problem for maven formatter plugin https://github.com/SAP/cloud-security-xsuaa-integration/pull/702

**Comment by liga-oz** [comment]
the following dependency is required to compile the project with java 11  as it's not part of jdk 11 anylonger:
```xml
<dependency>
   <groupId>javax.annotation</groupId>
   <artifactId>javax.annotation-api</artifactId>
</dependency>
```

**Comment by liga-oz** [comment]
Issue with `com.google.code.findbugs` dependency, development stopped in 2015 with JAVA 8  http://findbugs.sourceforge.net/ doesn't support higher versions. 

@nenaraab what you think of switching to this successor https://spotbugs.github.io/ ?
