### ISSUE TITLE
Support for Basic Auth in Client Credentials Flow

### ISSUE THREAD

**Issue by ww917352** [SAP/cloud-security-xsuaa-integration#554]
Hi colleagues,

OAuth2 standard also supports basic auth for client credentials flow (https://www.oauth.com/oauth2-servers/access-tokens/client-credentials/).

Could you also provide support for basic auth (client id as username, and client secret as password)? We (an SAP team) are using your token client library for token request. However, some customers are using the NEO OAuth2 Service (https://help.sap.com/viewer/ea72206b834e4ace9cd834feed6c0e09/Cloud/en-US/f69fa8762d2a44aab2a22ea7214fb3ff.html) that only supports basic auth for client credentials flow.

Thank you for checking it out.

Cheers,
Wei

**Comment by liga-oz** [comment]
Hi @ww917352,

if I understood you correctly, then you're using `XsuaaTokenFlows` from token-client module and want to perform `XsuaaTokenFlows.clientCredentialsTokenFlow()`, but need to replace `clientId` and `clientSecret` with `username` and `password`, for that scenario you can initialize the `XsuaaTokenFlows` class with your own provided `ClientIdentity` instance, like so:

```java
ClientIdentity clientIdentity = new ClientCredentials(username, password);

XsuaaTokenFlows tokenFlows = new XsuaaTokenFlows(
                    new DefaultOAuth2TokenService(HttpClientFactory.create(clientIdentity)),
                    new XsuaaDefaultEndpoints(<OAuth2ServiceConfiguration>),
                    clientIdentity);
```

Kind Regards,
Liga

**Comment by ww917352** [comment]
Hi @liga-oz ,

Thank you so much for your reply.

I upgraded to the latest version `2.10.0`, and tried what you suggested:

```
            flows = new XsuaaTokenFlows(
                new DefaultOAuth2TokenService(HttpClientFactory.create(clientCredentials)),
                new UnmodifiedBaseUriEndpoints(baseUaaUrl),
                clientCredentials);
            OAuth2TokenResponse reponse;
            try {
                reponse = flows.clientCredentialsTokenFlow().execute();
                return "Bearer " + reponse.getAccessToken();
            } catch (TokenFlowException e1) {
```

It still set client id and secret as parameters in the body instead of using them as username and password in basic auth. (I followed a debug session)

Did I miss something or do anything wrong here?

Thank you!

Cheers,
Wei

**Comment by liga-oz** [comment]
Hi @ww917352,

Did you create an instance of `ClientCredentials` with your provided username and password? That's where the request gets the clientId and clientSecret from to initialize `ClientCredentialsTokenFlow`

Kind Regards,
Liga

**Comment by ww917352** [comment]
Hi @liga-oz ,

Yes, we set it, but with client id and secret.

This is our original code

```
        ClientCredentials clientCredentials = new ClientCredentials(
                queryParams.get("client_id"),
                queryParams.get("client_secret"));
        XsuaaTokenFlows flows = new XsuaaTokenFlows(
            new DefaultOAuth2TokenService(), new UnmodifiedBaseUriEndpoints(baseUaaUrl), clientCredentials);
```

and this is the code with your suggestion

```
        ClientCredentials clientCredentials = new ClientCredentials(
                queryParams.get("client_id"),
                queryParams.get("client_secret"));
         XsuaaTokenFlows flows = new XsuaaTokenFlows(
              new DefaultOAuth2TokenService(HttpClientFactory.create(clientCredentials)),
              new UnmodifiedBaseUriEndpoints(baseUaaUrl),
              clientCredentials);
```

Do they actually do different things? We need to use the client id and secret and username/password in basic auth. I set breakpoints, and debugged, and didn't see this being done.

Thank you!

Cheers,
Wei

**Comment by liga-oz** [comment]
Hi @ww917352,

I guess I don't understand what exactly you're trying to achieve here, to perform client-credentials flow replacing client id and secret with username or password or something else? Can you show how your request should look like, where do you expect the client id, secret, username and password to be?

BR,
Liga

**Comment by ww917352** [comment]
Sure, Liga. Here is the curl command

```
curl --location --request POST 'https://oauthasservices-<<account_id>>.int.sap.eu2.hana.ondemand.com/oauth2/api/v1/token?token_format=jwt' \
--header 'Authorization: Basic <<username=client_id, password=client_secret>>' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=client_credentials'
```

**Comment by liga-oz** [comment]
Hi @ww917352 ,

I see now, this is not a request to xsuaa token endpoint. Unfortunately, our library does not support the request you mentioned. You can achieve what you've described by overriding the implementation of [AbstractOAuth2TokenService.retrieveAccessTokenViaClientCredentialsGrant](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/token-client/src/main/java/com/sap/cloud/security/xsuaa/client/AbstractOAuth2TokenService.java#L92) by providing the required header using [HttpHeadersFactory.createFromHeaders()](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/token-client/src/main/java/com/sap/cloud/security/xsuaa/http/HttpHeadersFactory.java#L42) method.

BR,
Liga

**Comment by ww917352** [comment]
Hi @liga-oz 

I was directed to the OAuth2.0 Spec, especially the following quotes

https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1

> The authorization server MUST support the HTTP Basic authentication scheme for authenticating clients that were issued a  client password.

and

> Including the client credentials in the request-body using the two parameters is NOT RECOMMENDED and SHOULD be limited to clients unable to directly utilize the HTTP Basic authentication scheme (or other password-based HTTP authentication schemes).

You can see that it is actually **not recommended** to pass client id and secret as parameter.

Can you please consider to use BASIC auth in client credentials flow because this is what every OAuth2 implementation must include.

Cheers,
Wei

**Comment by ww917352** [comment]
> Hi @ww917352 ,
> 
> I see now, this is not a request to xsuaa token endpoint. Unfortunately, our library does not support the request you mentioned. You can achieve what you've described by overriding the implementation of [AbstractOAuth2TokenService.retrieveAccessTokenViaClientCredentialsGrant](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/token-client/src/main/java/com/sap/cloud/security/xsuaa/client/AbstractOAuth2TokenService.java#L92) by providing the required header using [HttpHeadersFactory.createFromHeaders()](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/token-client/src/main/java/com/sap/cloud/security/xsuaa/http/HttpHeadersFactory.java#L42) method.
> 
> BR,
> Liga

I will give it a try. Thank you, @liga-oz

**Comment by ww917352** [comment]
Hi Liga,

There are private fields and methods used in retrieveAccessTokenViaClientCredentialsGrant. How can I override it in a way that just changes the headers?

Thank you!

Cheers,
Wei

**Comment by liga-oz** [comment]
Hi @ww917352 ,

as going forward default authentication method will switch to certificate(X.509) based this does not impose a security vulnerability, moreover, client secret won't be required at all for client-credentials flow, only client id. You can read more about it [here](https://github.wdf.sap.corp/CPSecurity/Knowledge-Base/blob/master/90_CrownJewels/faq.md)

You can check this [issue](https://github.com/SAP/cloud-security-xsuaa-integration/issues/318) that seems to be the same as yours, with that I'm closing this issue.

Kind Regards,
Liga
