### ISSUE TITLE
Missing java-api dependency in spring-xsuaa?

### ISSUE THREAD

**Issue by luk-lo** [SAP/cloud-security-xsuaa-integration#558]
Using version 2.10.0 of `xsuaa-spring-boot-starter`, the following error occurs during our integration tests:

```
java.lang.NoClassDefFoundError: com/sap/cloud/security/config/CredentialType
        at com.sap.cloud.security.xsuaa.autoconfiguration.XsuaaAutoConfiguration$OnNotX509CredentialTypeCondition.matches(XsuaaAutoConfiguration.java:113)
```

Looking at the `XsuaaAutoConfiguration` and `CredentialType` classes, it appears the `spring-xsuaa` artifact (where `XsuaaAutoConfiguration` is located) may be missing a dependency on the `java-api` artifact (where `CredentialType` is located).

Adding the `java-api` dependency to our project resolved the issue so it looks like that is the case.

**Comment by liga-oz** [comment]
Hi @luk-lo,

thanks a lot for reporting the issue. Indeed, java-api dependency is missing in spring-xsuaa module 💯 

BR,
Liga
