### ISSUE TITLE
XsuaaServiceConfigurationDefault Property Extension

### ISSUE THREAD

**Issue by m-ignatov** [SAP/cloud-security-xsuaa-integration#601]
Hi colleagues,

Our team uses the `XsuaaServiceConfigurationDefault` configuration from `spring-security-xsuaa` and we have the use case to get the `tenantid` and `apiurl` properties of an XSUAA service instance.

Could you extend the `XsuaaServiceConfigurationDefault` configuration with getters for the mentioned properties? 
As I can see, the `XsuaaServicePropertySourceFactory` can be extended, so they can be mapped to the configuration.

Thanks and best regards,
Momchil

**Comment by nenaraab** [comment]
Hi @m-ignatov 
Lets see 👍 
can you pls provide us your xsuaa VCAP_SERVICES (without exposing secret and other sensitive data).
Thanks!

**Comment by m-ignatov** [comment]
Hi @nenaraab

Thanks for the quick response. 

Actually, there are not new fields, but part of the "credentials" section of the XSUAA VCAP_SERVICES:
```
"xsuaa": [
{
 ...
   
   "credentials": {
     "apiurl": "https://api.authentication.<region>.hana.ondemand.com",
     "tenantid": "<tenant_id>"
   },
   "instance_name": "xsuaa",
   "label": "xsuaa",
   "name": "xsuaa",
   "plan": "application"
     
 ...
}
   ```
   
We can also arrange a meeting to discuss it, if needed.

**Comment by nenaraab** [comment]
Hi @torsten-sap 

what is your opinion here?
Shall we support `tenantid` and `apiurl` - is it always available? Where do we find further documentation?

Kind regards,
Nena

**Comment by torsten-sap** [comment]
Hi @nenaraab,
I think the "apiurl" makes sense. Regarding "tenantid" I am not quite sure whether rather the "zoneid" should be used. @m-ignatov What is your use-case to get the "tenantid"?

In general it might be the case that "apiurl" is not available in the binding (very old binding) but the libs may return null in that case.

-Torsten

**Comment by m-ignatov** [comment]
Hi @torsten-sap, 

We have several use cases for the "tenantid", including system audit logging, and the "apiurl" is used for XSUAA API operations.

As far as I know, the "zoneid" and "tenantid" are the same currently for XSUAA. In our codebase we are using the term "tenantid", and that's why prefer to be consistent everywhere. I guess it is fine for the XSUAA library to support the retrieval of both properties. 

It also makes sense to me that if a property is missing from the XSUAA VCAP, the lib would return null.

Regards,
Momchil

**Comment by nenaraab** [comment]
Hi @m-ignatov 

I understand, but the tenant information should could be easily derived from the verified token, e.g. from the security context. See also [here](https://github.com/SAP-samples/teched2020-DEV263#changed-api-for-multi-tenant-applications-to-determine-tenant-identifier-getsubaccountid-replaced-by-getzoneid).

In case you need further information than exposed with XsuaaServiceConfigurationDefault class you can leverage for now [DefaultJsonObject](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/java-security/src/main/java/com/sap/cloud/security/json/DefaultJsonObject.java) as described [here](https://github.com/SAP/cloud-security-xsuaa-integration/tree/master/java-security#get-further-information-from-vcap_services)

Will recheck the requirement later.

Kind regards,
Nena

**Comment by m-ignatov** [comment]
Thank you for considering it, Nena.

Actually in our use case, we need the information for the system tenant, which is derived from the XSUAA binding.

Of course, there can be a workaround to get the needed info, but it would be great if the XsuaaServiceConfigurationDefault supported these properties as well :)


Kind regards,
Momchil
