### ISSUE TITLE
Add token_type in OAuth2TokenResponse

### ISSUE THREAD

**Issue by tsvetomir-lyubenov** [SAP/cloud-security-xsuaa-integration#606]
Hi Colleagues,

We are trying to use the XSUAA Token Client and Token Flow API for token retrieval.

However, there is one little problem.

If we look at OAuth2TokenResponse we can see that it contains the access token and its expiration time, but it doesn't contain the token type.

Could you please add it to the OAuth2TokenResponse so that there won't be need to use a hard-coded "Bearer " string in our code?

Best regards,
Tsvetomir Lyubenov

**Comment by nenaraab** [comment]
Hi @tsvetomir-lyubenov 
Thanks for the request. Will consider that small enhancement in one of our next releases.

This is the [api/contract](https://docs.cloudfoundry.org/api/uaa/version/75.5.0/index.html#jwt-bearer-token-grant) 
It states *token_type will always be bearer*.
 
Consequently, as workaround you can just do 
```
"bearer" + OAuth2TokenResponse.getAccessToken() 
```

Kind regards,
Nena
