### ISSUE TITLE
K8s fallback for missing service-manager binding

### ISSUE THREAD

**Issue by liga-oz** [SAP/cloud-security-xsuaa-integration#619]
service-manager is required to fetch the service instance plans for the bound Xsuaa service instances, at the moment if the service-manager is not provided it will result in empty xsuaa service configuration as the plans can't be mapped.
Proposal for a fallback option, to take the first item from Xsuaa OAuthServiceConfiguration array in case no service-manager is provided with a warning message in logs.

**Comment by nenaraab** [comment]
Hi @liga-oz 

the default should be only one xsuaa binding, in that case no service manager should be required.

In case of multiple bindings, we can do it like in the ias case and as you proposed, that we take the first and log a warning...
The downside of that approach, 
a) is that developers might not recognize the warning and do not understand follow up errors... and do not understand that they have to do something.
b) our client lib behaves different in the K8s environment compared with CF environment
