### ISSUE TITLE
[token-client] extend SSLContextFactory with KeyStore getter method

### ISSUE THREAD

**Issue by liga-oz** [SAP/cloud-security-xsuaa-integration#621]
For a case when application provides custom implementation for `HttpClientFactory` interface, it would be helpful to have access to `KeyStore` object to reduce code duplications for certificate and key parsing when initialising custom `SSLContext`.

Proposal to add public method `getKeyStore` to [SSLContextFactory](https://github.com/SAP/cloud-security-xsuaa-integration/blob/master/token-client/src/main/java/com/sap/cloud/security/mtls/SSLContextFactory.java) which would resolve accordingly the `certificate` and `key` attributes from `ClientIdentity` class and initialize the `KeyStore`.
```java
public KeyStore getKeyStore(ClientIdentity clientIdentity){...}
```

**Comment by nenaraab** [comment]
On hold: asked for further details.
