### ISSUE TITLE
[Question] [CJ] How will you deal with outdated XSUAA client certificates?

### ISSUE THREAD

**Issue by newtork** [SAP/cloud-security-xsuaa-integration#628]
I'm from the [SAP Cloud SDK](https://sap.github.io/cloud-sdk/) team and I'm wondering what would be your response:

On **Cloud Foundry** as a consumer of your client libraries I will soon face the following situation:

- A service binding to **XSUAA** will result in configuration `"credentials-type": "x509"` (new default) instead of `"binding-secret"` or `"instance-secret"`. With the binding comes an entry in environment variable `"VCAP_SERVICES"`, containing a base64-encoded `"certificate"`. This is being read by your library and used for communicating with XSUAA.

- Authorization and token exchange will work fine for 7 days. Afterwards the provided certificate is expired, the end of validity is reached.

- What do I do now?

**Comment by nenaraab** [comment]
Hi @MatKuhr 

for now I would suggest to [create an issue here](https://github.wdf.sap.corp/CPSecurity/Knowledge-Base/issues/new) to extend the SAP-internal documentation, in case boundary conditions are not sufficiently documented:
https://github.wdf.sap.corp/pages/CPSecurity/Knowledge-Base/03_ApplicationSecurity/X509Authentication/
This might then be part of help.sap.com as well.

Kind regards,
Nena
