### ISSUE TITLE
Retrieving OAuth2ServiceConfiguration object for bounded services with CF apps

### ISSUE THREAD

**Issue by SumanSwati** [SAP/cloud-security-xsuaa-integration#716]
Hi Team 

We wanted to switch to xsuaa _X.509_ authentication instead of client-secret base authentication, in order to make communication with other services. We followed this SAP's java security [document](https://github.com/SAP/cloud-security-xsuaa-integration/tree/main/token-client) and this is how we implemented it for our app.

After following the documentation, We got to know that, we would need _OAuth2ServiceConfiguration_ instance for bounded services in order to perform authentication. So Can someone suggest me, how can I get _OAuth2ServiceConfiguration_ instance for respective services? I have different services and plans in-place.

**Question Summary**
If applicable, please mention:
- java cloud.security.xsuaa token-client library - 2.11.2
- Environment: Cloud Foundry

**Comment by nenaraab** [comment]
Hi @SumanSwati 
there is `Environments.getCurrent()` to get an instance of `OAuth2ServiceConfiguration`. But if you share further details on how you did it previously (maybe some code snippet and information about the bound xsuaa instances) we can support you further.

**Comment by SumanSwati** [comment]
Thanks, but as far as my understanding this is useful for our xsuaa services. :)  But I wanted to know how will I get this OAuth2ServiceConfiguration instance for other services like _metering svc_, etc, which are bounded to our apps. By the way, this is how our code snippet looks like, in order to get xsuaaAccesstoken of any services with client-secret authentication:

```
Credentials credentials = VcapServices.getCredentials(serviceName);
String url = (String) credentials.get(TOKEN_URL)),
String clientId =  (String) credentials.get("clientid"), 
String clientSecret = (String) credentials.get("clientsecret"))

@SuppressWarnings("rawtypes")
 public static ResponseEntity<Map> getAccessToken(final String url, final String clientId, final String clientSecret) {
        RestTemplate restTemplate = new RestTemplate();
        HttpHeaders headers = new HttpHeaders();
        headers.add(HttpHeaders.AUTHORIZATION, getBasicAuthorizationString(clientId, clientSecret));
        MultiValueMap<String, String> map = new LinkedMultiValueMap<>();
        map.add(GRANT_TYPE, CLIENT_CREDENTIALS);
        HttpEntity<MultiValueMap<String, String>> request = new HttpEntity<>(map, headers);
        return restTemplate.postForEntity(url, request, Map.class);
    }
```

**Comment by nenaraab** [comment]
This request is related to #707 

```java
Credentials credentials = VcapServices.getCredentials(serviceName);
String url = (String) credentials.get(TOKEN_URL)),
String clientId =  (String) credentials.get("clientid"), 
String clientSecret = (String) credentials.get("clientsecret"))

XsuaaTokenFlows tokenFlows =
        new XsuaaTokenFlows(
            new XsuaaOAuth2TokenService(<your Rest Template>),  
            new XsuaaDefaultEndpoints(uaa, null), // available as of 2.11.3 version see also #707
            new ClientCredentials(clientId, clientSecret));
```

does this answer your question?

**Comment by SumanSwati** [comment]
No, Actually, I want to have both way of authentication, client-secret as well as  x.509 auth, which means I need to use certificate and key. Also I don't want to write my own logic if x509, then do this, if credential contain secret, then do that. I believe 2.11.2 token-client takes care of that. That's the reason I said I followed the latest document: https://github.com/SAP/cloud-security-xsuaa-integration/tree/main/token-client where it is said to do something like this:

```
XsuaaTokenFlows tokenFlows = new XsuaaTokenFlows(
					new DefaultOAuth2TokenService(HttpClientFactory.create(configuration.getClientIdentity())),
					new XsuaaDefaultEndpoints(configuration), configuration.getClientIdentity());
		    tokenResponse = tokenFlows.clientCredentialsTokenFlow().execute();
```

This configuration is an instance of OAuth2ServiceConfiguration, as per the documentation. Now my only query is: _how do I get this configuration instance for services like metering service etc which are bound to our application_?
I hope I have given the exact query now. Let me know if you need any thing from my side.

**Comment by nenaraab** [comment]
Hi @SumanSwati 

Correct! This code snippet explains how to initialize XsuaaTokenFlows for client certificate based token flow:
```java
Credentials credentials = VcapServices.getCredentials(serviceName);
String url = (String) credentials.get(TOKEN_URL)),
String clientId =  (String) credentials.get("clientid"), 
String clientCert = (String) credentials.get("certificate")) //new
String clientCertKey = (String) credentials.get("key")) //new

ClientIdentity identity = new ClientCertificate(clientCert, clientCertKey, clientId);

XsuaaTokenFlows tokenFlows =
        new XsuaaTokenFlows(
            new DefaultOAuth2TokenService(HttpClientFactory.create(identity)),
            new XsuaaDefaultEndpoints(url, null), // available as of 2.11.3 version see also #707
            identity);
```

does this answer your question?

**Comment by nenaraab** [comment]
Hi @SumanSwati 

there is a `OAuth2ServiceConfigurationBuilder` provided with the env project (should be a transient dependency)...

Please try:
```java
OAuth2ServiceConfigurationBuilder builder = OAuth2ServiceConfigurationBuilder.forService(Service.XSUAA);
OAuth2ServiceConfiguration config = builder.withClientId(...)
                                                                              .withClientSecret(...)
                                                                              .withCertificate(...)
                                                                              .withPrivateKey(...)
                                                                              .withUrl(...)
                                                                              .withCertUrl(...).build();
```

**Comment by SumanSwati** [comment]
Thanks, This is what I was looking for :)

**Comment by SumanSwati** [comment]
is 2.11.3 version is available? I dont see it in the latest release.

**Comment by SumanSwati** [comment]
> ```java
> OAuth2ServiceConfigurationBuilder builder = OAuth2ServiceConfigurationBuilder.forService(Service.XSUAA);
> ```

Also, The example state OAuth2ServiceConfigurationBuilder for XSUAA service. What about other services, which are bound to our app like metering-service, etc ? Can you also state example for that as well?

**Comment by nenaraab** [comment]
Hi @SumanSwati 
the version `2.11.3` gets hopefully released by end of this week, you can watch this github repo to get notified by new releases.

In regard to the `OAuth2ServiceConfigurationBuilder.forService(Service.XSUAA)` ... its just a constant that defines, that the parameters like clientid, url are the oauth2 configurations of an Xsuaa service.

**Comment by nenaraab** [comment]
Hi @SumanSwati if you like, you can review the PR as well: 
https://github.com/SAP/cloud-security-xsuaa-integration/pull/720
