### ISSUE TITLE
Support for reactive ServerHttpSecurity (Spring webflux)

### ISSUE THREAD

**Issue by RRoggia** [SAP/cloud-security-xsuaa-integration#75]
> A ServerHttpSecurity is similar to Spring Security's HttpSecurity but for WebFlux.

The library does not support the reactive interface `ReactiveJwtDecoder` nor the `Converter<Jwt, ? extends Mono<? extends AbstractAuthenticationToken>>`. Therefore, an webflux project is required to have some wrappers in order to use this library.

Something like this:
```java
@EnableWebFluxSecurity
@EnableReactiveMethodSecurity
@PropertySource(factory = XsuaaServicePropertySourceFactory.class, value = { "" })
public class WebSecurityConfig {

	@Autowired
	XsuaaServiceConfigurationDefault xsuaaServiceConfiguration;

	@Bean
	public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
	http.authorizeExchange().anyExchange().authenticated().and().oauth2ResourceServer().jwt()
				.jwtAuthenticationConverter(getJwtAuthoritiesConverter()).jwtDecoder(jwtDecoder());

		return http.build();
	}

	private ReactiveJwtDecoder jwtDecoder() {
		return token -> {
			JwtDecoder build = new XsuaaJwtDecoderBuilder(xsuaaServiceConfiguration).build();
			return Mono.just(build.decode(token));
		};
	}

	private Converter<Jwt, Mono<AbstractAuthenticationToken>> getJwtAuthoritiesConverter() {
		return jwt -> {
			TokenAuthenticationConverter converter = new TokenAuthenticationConverter(xsuaaServiceConfiguration);
			converter.setLocalScopeAsAuthorities(true);
			return Mono.just(converter.convert(jwt));
		};
	}

	@Bean
	XsuaaServiceConfigurationDefault xsuaaConfig() {
		return new XsuaaServiceConfigurationDefault();
	}

}
```
Although, these wrappers enable the usage of the library for webflux projects, they do not make usage of a full reactive approach and this might impact the overall performance of the application. I'm still trying to figure out how big is the impact.

Yet, I think people would benefit from having a some reactive interfaces to enable webflux apps. The impacts I see:
* Add the reactor library as dependecy.
* new class for `ReactiveTokenAuthenticationConverter` implementing the `Converter<Jwt, ? extends Mono<? extends AbstractAuthenticationToken>>` interface.
* new class for `ReactiveXsuaaJwtDecoder` implementing the `ReactiveJwtDecoder`.
* `buildAsReactive` new method in `XsuaaJwtDecoderBuilder` for building the `ReactiveJwtDecoder`.

I think this could be a beginning for at least enabling the lib to webflux. While it's not fully enabled with reactor. 

Waiting to hear your thoughts about it.

**Comment by RRoggia** [comment]
With the proposed additions the security configuration would look like:
```java
@EnableWebFluxSecurity
@EnableReactiveMethodSecurity
@PropertySource(factory = XsuaaServicePropertySourceFactory.class, value = { "" })
public class WebSecurityConfig {

	@Autowired
	XsuaaServiceConfigurationDefault xsuaaServiceConfiguration;

	@Bean
	public SecurityWebFilterChain securityWebFilterChain(ServerHttpSecurity http) {
		http.authorizeExchange().anyExchange().authenticated().and().oauth2ResourceServer().jwt()
				.jwtAuthenticationConverter(new ReactiveTokenAuthenticationConverter(xsuaaServiceConfiguration))
				.jwtDecoder(new XsuaaJwtDecoderBuilder(xsuaaServiceConfiguration).buildAsReactive());

		return http.build();
	}

	@Bean
	XsuaaServiceConfigurationDefault xsuaaConfig() {
		return new XsuaaServiceConfigurationDefault();
	}

}
```

**Comment by mwdb** [comment]
I have not yet had a deeper look into the reactive Spring. 
Do you want to create a PR for this?
