### ISSUE TITLE
Log4j vulnerability impact

### ISSUE THREAD

**Issue by JerryZhang0929** [SAP/cloud-security-xsuaa-integration#750]
As you might know, log4j has a big vulnerability. We use project template provided SAP Cloud SDK library. Inside the project, by default, the xsuaa-spring-boot-starter is included and the version is 2.11.0. When I run mvn dependency:tree, I can see the log4j-to-slf4j is used which contains log4j-api:jar:2.14.1. 

[INFO] +- com.sap.cloud.security.xsuaa:xsuaa-spring-boot-starter:jar:2.11.5:compile
[INFO] |  +- com.sap.cloud.security.xsuaa:spring-xsuaa:jar:2.11.5:compile
[INFO] |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.14.1:compile
[INFO] |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.14.1:compile

Is there any impact on the application running on SAP BTP, Cloud Foundry environment?

**Comment by SumanSwati** [comment]
I already see this issue has been merged as part of this commit: https://github.com/SAP/cloud-security-xsuaa-integration/pull/749/files When is the plan to have the next release?

**Comment by nenaraab** [comment]
Dear @JerryZhang0929 and @SumanSwati 
thanks a lot for reporting it!
Actually, I've checked already yesterday and according to this [Spring blog post](https://spring.io/blog/2021/12/10/log4j2-vulnerability-and-spring-boot), there is no issue in `log4j-to-slf4j` and `log4j-api`...
> Only applications using log4j-core and including user input in log messages are vulnerable.

Still, I 'm going to release it now, so everyone who uses one of our spring starters can upgrade.

**Comment by JerryZhang0929** [comment]
Thank you very much for the information.

**Comment by nenaraab** [comment]
[release 2.11.6 ](https://github.com/SAP/cloud-security-xsuaa-integration/releases/tag/2.11.6) is available - but as said, an upgrade is not required.
