### ISSUE TITLE
Sample sap-java-buildpack-api-usage not working because of missing jar in maven central?

### ISSUE THREAD

**Issue by maxstreifeneder** [SAP/cloud-security-xsuaa-integration#76]
Dear colleagues,

I was about to try the provided samples from sap-java-buildpack-api-usage, but unfortunately couldn't get it working. 

Followed the steps to clone the repository, installed the approuter and when I want to build my java projecrt via **mvn package** the following error occurs: 

![image](https://user-images.githubusercontent.com/36535298/57289984-ca32cc00-70bc-11e9-9f2a-e138ff3e7ba7.png)

I assume this happens because version 1.4.0 of com.sap.cloud.security.xsuaa.api is not yet published on maven central? are you using a different repository? 

![image](https://user-images.githubusercontent.com/36535298/57290130-141bb200-70bd-11e9-8fde-1f5677d0e80a.png)

the according POM (not edited, still the provided one) looks like: 

```xml: 
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.sap.cloud.security.xssec.samples</groupId>
	<artifactId>sap-java-buildpack-api-usage</artifactId>
	<version>1.0</version>
	<packaging>war</packaging>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<version>2.3</version>
				<configuration>
					<warName>sap-java-buildpack-api-usage</warName>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<dependencies>
		<dependency>
			<groupId>com.sap.cloud.security.xsuaa</groupId>
			<artifactId>api</artifactId>
			<version>1.4.0</version>
			<scope>provided</scope>
		</dependency>
		<!-- https://mvnrepository.com/artifact/javax.servlet/javax.servlet-api -->
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>3.0.1</version>
			<scope>provided</scope>
		</dependency>

	</dependencies>
</project>
```

Thanks in advance and cheers,
Max

**Comment by mwdb** [comment]
yes, we indeed already increased the version, but did not yet publish a release build.
As a workaround please build it locally with
man clean install

Release build is expected begin of next week.

**Comment by mwdb** [comment]
Closing as version 1.4.0 is available on maven central
