### ISSUE TITLE
XsuaaServiceConfigurationDefault breaking change since 2.11.1

### ISSUE THREAD

**Issue by m-ignatov** [SAP/cloud-security-xsuaa-integration#802]
Hi colleagues,

It seems that from version 2.11.1 of XSUAA Spring library, the `XsuaaServiceConfigurationDefault` class has breaking changes that affect the ability to get XSUAA VCAP properties that are not mapped in the class and do not have any getters. 

The `getProperty()` and `hasProperty()` methods were deleted.
For example, properties like API URL and tenant ID cannot be fetched now directly.

How can these properties be fetched via the XSUAA Spring library?

As far as I can see, the change is from here:
https://github.com/SAP/cloud-security-xsuaa-integration/pull/698/files#diff-578760e442614f47823e1a3c83ed22a0a8cab50f5005861b9417764499473606L115

Best regards,
Momchil

**Comment by nenaraab** [comment]
Hi @m-ignatov 

First of all, sorry for the delay!
Yes, I have to admit, that I've introduced with version `2.11.0` the method implementation for `hasProperty` and  `getProperty`, which has caused an incompatibility and unwanted side effect (see issue #695).
Consequently we repaired that in version `2.11.1`.  And as we have never documented `hasProperty` and  `getProperty` we just falled back to the previous implementation, hope that all would update to latest version soon...

All common xsuaa service credentials should be accessible via `XsuaaServiceConfigurationDefault` API.
Your xsuaa service binding consists of `tenant id` and `api url`? 
Can you please share your xsuaa vcap_services binding with me (via email) and without sensitive data e.g. secrets/certificates/keys...?

**Comment by nenaraab** [comment]
Affected commits:
1. https://github.com/SAP/cloud-security-xsuaa-integration/commit/3cb10bcda77709523f42c67c7804b5f96d9e0ca3 
2. https://github.com/SAP/cloud-security-xsuaa-integration/pull/698 (issue #695)
