### ISSUE TITLE
Challenging Own HttpClientFactory

### ISSUE THREAD

**Issue by kramerul** [SAP/cloud-security-xsuaa-integration#810]
I find it quite challenging to [provide an own HttpClientFactory](https://github.com/SAP/cloud-security-xsuaa-integration/blob/main/token-client/README.md#new-warning-in-productive-environment-provide-well-configured-httpclientfactory-service). It would be nice if you would provide at least an example with possible configuration parameters.

This is [my solution](https://github.tools.sap/nucleus-resources/nucleus-resources-broker/blob/http-client-factory-271/src/main/java/com/sap/sva/nucleus/resources/broker/config/NucleusHttpClientFactory.java). I'm not 100% sure if it's working correctly.

**Comment by liga-oz** [comment]
Hi @kramerul,
 
the code snippets and explanation are described in this [article](https://www.baeldung.com/httpclient-connection-management). There is no right or wrong setup that will work or not work for every use case, you need to test your application and evaluate the performance and stability with different settings and adjust timeouts, pool sizes etc based on the evaluation results.

Kind Regards,
Liga

**Comment by kramerul** [comment]
Hi @liga-oz,

thank you for your quick answer. I already studied [this article](https://www.baeldung.com/httpclient-connection-management) and found it not really helpful. 

Especially the pooling requires much more effort as you can see in [my solution](https://github.tools.sap/nucleus-resources/nucleus-resources-broker/blob/http-client-factory-271/src/main/java/com/sap/sva/nucleus/resources/broker/config/NucleusHttpClientFactory.java).

I searched on github.tools.sap for other solutions and found only one [UaaClient](https://github.tools.sap/IO-CLOUD/it-op-multicloud-utils/blob/812286039d9ffe0721ccd29d468c88e58a547eb4/bundles/com.sap.it.op.multicloud.utils.commons/src/main/java/com/sap/it/op/multicloud/utils/commons/uaa/UaaClient.java). This is an indicator for
* Only a few people are taking your warning serious
* Most of them are not willing to implement an own `HttpClientFactory`
* Pooling of SSL connections is really a challenge.

**Comment by liga-oz** [comment]
Hi @kramerul,

we cannot just like that simplify SSL connection configuration, developers have to understand it thoroughly to configure it correctly, we can't do it for everyone, because it won't fit to all scenarios. 
If the developers are not introducing their own implementation/configuration that is then up to them and in their responsibility.

This is an open source project, feel free to contribute if you see improvement possibilities.

Kind Regards,
Liga

**Comment by nenaraab** [comment]
Hi @kramerul,

thanks again for your feedback and also contribution here 🥇 !
I will close this issue as duplicate of #842.
A PR for milestone `2.12` is prepared and in review (see also #849). Feel free to have a look at and provide your feedback.

Kind regards,
Nena
