### ISSUE TITLE
WebFlux-Based XSUAA library

### ISSUE THREAD

**Issue by vasil-tsimashchuk** [SAP/cloud-security-xsuaa-integration#825]
**Is your feature request related to a problem? Please describe.**
Current implementation of _XSUAA_ library is based on Spring's `RestTemplate`. `RestTemplate` is deprecated since _Spring 5_ which means it's not really that future proof. `WebClient` is part of _Spring WebFlux_ and is intended to replace the classic `RestTemplate`. Compared to `RestTemplate`, `WebClient` has a more functional feel and is fully reactive. In addition, modern _Spring_ projects, e.g. _Spring Cloud Gateway_, are based on the `WebClient`.

As of today, integration of _XSUAA_ library in a _WebFlux_-based project, e.g. _Spring Cloud Gateway_, needs to be performed with extra caution in order to comply with reactive programming model and leverage its strengths (e.g. IO operations executed in a non-caller thread).

**Describe the solution you'd like**
_Spring WebFlux_-based _XSUAA_ library making use of `WebClient` and fostering reactive programming model would be a natural solution to the problem.

**Additional context**
* https://www.baeldung.com/spring-webclient-resttemplate

**Comment by nenaraab** [comment]
Hi @vasil-tsimashchuk thanks a lot for the request and sorry for the long delay in answering it. 

Its an open-source project, and in the past developers that required the WebFlux feature has contributed that extension. Unfortunately - as my knowledge is less - i would suggest you to apply the enhancements and myself are going to support you however possible, concept discussion, review, knowledge transfer session etc. 

What so you think?

**Comment by nenaraab** [comment]
Hi @vasil-tsimashchuk I'm going to close that issue for now, please let me know on how to continue here.
