### ISSUE TITLE
How to get refresh token

### ISSUE THREAD

**Issue by sayortanaka** [SAP/cloud-security-xsuaa-integration#840]
Hi team,

I try this sample, I can get access token, but not get refresh token.
Refresh token is null.

https://github.com/SAP/cloud-security-xsuaa-integration/blob/5302fb58a2f361fd2a706164e79474be041eb65e/samples/spring-security-xsuaa-usage/src/main/java/sample/spring/xsuaa/TestController.java#L172

How to get refresh token?

**Comment by liga-oz** [comment]
HI @sayortanaka,

if you fetch the token from xsuaa directly via curl or postman, is the refresh token present in the response?

**Comment by sayortanaka** [comment]
@liga-oz 
No, refresh token is null.

**To Reproduce**
1. Get the access token.
https://spring-security-xsuaa-usage-web-<ID>.<LANDSCAPE_APPS_DOMAIN>/v1/sayHello
2. Use postman, select authentication type bearer token and set access token.
3. GET https://spring-security-xsuaa-usage-sample-<ID>.<LANDSCAPE_APPS_DOMAIN>/v3/requestUserToken

ClientCredentialsToken is the same.
`clientCredentialsTokenResponse.getRefreshToken()` is null.
https://github.com/SAP/cloud-security-xsuaa-integration/blob/ca657920fef09f3eb8a55fc9b6230acfc4a3e2bb/samples/spring-security-xsuaa-usage/src/main/java/sample/spring/xsuaa/TestController.java#L139

**Comment by liga-oz** [comment]
Hi @sayortanaka,

I meant fetching token directly from XSUAA, without sample app interference.
See [here](https://github.com/SAP/cloud-security-xsuaa-integration/blob/main/docs/HowToFetchToken.md#xsuaa-tokens) how to fetch token from XSUAA.

Kind Regards,
Liga

**Comment by sayortanaka** [comment]
Hi @liga-oz 

I'm sorry, I understand.
I ran the curl command by following the steps in the link, I got an refresh token.

**Comment by nenaraab** [comment]
@sayortanaka 

Client Credential and JWT Bearer Token Flows does not support `refresh_token` in the response, see specification here: 
- https://docs.cloudfoundry.org/api/uaa/version/4.30.0/index.html#client-credentials-grant
- https://docs.cloudfoundry.org/api/uaa/version/4.30.0/index.html#jwt-bearer-token-grant

Only the user token flow supports it.
We had to switch from UAA proprietary User Token Flow to the JWT Bearer Token flow some times ago, and didn't adapted samples and documentation. It seems that we can support the Refresh Token Flow, but you don't get such a refresh token any longer via `ClientCredentialsTokenFlow` and `UserTokenFlow` API. Sorry, for that!

**Comment by sayortanaka** [comment]
@nenaraab 
Can't get refresh token using application, is the understanding correct?

**Comment by nenaraab** [comment]
@sayortanaka exactly, as JWT Bearer token flow, as well as Client Credentials token flow does not provide refresh token.
