### ISSUE TITLE
Stop DefaultHttpClientFactory from logging warning messages

### ISSUE THREAD

**Issue by newtork** [SAP/cloud-security-xsuaa-integration#842]
Related https://github.com/SAP/cloud-security-xsuaa-integration/issues/810

**Is your feature request related to a problem? Please describe.**
[SAP Cloud SDK](https://sap.github.io/cloud-sdk/) uses this library.
We noticed [`DefaultHttpClientFactory` logs a warning](https://github.com/SAP/cloud-security-xsuaa-integration/blob/ca657920fef09f3eb8a55fc9b6230acfc4a3e2bb/token-client/src/main/java/com/sap/cloud/security/client/DefaultHttpClientFactory.java#L30) urging to provide a custom implementation.

_Cloud SDK_ implemented a [`CertificateBasedHttpClientFactory`](https://github.wdf.sap.corp/MA/sdk/blob/develop/cloudplatform/cloudplatform-connectivity-scp-cf/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/CertificateBasedHttpClientFactory.java) which works but does not really bring advantage to the original `DefaultHttpClientFactory`. The problem is class loading which [does not work reliable with _SAP Java Buildpack_](https://jtrack.wdf.sap.corp/browse/NGPBUG-180018).

**Describe the solution you'd like**
`DefaultHttpClientFactory` no longer logs a warning.
```diff
- LOGGER.warn("In productive environment provide well configured HttpClientFactory service");
```
_Cloud SDK_ can remove their implementation. The class loading works again. No warning messages are logged.

**Describe alternatives you've considered**
Providing own / customer implementation will lead to class loading problems.

**Additional context**
When considering _Cloud Foundry_ I don't see any issues with the original implementation of `DefaultHttpClientFactory`. It's unclear for us, why this should not be used by default.

**Comment by nenaraab** [comment]
related ticket #810

**Comment by nenaraab** [comment]
Hi @newtork could you please help us in testing that PR in production?
https://github.com/SAP/cloud-security-xsuaa-integration/pull/849

**Comment by nenaraab** [comment]
done with https://github.com/SAP/cloud-security-xsuaa-integration/releases/tag/2.12.0
