### ISSUE TITLE
Inquiry regarding X.509 authentication method with XSUAA managed certificate.

### ISSUE THREAD

**Issue by micol92** [SAP/cloud-security-xsuaa-integration#844]
**Question Summary**

Hello,

Should we make use of X.509 authentication method in the xs-security.json ?
I've heard that users have to unbind and rebind any consuming applications to rotate binding secrets so that users makes use of X.509.
If it's designed concept for X.509, is there a way to automate it without repetitive manual task by users ?

And if the user wants to deprecated method, are there any expected problems ? 

<img width="1238" alt="image" src="https://user-images.githubusercontent.com/39489882/159012619-c545a8f0-0716-4c02-9f38-e7ee88227685.png">

Best Regards
Jungwoo

**Comment by nenaraab** [comment]
Hi @micol92 

your question needs to be addressed to the xsuaa service component, which also implement the service broker.
Please create either a NGPBUG ticket on our `xsuaa` component or, alternatively a ServiceNow case can be created on `BC-CP-CF-SEC-IAM`.
