### ISSUE TITLE
Dependency on spotbugs-annotations should be optional

### ISSUE THREAD

**Issue by calle2010** [SAP/cloud-security-xsuaa-integration#851]
**Is your feature request related to a problem? Please describe.**

The dependency on spotbugs-annotations in 
[cloud-security-xsuaa-integration](https://github.com/SAP/cloud-security-xsuaa-integration/tree/ade5764ec22ba60ecee726988bd3fb0ec1995dce)/[java-api](https://github.com/SAP/cloud-security-xsuaa-integration/tree/ade5764ec22ba60ecee726988bd3fb0ec1995dce/java-api)/pom.xml
is transitive. This means projects relying on java-api will be delivering spotbugs-annotations and findbugs:jsr305 to their clients.

I assume this is not required as these annotations are not processed at runtime.

Also the documentation at https://spotbugs.readthedocs.io/en/stable/migration.html#guide-for-migration-from-findbugs-3-0-to-spotbugs-3-1 recommends to make this dependency optional, so by default it will not propagate into downstream projects.

**Describe the solution you'd like**

The dependency on spotbugs-annotations should be optional.

**Describe alternatives you've considered**

Alternatively, the dependency could be excluded by downstream projects but this requires an effort for every project. A sane default with the "optional" dependency would be preferred.

**Comment by nenaraab** [comment]
Hi @calle2010 thanks a lot for raising this issue 👍 . Will fix that in the upcoming version.
