### ISSUE TITLE
Implement websocket security through xsuaa

### ISSUE THREAD

**Issue by michael-kong** [SAP/cloud-security-xsuaa-integration#854]
Hi, Our project is deployed on SAP BTP, using xsuaa for permission verification. At present, we have a requirement to use websocket as a communication tool in the project, but at present I only found the example of the integration of Spring Security and websocket on the Internet, and I have not found the example of the integration of xsuaa and websocket. Is it feasible to implement websocket security through xsuaa? If it is feasible, is there any specific example for reference?

**Comment by nenaraab** [comment]
Hi @michael-kong

We don’t support authentication/authorization checks for `spring-websocket`, only spring security resource server, and therefore there is no example for:
```xml
<groupId>org.springframework</groupId> 
<artifactId>spring-websocket</artifactId> 
```

These are these references I've found in that context:
- https://www.baeldung.com/spring-security-websockets
- https://docs.spring.io/spring-security/site/docs/4.2.x/reference/html/websocket.html

This might be helpful to understand the way it’s currently implemented, like in `spring-security` `hasRole()` requires authorization the `ROLE_`-Prefix that’s why we’ve implemented [XsuaaTokenAuthorizationConverter](https://github.com/SAP/cloud-security-xsuaa-integration/blob/main/spring-security/src/main/java/com/sap/cloud/security/spring/token/authentication/XsuaaTokenAuthorizationConverter.java) to be able to map it to local scopes.

I haven’t found any documentation in how to implement integration. But it might be similar to what is implemented with `spring-security` already?

Kind regards,
Nena

**Comment by nenaraab** [comment]
This issue is without any activity for 14 days or longer. 
Thus, closing the ticket. Please reopen if the issue is still relevant.
