### ISSUE TITLE
Logging PEM Formatted Private Key

### ISSUE THREAD

**Issue by edmundham** [SAP/cloud-security-xsuaa-integration#887]
Hi Team,

I noticed recently that there is a DEBUG log that logs PEM formatted private key.
https://github.com/SAP/cloud-security-xsuaa-integration/blob/main/token-client/src/main/java/com/sap/cloud/security/mtls/SSLContextFactory.java#L145

Should we remove it? As far as I know any secrets should not be logged.

**Comment by nenaraab** [comment]
I've changed it in that way, that it prints only the first and the last 7 characters.
