### ISSUE TITLE
SpringSecurity5 migration issue

### ISSUE THREAD

**Issue by Anti-neutrino** [SAP/cloud-security-xsuaa-integration#906]
Hello colleagues,

We are migrating to SpringSecurity5 in two of our projects. We are using similar spring security configurations for the both apps but one of them is working but the other throws the following exception during the initialization of one of the beans. Here is the exception: 
` 
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'securityConfiguration': Unsatisfied dependency expressed through field 'xsuaaServiceConfiguration'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'xsuaaServiceConfiguration' defined in com.sap.xs.auditlog.viewer.util.SecurityConfiguration: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.sap.cloud.security.xsuaa.XsuaaServiceConfiguration]: Circular reference involving containing bean 'securityConfiguration' - consider declaring the factory method as static for independence from its containing instance. Factory method 'xsuaaServiceConfiguration' threw exception; nested exception is java.lang.NullPointerException","\tat org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:659)","\tat org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:639)",
`
I have tried to use the spring security configurations with spring-security.xml and Java-based configuration but the result is the exception above in both scenarios. Have you observed such exception before? Do you have an idea what might be causing this problem?

Best regards,
Momchil

**Comment by nenaraab** [comment]
Hi @Anti-neutrino 

can you please share with us some migration details. Previous dependencies in pom.xml (`mvn dependency:tree`), actual dependencies... which migration guide, docs, samples have you used etc...

Thanks in advance!
Nena

**Comment by Anti-neutrino** [comment]
Hi,

We are following the spring-xsuaa-sample app for the spring security configurations: https://github.wdf.sap.corp/i340902/spring-xsuaa-sample/blob/766caf3d7b594985b0a764923b649a9d9d02403c/src/main/java/sample/spring/xsuaa/SecurityConfiguration.java.

These are the dependencies in the pom.xml:
Previous dependencies:
`
			<groupId>org.springframework.security.oauth</groupId>
			<artifactId>spring-security-oauth2</artifactId>
			<version>2.5.1</version>
`
Current dependencies: 
`
<dependency>
				<groupId>org.springframework.security</groupId>
				<artifactId>spring-security-oauth2-jose</artifactId>
				<version>5.6.3</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.security</groupId>
				<artifactId>spring-security-config</artifactId>
				<version>5.6.3</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.security</groupId>
				<artifactId>spring-security-oauth2-resource-server</artifactId>
				<version>5.6.3</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.security</groupId>
				<artifactId>spring-security-oauth2-client</artifactId>
				<version>5.6.3</version>
			</dependency>
			<dependency>
				<groupId>com.sap.cloud.security.xsuaa</groupId>
				<artifactId>spring-xsuaa</artifactId>
				<version>2.11.15</version>
			</dependency>
			<dependency>
				<groupId>org.apache.logging.log4j</groupId>
				<artifactId>log4j-to-slf4j</artifactId>
				<version>2.17.2</version>
			</dependency>
`
Best regards,
Momchil

**Comment by nenaraab** [comment]
Hi @Anti-neutrino 
thanks for the details 👍 
Unfortunately there is from Spring projects and also not from our side a dedicated migration guide given.

But in case of a **native Java project** there is a guide on how to set it up:
https://github.com/SAP/cloud-security-xsuaa-integration/tree/main/java-security 

> ** Note** java-security is also built in as part of SAP (XSA) Java Buildpack. There you can define roles /authorization check as part of web.xml (Servlet Security), see [buildpack sample app](https://github.com/SAP/cloud-security-xsuaa-integration/tree/main/samples/sap-java-buildpack-api-usage).

In case of a **Spring project** this guide is the one to choose:
https://github.com/SAP/cloud-security-xsuaa-integration/tree/main/spring-security 

> **Note** this is a successor of `spring-xsuaa` which supports as well IAS token validation. Like in `spring-xsuaa` project there are some autoconfigurations, that are required to autowire Spring Beans, such as `xsuaaServiceConfiguration`.

**Comment by Anti-neutrino** [comment]
Hi @nenaraab ,
We have found out the problem and fix it. Thank you for your support.

**Comment by nenaraab** [comment]
Hi @Anti-neutrino thanks a lot for feedback and closing!
