### ISSUE TITLE
It is possible to init the SpringSecurityContext when we only receive the tenant_id (subdomain) from an incoming message?

### ISSUE THREAD

**Issue by culebras** [SAP/cloud-security-xsuaa-integration#913]
**Question Summary**
- client library:  xsuaa-spring-boot-starter - v 2.12.2
- Environment: Cloud Foundry

Hi,

Outside of the context of HTTP requests (https://github.com/SAP/cloud-security-xsuaa-integration/tree/main/spring-xsuaa#setup-security-context-for-non-http-requests) you are proposing to just use the received token to initialize the `SpringSecurityContext`. That means that the token should be propagated inside the message headers in case we are working with a message broker such as Rabbit or Kafka.

While that approach works for us: for example if we are receiving a Kafka event in our spring-boot service, and in the event the token was supplied in the message headers, that can be a potential security problem, as Kafka is a distributed log system, therefore the events are stored in disk.

In the other hand, we cannot relay that all systems that are posting messages to our Kafka topics will have available a JWT token to propagate into the message headers, at most, they will be able to just setup a TENANT message header containing the tenant id (~subdomain).

So the question is: it is possible in our spring-boot service to initialize the `SpringSecurityContext` when we are just receiving the tenant id in the incoming Kafka message headers? Our service is bound to the `xsuaa` instance in our CF space.

Thanks,
F.

**Comment by culebras** [comment]
Actually we found the way to do it. It is possible to retrieve the token just knowing the tenant provided in the Kafka message header by using the `clientCredentialsTokenFlow()` passing the tenant as the value for `zoneId`.

So I guess this issue could be closed.

**Comment by nenaraab** [comment]
@culebras thanks a lot for sharing your use case and solution. 
Wish you all the best!
