### ISSUE TITLE
NPE if uri is wrong, and uir.getHost() returns null then

### ISSUE THREAD

**Issue by sim-lus** [SAP/cloud-security-xsuaa-integration#943]
https://github.com/SAP/cloud-security-xsuaa-integration/blob/afd832741ac6b91be06dc4215de3e080d7d4fb8e/token-client/src/main/java/com/sap/cloud/security/xsuaa/util/UriUtil.java#L54

**Comment by liga-oz** [comment]
thanks for reporting a bug 👍🏻
